### ISSUE TITLE
nix profile error message mentions nix-env and priorities

### ISSUE THREAD

**Issue by tomberek** [NixOS/nix#6406] opened 2022-04-14 19:54 UTC
**Describe the bug**
File conflicts between independent installables placed into a profile with `nix profile` causes a conflict in builtin:buildenv that mentions nix-env.

**Steps To Reproduce**
```
[tom@tframe:~/nix]$ nix profile install nixpkgs#hello

[tom@tframe:~/nix]$ nix profile install github:NixOS/nixpkgs/21.11#hello
error: packages '/nix/store/g124820p9hlv4lj8qplzxw1c44dxaw1k-hello-2.12/share/info/hello.info' and '/nix/store/bycfqd9pi8ik14dflid8h71ib926icg7-hello-2.10/share/info/hello.info' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
```

**Expected behavior**
Error message should be appropriate for the CLI style used.
nix (Nix) 2.8.0pre20220410_8b197c4

**Comment by elikoga** [comment] 2022-05-11 10:18
Duplicate of #6143

**Comment by elikoga** [comment] 2022-05-24 13:02
Can be closed most probably

**Closed** 2022-05-24 22:28 UTC
Labels: bug, UX
