### ISSUE TITLE
wrong default value 4294967295 in nix.conf man page

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nix#7020] opened 2022-09-10 08:40 UTC
**Describe the bug**

the `tarball-ttl` default value reported in the nix.conf man page is wrong, in https://github.com/NixOS/nix/blob/8d84634e26d6a09f9ca3fe71fcf9cba6e4a95107/src/libstore/globals.hh#L542 the default is set to 60*60 which is 3600 but the man page has 4294967295

**Steps To Reproduce**

1. search `tarball-ttl` in nix.conf man page
2. the default is 4294967295,
3. it should be 3600
4. 4294967295 is the maximum value of an unsigned int https://en.wikipedia.org/wiki/4,294,967,295

**Comment by NobbZ** [comment] 2022-09-10 10:47
Duplicate of #6914

**Closed** 2022-09-10 10:57 UTC
Labels: bug
