### ISSUE TITLE
`nix log` cannot show log without `<INSTALLABLE>`

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nix#2332] opened 2018-08-05 11:08 UTC
This issue is related to Nix 2.0 UX.

Nix 2.0 introduced the command `nix build` where it is possible to call it without attributes. For instance:

```
nix build-f <FILE>
```

To retrieve the log of such a build I presumed the same command-line could be used to refer to the same derivation:

```
nix log -f <FILE>
```

However, this results in the following error:

```
error: more arguments are required
Try 'nix --help' for more information.
```

I tried to add an attribute that referred to the root of the file, but without succes:

```
nix log -f <FILE> self
nix log -f <FILE> .
nix log -f <FILE> ""
```
I think the `nix log` is too strict on its command-line arguments. It should operate exactly the same as `nix build`.

**Comment by bobvanderlinden** [comment] 2018-08-08 20:40
I saw this is caused because `nix log` requires `<INSTALLABLE>`, which is required. Whereas `nix build` requires `<INSTALLABLES>`, which is also required, but may be empty.

I want to try to make `nix log` act the same way as `nix build` in this regard.

**Comment by lheckemann** [comment] 2018-08-12 18:56
duplicate of #2066

**Closed** 2018-08-12 19:43 UTC
