### ISSUE TITLE
`nix copy` consumes unbounded memory in some cases

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nix#3386] opened 2020-03-04 21:42 UTC
I have a Nix store that contains at present:

- 271G of data
- 135,333 entries (i.e., `ls -l /nix/store | wc -l`)

Copying just `/run/current-system/sw` resulted in copying 830 entries, with a total size of 12.4G. However, while copying the system becomes almost unusable. There are 20 jobs running, with Activity Monitor showing 600% CPU utilization and ~5GB of RAM in use. Seems like a lot of RAM for 830 entries...

In fact, for an operation that's essentially just compressing and copying a stream of bytes from one location to another — both local — I'm surprised there's any real memory use at all.

If I bump this operation up to `nix copy --all`, the `nix` process runs all CPUs flat out, causes the mouse to stop moving on the screen for a while, and consumes 64+ GB of memory (all available) before being OOM killed by the kernel.

**Comment by edolstra** [comment] 2020-03-05 10:33
Copying between local stores should run in bounded memory:
```
$ command time nix copy --from /tmp/nix2 --to /tmp/nix3 /run/current-system --no-check-sigs
[1409 copied (5342.9 MiB)]
58.24user 26.93system 0:37.05elapsed 229%CPU (0avgtext+0avgdata 34580maxresident)k
10708064inputs+11664984outputs (44major+33982minor)pagefaults 0swaps
```
However, copying to a binary cache requires NARs to be loaded into memory because `BinaryCacheStore::addToStore()` doesn't support streaming NARs (unlike `LocalStore::addToStore()`). In combination with parallelism this can lead to high memory consumption. Currently there is no option to reduce parallelism, but as a workaround you can do something like `taskset 1 nix copy ...` to pretend that there is only one CPU available.

**Comment by jwiegley** [comment] 2020-03-05 15:39
Aha, I'll try local stores, thanks Eelco.

**Comment by jwiegley** [comment] 2020-03-05 17:30
Leaving open until there's a way to stream NARs...

**Comment by jwiegley** [comment] 2020-03-05 17:53
@edolstra A new problem: Now that I'm copying between stores, instead of to a binary cache, how do I get Nix to use this copied store when an output path doesn't already exist in my main store? I want to use this second store _as a binary cache_.

**Comment by edolstra** [comment] 2020-03-05 19:11
Using the `substituters` option/flag, e.g. `--substituters /path/to/other/store`. You can use any store as a substituter. The NixOS installer uses this to copy paths from the installation CD.

**Comment by AleXoundOS** [comment] 2020-04-14 19:21
The issue is pretty much a duplicate of #1681 and #2774.

**Comment by domenkozar** [comment] 2020-04-15 07:39
Agreed.

**Closed by domenkozar** 2020-04-15 07:39 UTC
