### ISSUE TITLE
`nix profile install` does not accept `--expr=` flag contrary to what documentation indicates

### ISSUE THREAD

**Issue by mkoloberdin** [NixOS/nix#9439] opened 2023-11-22 12:24 UTC
**Describe the bug**

```
$ nix --version
nix (Nix) 2.20.0pre20231122_3884494
```

Attempting to do this:
```
NIXPKGS_ALLOW_UNFREE=1 nix profile install -L --debug --impure --expr='(with import <nixpkgs> {}; openai-whisper.override { cudaSupport = true; })'
```
(Please correct me if I'm trying to do it wrong BTW)

...produces:
```
error: unrecognised flag '--expr=(with import <nixpkgs> {}; openai-whisper.override { cudaSupport = true; })'
Try 'nix --help' for more information.
```
Removing `-L --debug --impure` does not make any difference.

**Steps To Reproduce**

As described above.

**Expected behavior**

`nix profile install --help` says:
```
[--expr](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-install#opt-expr) expr

Interpret [installables](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix#installables) as attribute paths relative to the Nix expression expr.
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by mkoloberdin** [comment] 2023-11-22 12:27
Looks like I've misread the documentation. `--expr ...` rather than `--expr=...` seems to act as documented.

**Comment by thufschmitt** [comment] 2023-11-23 17:08
I'll close this since it's indeed the current expected behavior, but I've opened https://github.com/NixOS/nix/issues/9442 to consider supporting `--foo=bar` as it's very standard and useful to have.

**Closed by thufschmitt** 2023-11-23 17:08 UTC
Labels: bug

**Comment by ditsuke** [comment] 2024-06-13 04:59
Is it expected to get a "args are incompatible with flakes"?
```
❯ nix profile install nixpkgs#pgadmin --arg server-mode false         
error: '--arg' and '--argstr' are incompatible with flakes
Try 'nix --help' for more information.
```
