### ISSUE TITLE
NUL bytes in JSON input are not handled correctly

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nix#10826] opened 2024-06-02 12:02 UTC
**Describe the bug**

- When decoding JSON, `\u0000` is accepted in input strings, but doesn't cause a failure (e.g. `builtins.readFile` would fail if it encounters a NUL byte).
- Strings seem to be cut off on the first NUL byte.
- Keys of attribute sets retain the NUL byte (it can be recovered with `builtins.toJSON`), but not across conversions (e.g. via `builtins.attrNames`). This creates bizarre attributes that can't be accessed. ~~Also, the rendering between `nix repl` and `nix-instantiate` is not consistent here.~~ (only observed in Nix 2.3)

**Steps To Reproduce**

**Strings**

```
Welcome to Nix 2.18.2. Type :? for help.

nix-repl> builtins.fromJSON ''"foo\u0000bar"''
"foo"

nix-repl> builtins.stringLength (builtins.fromJSON ''"foo\u0000bar"'')
3

nix-repl> builtins.fromJSON ''"foo\u0000bar"'' == "foo"                
true
```

**Attribute sets**

```
nix-repl> builtins.fromJSON ''{ "foo\u0000bar" : 2, "foo" : 1 }''              
{ foo = 1; "foobar" = 2; }     

nix-repl> (builtins.fromJSON ''{ "foo\u0000bar" : 2, "foo" : 1 }'')."${builtins.fromJSON ''"foo\u0000bar"''}" 
1

nix-repl> builtins.toJSON (builtins.fromJSON ''{ "foo\u0000bar" : 2, "foo" : 1 }'')
"{\"foo\":1,\"foo\\u0000bar\":2}"

nix-repl> builtins.attrNames (builtins.fromJSON ''{ "foo\u0000bar" : 2, "foo" : 1}'')
[ "foo" "foo" ]

nix-repl> builtins.map (x: x == "foo") (builtins.attrNames (builtins.fromJSON ''{ "foo\u0000bar" : 2, "foo" : 1 }''))
[ true true ]
```

**Expected behavior**

Nix strings (given that they are byte strings without NUL) should reject such JSON input.

**Comment by roberth** [comment] 2024-06-09 22:53
Indeed strings `Value`s are represented by `NUL`-terminated C strings, whereas `Symbol`s, which back attribute names, are backed by `std::string`s.

Indeed as a mitigation, Nix should throw an error when it cannot convert a string losslessly.

I'd be supportive of a change to make `NUL` bytes representable in strings if it's not too much of a burden. Cc @tomberek.

**Comment by lheckemann** [comment] 2024-06-10 09:27
Duplicate of https://github.com/NixOS/nix/issues/10317 ?

**Comment by roberth** [comment] 2024-06-10 10:49
Closing as duplicate of #10317

Thanks @lheckemann and @sternenseemann for reporting.

**Closed by roberth** 2024-06-10 10:49 UTC
Labels: bug, language
