### ISSUE TITLE
Nix "disables some network-dependent features" prematurely

### ISSUE THREAD

**Issue by unappetizing-morsel** [NixOS/nix#10276] opened 2024-03-21 05:21 UTC
**Describe the bug**

When `haveInternet` is `false` Nix unconditionally behaves as if `--offline` was passed on the CLI and Nix cannot be configured to not act this way.

**Steps To Reproduce**

1. Have a system where [`haveInternet()`][] is `false`.

    - A locally hosted virtual machine not connected to any network is a reasonable example environment.

2. Configure `nix.conf` to set `substitute = true` or any setting that would be affected by `--offline`.
3. Show the current config and check those settings.
 
    ```
    $ nix --extra-experimental-features nix-command show-config
    warning: you don't have Internet access; disabling some network-dependent features
    ...
    connect-timeout = 1
    download-attempts = 0
    substitute = false
    tarball-ttl = 4294967295
    ...
    ```

**Expected behavior**

It is OK for Nix to try to infer `--offline` through whatever heuristic it pleases, but please add a `nix.conf` setting to enable explicitly opting out of the `--offline` inference feature.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.18.1
```

Debian testing (13/trixie) package of Nix, but the same relevant code appears on main branch as is in the `2.18.1` tag.

**Additional context**

A legitimate scenario where `haveInternet` would be `false` but Nix should not behave as if `--offline` was on the CLI would be a virtual machine where a systemd socket listens at `127.0.0.1:22` and will launch a systemd template service on connection that effectively provides a TCP connection over a hypervisor-specific technology.

In this scenario inferring `--offline` could interfere with substituting from a substituter like `ssh://user@127.0.0.1`.

In `src/nix/main.cc` see:

- [`warning: you don't have Internet access; disabling some network-dependent features`](https://github.com/NixOS/nix/blob/7d2ead50e5ee6223f2ca3e5c80695f209ae4eb9a/src/nix/main.cc#L489)
- [`--offline`](https://github.com/NixOS/nix/blob/7d2ead50e5ee6223f2ca3e5c80695f209ae4eb9a/src/nix/main.cc#L494)
- [`haveInternet()`][]

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

[`haveInternet()`]: <https://github.com/NixOS/nix/blob/7d2ead50e5ee6223f2ca3e5c80695f209ae4eb9a/src/nix/main.cc#L54> "/* Check if we have a non-loopback/link-local network interface. */"

**Comment by thufschmitt** [comment] 2024-03-21 15:20
Dupe of #8216. Closing to keep the discussion in one place.

**Closed by thufschmitt** 2024-03-21 15:20 UTC
Labels: bug
