### ISSUE TITLE
Quadratic scaling of `--print-out-paths` when repeated buildable specified

### ISSUE THREAD

**Issue by johnrichardrinehart** [NixOS/nix#9528] opened 2023-12-03 21:37 UTC
**Describe the bug**

```bash
$ for n in {1..10}; do 
   nix build $(printf 'github:nixos/nixpkgs#hello %.0s' {1..$n}) --print-out-paths | wc -l
done
1
4
9
16
25
36
49
64
81
100
```

**Expected behavior**

```bash
$ for n in {1..10}; do 
   nix build $(printf 'github:nixos/nixpkgs#hello %.0s' {1..$n}) --print-out-paths | wc -l
done
1
2
3
4
5
6
7
8
9
10
```

```bash
$ nix --version                              
nix (Nix) 2.17.1
```

**Comment by alois31** [comment] 2024-03-17 10:25
Is this a duplicate of https://github.com/NixOS/nix/issues/9042?

**Comment by thufschmitt** [comment] 2024-03-18 08:17
It is, indeed. Closing in favour of #9042 then to keep the discussion in one place

**Closed by thufschmitt** 2024-03-18 08:17 UTC
Labels: bug
