### ISSUE TITLE
nix-daemon is slow to download files from the cache

### ISSUE THREAD

**Issue by stapelberg** [NixOS/nix#1128] opened 2016-11-12 13:30 UTC
I’m currently rebuilding my system to enable debug symbols for all packages.

A long time (many tens of minutes) is spent in just downloading files from the cache. Take this representative example, sampled from hundreds of others which show the same behavior:

```
*** Downloading ‘https://cache.nixos.org/nar/1wyksagbra4m12z5qka02jnaylc9w93szg36yxm9h4c93bszr0ci.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/6ida1j75qnn82q3i0z7hz1x03w0kg4hs-ghostscript-9.20.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.7M  100 24.7M    0     0  1220k      0  0:00:20  0:00:20 --:--:-- 1330k
```

The reported speed (1.3 MB/s, 20s for 24MB) strikes me as unusually slow:
* The reported load average during the rebuild is `0,08, 0,07, 0,02`, so the rebuild is not CPU bound.
* I’m using an SSD, so I don’t assume the rebuild is I/O bound either.
* I’m on a 1 Gbps fiber ethernet connection and my provider has a direct network interconnect with amazon. I frequently reach download speeds of ≥ 100 MB/s. In fact, when repeating the same download just a couple of seconds later, I see:

```
$ wget -O/dev/null https://cache.nixos.org/nar/1wyksagbra4m12z5qka02jnaylc9w93szg36yxm9h4c93bszr0ci.nar.xz
--2016-11-12 14:20:35--  https://cache.nixos.org/nar/1wyksagbra4m12z5qka02jnaylc9w93szg36yxm9h4c93bszr0ci.nar.xz
Resolving cache.nixos.org (cache.nixos.org)... 2600:9000:200c:ec00:10:dfa4:b0c0:93a1, 2600:9000:200c:4000:10:dfa4:b0c0:93a1, 2600:9000:200c:5c00:10:dfa4:b0c0:93a1, ...
Connecting to cache.nixos.org (cache.nixos.org)|2600:9000:200c:ec00:10:dfa4:b0c0:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25973788 (25M) [binary/octet-stream]
Saving to: ‘/dev/null’

/dev/null                                        100%[=======================================================================================================>]  24,77M  19,9MB/s    in 1,2s    

2016-11-12 14:20:36 (19,9 MB/s) - ‘/dev/null’ saved [25973788/25973788]
```

I’m wondering whether this is because of the way the curl/xz/nix-store processes are wired up?

```
root     30420  0.0  0.0  50288  5480 ?        Ss   14:17   0:00 nix-daemon --daemon
root     30437  0.9  0.2  70920 17536 ?        Ssl  14:17   0:02  \_ nix-daemon 30436
root     30440  0.0  0.2 207556 21832 ?        S    14:17   0:00      \_ /nix/store/r9ww7pwkmphr1zbwb1sfnjw9d2y90js2-perl-5.22.2/bin/perl -w -I/nix/store/vfjzlc2si28i2yslaay7413iqvv84ixp-nix-1.11.4 /nix/store/vfjzlc2si28i2yslaay7413iqvv84ixp-nix-1.11.4/libexec/nix/substituters/download-from-binary-cache.pl --query
root     30757  0.0  0.2 206228 20448 ?        Ss   14:21   0:00      \_ /nix/store/r9ww7pwkmphr1zbwb1sfnjw9d2y90js2-perl-5.22.2/bin/perl -w -I/nix/store/vfjzlc2si28i2yslaay7413iqvv84ixp-nix-1.11.4 /nix/store/vfjzlc2si28i2yslaay7413iqvv84ixp-nix-1.11.4/libexec/nix/substituters/download-from-binary-cache.pl --substitute /nix/store/2nmvd0m2iwhqcj64012yfj5i49f3hiyj-gnome-bluetooth-3.20.0.tar.xz /nix/store/2nmvd0m2iwhqcj64012yfj5i49f3hiyj-gnome-bluetooth-3.20.0.tar.xz
root     30758  0.0  0.0 125136  3100 ?        S    14:21   0:00          \_ sh -c /nix/store/zs006n5dlp80fy5g54rdcfipwf7kca8b-curl-7.50.3-bin/bin/curl --fail --location --connect-timeout 0 -A 'Nix/1.11.4' 'https://cache.nixos.org/nar/1nsbw12hd9d3c0rjmixfr5i8ddvmm0prsh21hxr79g0wd6b909k1.nar.xz' | /nix/store/zn2a3m1if5vsz7h9gnijywkj44va1hws-xz-5.2.2-bin/bin/xz -d | /nix/store/vfjzlc2si28i2yslaay7413iqvv84ixp-nix-1.11.4/bin/nix-store --restore /nix/store/2nmvd0m2iwhqcj64012yfj5i49f3hiyj-gnome-bluetooth-3.20.0.tar.xz
root     30759  0.0  0.0 134712  6340 ?        S    14:21   0:00              \_ /nix/store/zs006n5dlp80fy5g54rdcfipwf7kca8b-curl-7.50.3-bin/bin/curl --fail --location --connect-timeout 0 -A Nix/1.11.4 https://cache.nixos.org/nar/1nsbw12hd9d3c0rjmixfr5i8ddvmm0prsh21hxr79g0wd6b909k1.nar.xz
root     30760  0.0  0.0 119304   400 ?        S    14:21   0:00              \_ /nix/store/zn2a3m1if5vsz7h9gnijywkj44va1hws-xz-5.2.2-bin/bin/xz -d
root     30761  0.0  0.0  52376  4432 ?        S    14:21   0:00              \_ /nix/store/vfjzlc2si28i2yslaay7413iqvv84ixp-nix-1.11.4/bin/nix-store --restore /nix/store/2nmvd0m2iwhqcj64012yfj5i49f3hiyj-gnome-bluetooth-3.20.0.tar.xz
```

Hence, I have the following questions:

1. Can we make the nix-daemon use libcurl instead of an out-of-process curl, so that we get pipelining, keepalive, etc.? Downloading many small files is _way_ faster when re-using the same TCP connection (which keeps the window size high).
2. Would it be beneficial to decouple the steps (curl, xz, nix-store) into distinct phases?

Thanks!

**Comment by vcunat** [comment] 2016-11-13 09:44
- Note that multiple jobs are done in parallel in typical setup so it's normal to have lower speed on each.
- I typically get full utilization of my link when substituting (100 Mbit/s), on an old notebook with 5400 rpm HDD.
- (Question 1) The download isn't done by nix (daemon) itself but by the substituter. I think that one was recently rewritten from perl to c++ as part of https://github.com/NixOS/nix/issues/341 but it's not in any released version yet.
- Question 2: I don't think so.

**Comment by stapelberg** [comment] 2016-11-13 11:28
> Note that multiple jobs are done in parallel in typical setup, so it's normal to have lower speed on each.

How can I verify whether this is happening for me? It certainly _looks_ like only one job is going on at a time, but I’m not 100% sure. In `/etc/nix/nix.conf`, I can see `build-max-jobs = 4`, and the actual compilation output intersperses multiple different builds, but I’m not sure whether that applies to downloading, too?

**Comment by vcunat** [comment] 2016-11-13 19:20
IIRC `build-max-jobs`, overridable by `-j`, is used to schedule a common pool of all locally-run jobs, including downloads, substitutes, and "regular builds". There may be inter-dependencies among those resulting into lower utilization at times...

**Comment by fpletz** [comment] 2016-11-23 01:11
This is due to nghttp2 which curl uses for HTTP/2 support. See https://github.com/NixOS/nixpkgs/pull/20639.

**Comment by domenkozar** [comment] 2016-11-23 12:08
Relevant: https://github.com/NixOS/nix/commit/90ad02bf626b885a5dd8967894e2eafc953bdf92

**Comment by domenkozar** [comment] 2016-11-23 12:35
See also how to reproduce this only using curl https://github.com/NixOS/nixpkgs/pull/20639#issuecomment-262501454

**Comment by domenkozar** [comment] 2016-11-23 13:21
This is going to be fixed in following day in nixpkgs repo for `master` and release-16.09`. Thanks for the report!

**Closed by domenkozar** 2016-11-23 13:21 UTC
