### ISSUE TITLE
gettext fails to build on OS X

### ISSUE THREAD

**Issue by andykitchen** [NixOS/nix#465] opened 2015-01-31 00:26 UTC
On yosemite, gettext fails to build with this error:

```
areadlink.c:41:13: error: use of undeclared identifier 'AT_FDCWD'
  if (fd != AT_FDCWD)
            ^
areadlink.c:55:24: error: use of undeclared identifier 'AT_FDCWD'
  return careadlinkat (AT_FDCWD, filename, NULL, 0, NULL, careadlinkatcwd);
                       ^
```

**Comment by iElectric** [comment] 2015-02-01 13:12
You might want to try reinstalling xcode, see https://trac.macports.org/ticket/45734

**Comment by andykitchen** [comment] 2015-02-03 01:05
So this is my bad, I was trying to use mainline nix on Yosemite, but I found the wiki page telling me to use https://github.com/joelteon/nixpkgs.git which seems to work ok. Although it seems to have quite heavily diverged from the nix mainline

```
$ git log --oneline $(git merge-base unstable/master joelteon/master)..unstable/master | wc -l
436
```

So I did a little digging into this problem and here is what I found:

```
$ grep AT_FDCWD /usr/include/sys/fcntl.h
#define AT_FDCWD	-2

$ grep AT_FDCWD /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/fcntl.h 
#define AT_FDCWD	-2

$ grep AT_FDCWD /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.0.sdk/usr/include/sys/fcntl.h
# nothing

$ grep -r AT_FDCWD /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk 
# nothing
```

So on Yosemite, the 10.9 SDK headers don't define AT_FDCWD but the system headers and the 10.10 SDK headers do define AT_FDCWD. So my guess is that the configure script is picking up the system headers so it believes that AT_FDCWD is available and then for whatever reason the compiler is using the 10.9 SDK instead.

Unfortunately this problem makes nix mainline practically unusable on Yosemite because gettext is a transitive dependency of most packages. That being said joelteon/nixpkgs seems to compile some common packages even if they are outdated.

I fell as though this problem is probably a symptom of a much larger move to Yosemite, so feel free to close. Thanks for your time.

Kind Regards

AK

**Comment by copumpkin** [comment] 2015-02-05 16:23
@andykitchen the issue is fixed in our upcoming [pure-darwin](https://github.com/copumpkin/nixpkgs) branch, so I'd recommend closing this.

The actual problem here is that Apple added a big load of `*at` versions of its syscalls for better atomic properties in 10.10. Most configure scripts actually don't even look at headers when checking for those calls, so they try linking against `libSystem` (happens by default), notice that when they try using the `*at` symbols they don't get linker errors, and then declare the functions to be usable. Later on, during compilation, they try using the functions and they fail because the headers don't define them.

**Comment by andykitchen** [comment] 2015-02-11 03:59
Sorry reopened, there really needs to be some kind of message on the download page telling you that Mac OS 10.10 is broken at the moment. It took me a least 2 hours and a lot of googling to get nix properly up and running.

**Closed** 2020-04-30 08:43 UTC
Labels: backlog
