### ISSUE TITLE
Flakes: Enhance Error when Files are not Added to Git

### ISSUE THREAD

**Issue by Malix-off** [NixOS/nix#11253] opened 2024-08-04 09:59 UTC
## Problem

Currently, about flakes development, the error when files are not added to git are not that helpful

## Proposed Solution

Would be nice if nix inspected the source tree and if an untracked file did exist there, that it would give you a more helpful error to run `git add -- <file>`

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by hraban** [comment] 2024-08-04 16:26
It would be nice if this functionality included support for the `flake.nix` file itself

**Comment by edolstra** [comment] 2024-08-05 14:44
Duplicate of #4507.

**Closed by edolstra** 2024-08-05 14:44 UTC
Labels: feature

**Comment by Malix-off** [comment] 2024-08-05 15:39
thanks @edolstra !

By the way, if you edit [your comment](https://github.com/NixOS/nix/issues/11253#issuecomment-2269251646) by making its content only strictly be "Duplicate of #ID", [it will be marked as duplicate](https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate#marking-duplicates)

**Comment by hraban** [comment] 2024-08-05 21:36
We're at risk of losing the 43 👍 votes for this issue if it just gets closed and marked as dupe without consolidating those, somehow. Don't know how much that matters but since the issue template explicitly asks for it, it might be at least somewhat relevant.

**Comment by Malix-off** [comment] 2024-08-05 21:38
Indeed, the upvote differential is quite significant
