### ISSUE TITLE
Disabling color output for nix-instantiate

### ISSUE THREAD

**Issue by w0rp** [NixOS/nix#2045] opened 2018-04-05 11:53 UTC
Hello! I'm not sure if this is the right GitHub project to ask a question on, and I don't really know what `nix` is, but is there an option for `nix-instantiate` for disabling terminal color output for warnings or errors? I maintain a Vim plugin for checking for problems with files, and someone [raised an issue](https://github.com/w0rp/ale/issues/1454) where it looks like that's the problem for them. Maybe setting `TERM` to something else would help? If anyone has any answers, let me know, or somewhere else where I can post this question.

**Comment by regnat** [comment] 2018-04-05 12:09
This is indeed the right place to ask.

It looks like this is a regression in nix 2.0 as it used to disable colors in case stderr isn't a terminal

**Comment by w0rp** [comment] 2018-04-05 12:31
Make sense. The command will be being run from NeoVim's job control functionality, and maybe that's passing on the right environment variables to make the program think it's being run from a terminal. I can override the environment variables in the plugin, so maybe there's something I can do from ALE.

**Comment by edolstra** [comment] 2018-04-05 13:31
This was fixed in 486872150638d56483c2bc429ba9e137d9974ee8.

**Closed by edolstra** 2018-04-05 13:31 UTC

**Comment by w0rp** [comment] 2018-04-05 13:37
Okay, thank you for fixing this so quickly! :+1:
