### ISSUE TITLE
macOS Montery 12.5.1 install failed

### ISSUE THREAD

**Issue by somebodyLi** [NixOS/nix#6947] opened 2022-08-24 10:38 UTC
os details:
![截屏2022-08-24 18 35 42](https://user-images.githubusercontent.com/32901980/186397688-d1061c39-47a6-4692-a43f-046c7932c085.png)
install output error:
![截屏2022-08-24 18 33 22](https://user-images.githubusercontent.com/32901980/186398018-d9a57c3d-9d0a-47a7-9bdf-876bc3000b4e.png)

**Comment by abathur** [comment] 2022-08-24 22:51
Looks like a duplicate of #6671

**Comment by somebodyLi** [comment] 2022-08-25 04:14
update brew and update `coreutils` to 9.1 can fix this
`brew update-reset`
`brew upgrade coreutils`

**Closed** 2022-08-25 04:14 UTC
Labels: bug
