### ISSUE TITLE
[macos mojave] Broken install

### ISSUE THREAD

**Issue by J-Swift** [NixOS/nix#2685] opened 2019-02-19 03:24 UTC
Hi there! I recently upgraded to Mojave and ran into an issue with my existing nix 2.0 install. I had this happen on another computer as well and was able to fix it by uninstalling/reinstalling. On this computer, however, I can't seem to get it to reinstall cleanly.

After nuking everything, rebooting, and running the multi-user setup (`nix-2.2.1-x86_64-darwin`), everything reports fine but when I run `nix-shell -p nix-info --run "nix-info -m"` I get `error: unexpected end-of-file`. I've tried other `nix-shell` commands and all error in the same way.

I've attached the same command run with `-v` in case it helps. Let me know if you need any more information.

https://gist.github.com/J-Swift/974d207669bffde761031dbfa2897878

EDIT: just looked in `/var/log/nix-daemon.log` and it shows this output when running the command:

```
accepted connection from pid <unknown>, user jimmy
objc[3373]: +[__NSPlaceholderArray initialize] may have been in progress in another thread when fork() was called.
objc[3373]: +[__NSPlaceholderArray initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by LnL7** [comment] 2019-02-19 17:38
Duplicate of https://github.com/NixOS/nix/issues/2523.

**Closed** 2020-04-30 10:09 UTC
