### ISSUE TITLE
Nix installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by jeremyherve** [NixOS/nix#6199] opened 2022-03-02 23:23 UTC
The following command :

sh <(curl -L https://nixos.org/nix/install)

presented here fails :
https://nixos.org/manual/nix/stable/installation/installing-binary.html

with the following error message:

```console
jdh@thinkpad:~$ sh <(curl -L https://nixos.org/nix/install)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4046  100  4046    0     0  10162      0 --:--:-- --:--:-- --:--:--   98k
downloading Nix 2.6.1 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.6.1/nix-2.6.1-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.ESH8mIO9Ro'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /tmp/nix-binary-tarball-unpack.ESH8mIO9Ro/nix-2.6.1-x86_64-linux.tar.x
Warning: z: No such file or directory
  0 27.3M    0  1362    0     0  23721      0  0:20:06 --:--:--  0:20:06 23894
curl: (23) Failure writing output to destination
/dev/fd/63: failed to download 'https://releases.nixos.org/nix/nix-2.6.1/nix-2.6.1-x86_64-linux.tar.xz'
```

**Comment by abathur** [comment] 2022-03-03 00:36
Does your user have permission to write to /tmp/?

**Comment by jeremyherve** [comment] 2022-03-03 07:31
> Does your user have permission to write to /tmp/?
I guess yes since the following commands works :
jdh@thinkpad:~$ touch /tmp/test
jdh@thinkpad:~$

**Comment by abathur** [comment] 2022-03-03 16:11
Has the installer failed more than once? What if you manually run the curl step?
`curl https://releases.nixos.org/nix/nix-2.6.1/nix-2.6.1-x86_64-linux.tar.xz -o /tmp/test`

**Comment by 21stce** [comment] 2022-03-03 17:06
I just tested this on `Ubuntu 20.04.3 LTS` and it works fine. This is a user error. 

The program should give a reasonable error message, but `sh <(foo)` is not a reliable method to run a program. The manual should not be recommending this.

**Comment by abathur** [comment] 2022-03-03 20:58
> This is a user error.

There's almost certainly something unexpected about their environment if they're seeing this consistently, but I'm not sure that it is anything the reporter has done.

> The program should give a reasonable error message

It is saying all it can really know--the download failed. It might be able to emit a better message if the case here is something the installer can detect before it leaps, but first we'll need to figure out why it's failing (regardless of who is at fault).

>  `sh <(foo)` is not a reliable method to run a program. The manual should not be recommending this.

You may need to cite reasoning or a source? It obviously won't work in any shells (e.g. sh, [fish](https://github.com/NixOS/nix/pull/4985)) that don't support the process substitution syntax--but AFAIK those would all be failing on invocation. It may not be portable/universal, but I'm not aware of any reason it is "unreliable" in the sense that it would have anything to do with the reporter's failure.

**Comment by jeremyherve** [comment] 2022-03-07 07:10
>

**Comment by jeremyherve** [comment] 2022-03-07 07:12
> Has the installer failed more than once? What if you manually run the curl step?
Yes 

> ```
> curl https://releases.nixos.org/nix/nix-2.6.1/nix-2.6.1-x86_64-linux.tar.xz -o /tmp/test
> ```

It works :)

jdh@thinkpad:~$ curl https://releases.nixos.org/nix/nix-2.6.1/nix-2.6.1-x86_64-linux.tar.xz -o /tmp/test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.3M  100 27.3M    0     0  79.9M      0 --:--:-- --:--:-- --:--:-- 79.8M

**Comment by SuperSandro2000** [comment] 2022-03-09 23:18
What shell is your sh? Is it dash? bash? ash? ksh? busybox sh?

**Comment by abathur** [comment] 2022-03-10 00:46
A few more:
- what do `type -a curl` and `which -a curl` report?
- what kind of system is this? Your workstation? A fresh VM? Cloud server?
- if you run the script with "sh -x ..." it should report what it is running as it goes, so that you can manually run the same curl command...

**Comment by jeremyherve** [comment] 2022-03-27 21:51
> What shell is your sh? Is it dash? bash? ash? ksh? busybox sh?
bash

> what do type -a curl and which -a curl report?
/snap/bin/curl

I discovered that :
```curl -L ... -o ... ``` is unable to write in /tmp/ but ```curl -L ... -o ... > /tmp/``` works

So modifying the Nix install script lines 83-84 like follows solves the problem :

```
if command -v curl > /dev/null 2>&1; then
    fetch() { curl -L "$1" > "$2"; }
```

**Comment by 21stce** [comment] 2022-03-29 12:41
If you can reproduce that, a bug needs to be filed with the curl project. This script should not be changed given what you have said despite your best intentions.

**Comment by abathur** [comment] 2022-03-29 14:07
@jeremyherve I found [a comment elsewhere mentioning similar trouble with the curl snap](https://github.com/nvm-sh/nvm/issues/2771#issuecomment-1075613880). Can you install it via apt, remove the snap, and confirm whether the install works?

**Comment by abathur** [comment] 2022-03-29 15:05
> @21stce: If you can reproduce that, a bug needs to be filed with the ~curl~ Ubuntu Snap project.

@jeremyherve I don't _think_ you need to do this:
- I found a report at https://github.com/woutervb/snap-curl/issues/2 that sounds like this issue (unless maybe you've installed a different snap? though it sounds like the issue is intrinsic to creating a snap for curl)

- the links at the bottom of the post document the reporter's own ~journey getting passed from curl -> snap -> snap-curl, so I expect the same would happen to you

- it sounds like a won't/can't fix; the thread suggests that a fix depended on relaxing the confinement, and https://forum.snapcraft.io/t/classic-confinement-request-for-curl/24611/11 indicates that the request was denied

**Comment by 21stce** [comment] 2022-03-30 18:49
Apparently, it's possible to query for the [confinement](https://snapcraft.io/docs/snap-confinement) of a given snap produced binary, so the script could check whether the provided curl is ~~butchered~~  a Snap one, figure out the confinement and then give an error message... 

Or detect the version of bash being used and do something like https://unix.stackexchange.com/questions/83926/how-to-download-a-file-using-just-bash-and-nothing-else-no-curl-wget-perl-et. That way everyone with a recent version of bash gets to enjoy something that works. 

Like a configure script, the installation script just needs to do a lot more work to figure out the environment in which it is operating. 

I'd also have the script detect wget, etc. as a fallback.

**Comment by fare** [comment] 2022-04-23 22:46
> I discovered that : `curl -L ... -o ... ` is unable to write in /tmp/ but `curl -L ... -o ... > /tmp/` works
>
OK, now that we have both an explanation and a solution, can we please adopt the solution?

Explanation: some installations of curl use a private /tmp that makes the `-o /tmp/xxx` unportable and therefore wholly inappropriate.
Solution: use `> /tmp/xxx` redirection which is completely portable instead of the `-o /tmp/xxx` option.

**Comment by fare** [comment] 2022-04-23 22:48
Also, maybe include an explanation as a comment in the source code so there is no regression in the future.

**Comment by abathur** [comment] 2022-04-24 02:04
This sounds like some sort of activism :)

**Comment by fare** [comment] 2022-04-24 03:43
Activism for portable code so the installation script may actually work everywhere, yes.

**Comment by samrose** [comment] 2022-10-15 14:19
> @jeremyherve I found [a comment elsewhere mentioning similar trouble with the curl snap](https://github.com/nvm-sh/nvm/issues/2771#issuecomment-1075613880). Can you install it via apt, remove the snap, and confirm whether the install works?

Can confirm: snap installed version of curl not working with nix installer.

apt-get installed version of curl works with nix installer. Ubuntu 22.04 nix 2.11.1

**Comment by SuperSandro2000** [comment] 2022-10-15 22:21
> Activism for portable code so the installation script may actually work everywhere, yes.

The code is portable in that place, just the snap version of curl is half broken and blocks basic curl flags.

**Comment by fczuardi** [comment] 2024-07-27 14:11
ok, so the workaround is to 

- remove curl from snap
- reinstall curl with apt
- open a new terminal

**Comment by SuperSandro2000** [comment] 2024-07-27 18:34
@fricklerhandwerk can you close this issue as won't fix? This is a common Ubuntu trap with their snap shenanigans.

**Closed** 2024-07-27 18:46 UTC
Labels: bug
