### ISSUE TITLE
Unexpected errors on substitution failures on 2.24.1 release

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#11265] opened 2024-08-07 18:42 UTC
**Describe the bug**

It looks like `nix-2.24.1` counts substitution failures as errors in progress bar.

**Steps To Reproduce**

Run a builder that needs local build and observe error counts:

```
$ nix build --impure --expr 'with import <nixpkgs> {}; lv.override { stdenv = gcc14Stdenv; }'
[0/2 built, 1/0/3 copied (1 failed) (104.0/244.0 MiB), 42.0/54.4 MiB DL] fetching gcc-14.1.0 from https://cache.nixos.org
...
```

**Expected behavior**

There should be no `(1 failed)` reports.

**`nix-env --version` output**: `nix-env (Nix) 2.24.1`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by trofi** [comment] 2024-08-07 18:45
More prominent example could be `glibc`-triggered rebuilds:

```
$ nix build --impure --expr 'with import <nixpkgs> { overlays = [(self: super: { glibc = super.glibc.overrideAttrs (oa: { env.UNUSED = "1"; }); })];}; lv'
[1/0/74 built, 17 copied (102 failed) (30.2/30.3 MiB), 7.8 MiB DL] building glibc-2.39-52 (unpackPhase): calling 'unpackCmd' function hook '_defaultUnpack' /nix/s
```

`(102 failed)`

**Comment by tomberek** [comment] 2024-08-07 21:52
Fixed byhttps://github.com/NixOS/nix/commit/0a00bd07b2421acfb21751a718292affa8c6e837. ?

**Comment by roberth** [comment] 2024-08-07 23:08
- Duplicate of https://github.com/NixOS/nix/issues/11198
- Fixed in https://github.com/NixOS/nix/pull/11257
- Backport to 2.24 in https://github.com/NixOS/nix/pull/11262
- No release as of yet

**Closed** 2024-08-08 09:31 UTC
Labels: bug, new-cli

**Comment by roberth** [comment] 2024-08-08 10:27
No worries. Thank you for early adopting the release!
