### ISSUE TITLE
Make new style command  `$(nix build nixpkgs#hello)/bin/hello` do the same as old style command `$(nix-build -E "with import <nixpkgs> { };hello")/bin/hello` 

### ISSUE THREAD

**Issue by nrolland** [NixOS/nix#5893] opened 2022-01-10 11:02 UTC
**Is your feature request related to a problem? Please describe.**

There is a different behaviour between old style and new style commands.

The new commands `nix build nixpkgs#hello`  outputs the error code

>  ❯ nix build nixpkgs#hello; echo $?
> 0

The old command `nix-build -E "with import <nixpkgs> { };hello"`  outputs the path of the output, as well as the error code

>  ❯  nix-build -E "with import <nixpkgs> { };hello"; echo $?
> /nix/store/q8gfl6gpjcyhq9caabhyq9ylp5jphfic-hello-2.10
> 0

In particular, we can compose the old-style commands with further commands in scripts.
For instance, a common pattern is building and launching at once :

`$(nix-build -E "with import <nixpkgs> { };hello")/bin/hello` 

This is precluded now

`$(nix build nixpkgs#hello)/bin/hello`  builds and err with 
> zsh: no such file or directory: /bin/hello

**Describe the solution you'd like**
I would like the return of new style commands to return the output (or output**S**) as well.

**Describe alternatives you've considered**
The alternative is rewriting the downstream scripts to adapt to either behavour.
This would make two incompatible families of script using either style of command.

**Comment by edolstra** [comment] 2022-01-10 11:57
Duplicate of #5601. As a workaround you can use the `--json` flag:
```
$(nix build --json nixpkgs#hello | jq -r .[].outputs.out)/bin/hello
```

**Closed by edolstra** 2022-01-10 11:57 UTC
Labels: improvement
