### ISSUE TITLE
make nix-store --gc to work as LRU

### ISSUE THREAD

**Issue by yaitskov** [NixOS/nix#7749] opened 2023-02-04 13:31 UTC
Hi,

From time to time nix-store eats up all free space and I had to run nix-store --gc.
Space is consumed by derivations used in nix-shell environments.
So 99% there is no roots when nix-shell is not running and running `nix-store --gc` is very painful in my case, because I need to rebuild lots of libraries when switching between branches with different GHC versions e.g.

File system has access time attribute.
My nixpkgs installation on Debian tracks this file parameter out of the box. 
On NixOs docker image I noticed that after touching file in /nix/store OS updates access time.

So idea is simply order folders /nix/store based on access time of latest modified time of the file inside them and 
delete specified % of that derivations let say first 50%.

**Comment by bjornfor** [comment] 2023-02-04 14:25
I think this is a duplicate of https://github.com/NixOS/nix/issues/7572.

**Comment by yaitskov** [comment] 2023-02-04 14:27
```
for i in /nix/store/* ; do echo "$(find $i -type f -printf "%A+\n"  | sort -r | head -n 1) - $i" ; done > /tmp/latest-access
```


```
#!/bin/bash

DRY_RUN=
DELETE_PERCENT=50
NIX_ROOTS=/nix/store

err() {
    echo "$@" 1>&2
    exit 1
}

while [ $# -ne 0 ] ; do
    case "$1" in
        -r) NIX_ROOTS="$2"; shift;;
        -d) DRY_RUN=1 ;;
        -h) cat<<EOF
nix-store-gc-lru generates least used derivations in nix store
USAGE: nix-store-gc-lru.sh [ -p ] [ -d ] [ -r ]
    -p <percent>     set percent of all least used derivations to be removed
    -d               dry-run - just print pathes to matching derivations
    -r <nix stores>  space separated list of nix storages (by default  /nix/store)
    -h               print help

EOF
            exit 1;;
        -p) DELETE_PERCENT="$2"; shift;;
        *) err "Unknown option: [$1]";;
    esac
    shift
done

for i in $NIX_ROOTS ; do
    [ -d "$i" ] || err "nix root [$i] does not exist"
done

if [[ "$DELETE_PERCENT" =~ ^[1-9][0-9]?$ ]] ; then
    :
else
    err "Bad delete percent [$DELETE_PERCENT] must be in range [0; 100]"
fi


for NROOT in $NIX_ROOTS ; do
    for i in $NROOT/* ; do
        echo "$(find -L $i -type f -printf "%A+\n"  | sort -r | head -n 1) - $i" ;
    done
done | sort > /tmp/$$-nix-derivation-latest-access

TOTAL_LINES=$(wc -l < /tmp/$$-nix-derivation-latest-access)

LINES_TO_DELETE=$[$DELETE_PERCENT * $TOTAL_LINES / 100]

if [ -n "$DRY_RUN" ] ; then
    echo "Delete first [$LINES_TO_DELETE] derivations out of [$TOTAL_LINES]"
    head -n $LINES_TO_DELETE /tmp/$$-nix-derivation-latest-access
else
    head -n $LINES_TO_DELETE /tmp/$$-nix-derivation-latest-access | \
        while read DELPATH ; do
            echo nix-store --delete $DELPATH || break
        done
fi

# rm -rf /tmp/$$-nix-derivation-latest-access

```

**Comment by Ericson2314** [comment] 2023-02-13 23:19
Indeed, closing as duplicate of https://github.com/NixOS/nix/issues/7572

**Closed by Ericson2314** 2023-02-13 23:19 UTC
Labels: feature
