### ISSUE TITLE
Cannot invalidate cache of files fetched in pure evaluation mode

### ISSUE THREAD

**Issue by yshui** [NixOS/nix#9814] opened 2024-01-19 16:57 UTC
**Describe the bug**

The command I tried:

```console
nix eval --option tarball-ttl 0 -vvvv --impure --json --expr 'builtins.fetchTarball { url = "https://code.visualstudio.com/sha/download?build=insider&os=linux-x64"; }'
```

`nix` does not issue any HTTP requests for this command. ~Whereas when running not in `nix-daemon` it does:~

   
   ```
   performing daemon worker op: 19
   performing daemon worker op: 11
   acquiring write lock on '/nix/var/nix/temproots/1337498'
   performing daemon worker op: 1
   using cache entry '{"name":"source","type":"tarball","url":"https://code.visualstudio.com/sha/download?build=insider&os=linux-x64"}' -> '{"etag":"\"0xA97310F638A7224D6CAE5809D7D668BD76D6531AA2511108A014D09B84CD9887\"","lastModified":1705642613}', '/nix/store/la1mp0fp1cqdhrk9w2mbq583dfwsnvyz-source'
   "/nix/store/la1mp0fp1cqdhrk9w2mbq583dfwsnvyz-source"
   ```

~~Additionally, `fetchurl` seems to behave as expected in either case. And without `tarball-ttl 0`, no HTTP request is issued with or without `nix-daemon`, which is expected.~~

This is because I have previously fetched the same url in pure mode:

```console
nix eval --json --expr 'builtins.fetchTarball { url = "https://code.visualstudio.com/sha/download?build=insider&os=linux-x64"; sha256 = "0000000000000000000000000000000000000000000000000000000000000000"; }'
```

Which changed the `immutable`/`locked` column in the `fetcher-cache` database to `1`. And afterwards this url will never be fetched ever again no matter what `tarball-ttl` is.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by yshui** [comment] 2024-01-19 17:07
Same problem with `fetchTree`. And documentation for `tarball-ttl` doesn't mention `fetchTree`. I wonder if `fetchTarball` is broken because it uses the same underlying implementation as `fetchTree`.

In that sense maybe `fetchTree` should respect `tarball-ttl` as well.

**Comment by yshui** [comment] 2024-01-19 17:42
OK, this has nothing to do with `nix-daemon`. The problem is in `fetcher-cache.sqlite`, this particular url has `immutable` (or `locked` as it is referred to in code) set to `1`. (I was using `root` to make `nix` not use nix-daemon, which coincidentally uses a different `fetcher-cache`).

What does `immutable` mean? And what will cause it to be set to `1`?

**Comment by yshui** [comment] 2024-01-19 17:49
Ah I see, if I fetch in pure mode with a `sha256`, it will cause `immutable` to be set to `1`. Later `nix` will never fetch the url again even if I try to fetch with a different `sha256`.

This would break the workflow of: changing `sha256` to something invalid -> run `nix` -> copy the new hash in error message to `sha256`, which is used to update fixed-output derivations. I think this is undesirable.

**Comment by tomberek** [comment] 2024-01-22 15:43
Seems like there are two behaviors and use-cases:

1. This is expected to be a stable URL and thus the cached hash and content are correct, thus there is no need to re-fetch, you already have the desired content.
2. This is known to be unstable, and thus the subsequent "--impure" request should be re-checked.

**Comment by yshui** [comment] 2024-01-22 16:40
> It seems we need conceptually two tables:

This makes sense to me.

But practically we can probably just store table 2. `--impure` queries can have a "sentinel" hash that always triggers a fetch.

**Comment by Ericson2314** [comment] 2024-01-23 15:49
> But practically we can probably just store table 2. --impure queries can have a "sentinel" hash that always triggers a fetch.

How would that work with the TTL? If you claim a different hash than the most recent entry (which, I agree, can perhaps just be an index on table 2) Then you have to redownload. On the other hand, if you have no hash (or the sentinal hash), then you will succeed within the TTL with the current entry's hash.

So I think I almost agree but it's the other way around --- it's the *non-sentinal* hash that always triggers a fetch (if that entry isn't cached).

**Comment by yshui** [comment] 2024-01-24 04:01
Actually, I found another problem that can be solved by this proposal as well.

Right now cache lookup doesn't try to match the hash. So it's possible to have this scenario:

1. You added a fixed url source to a flake.
2. You then generated a `flake.lock`. This caused the url to be download into the store at `storePathA`, let's say its hash is `hashA`. `url -> hashA + storePathA` was stored into the cache.
3. Later, maybe unrelated, you fetched the same url again, and its content has changed. So the cache entry is updated to `url -> hashB + storePathB`.
4. You now try to evalution the flake again. nix will try to fetch the fixed url, and get `storePathB` from the cache. so it will complain that `hashB` doesn't match `hashA`. While the desired the result is nix using `storePathA`, because that's what's locked in `flake.lock`

**Comment by thufschmitt** [comment] 2024-04-03 19:10
(duplicate of https://github.com/NixOS/nix/issues/9905)

**Comment by edolstra** [comment] 2024-04-05 14:18
This no longer happens on master (specifically since cabee9815239af426cece729cb765810b8a716ce), since we no longer set the "immutable" bit on files fetched during `fetchTarball`.

**Closed** 2024-04-05 14:20 UTC
Labels: bug
