### ISSUE TITLE
nix repl renders strings improperly escaped

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nix#4909] opened 2021-06-11 11:40 UTC
**Describe the bug**

`nix repl` prints string values improperly sometimes where pasting the printed expression back into the repl would result in a syntax error due to missing escaping.

**Steps To Reproduce**

Evaluate `''''${checkFlagsArray[@]}''` or `"\${checkFlagsArray[@]}"` into `nix repl` and paste the printed result back:

```
nix-repl> ''''${checkFlagsArray[@]}'' 
"${checkFlagsArray[@]}"

nix-repl> "\${checkFlagsArray[@]}"    
"${checkFlagsArray[@]}"

nix-repl> "${checkFlagsArray[@]}"
error: syntax error, unexpected '@'

       at «string»:1:20:

            1| "${checkFlagsArray[@]}"
             |                    ^
            2|
```

**Expected behavior**

`nix repl` prints `"\${checkFlagsArray[@]}"`

**Additional context**

Affects `nixUnstable` and `nix` 2.13.11.

**Comment by roberth** [comment] 2021-06-16 17:00
This isn't rendering a string, but presenting a Nix language parsing error in a confusing way.
The wrong part is `«string»`, which should have been something like `«repl»`. Below that is your input, not the supposed string your input intends to represent.

Does this look less confusing?

```
nix-repl> "${checkFlagsArray[@]}"
error: syntax error, unexpected '@'

       at «repl»:1:20:

            1| "${checkFlagsArray[@]}"
             |                    ^
            2|
```

An even nicer error would catch this specific mistake and show a custom error message explaining what you probably did wrong. Something like: it seems like you're using bash interpolation syntax inside a Nix interpolated string. Did you forget to escape the $ sign?

**Comment by sternenseemann** [comment] 2021-06-16 17:35
I don't really care about the error message, to be honest. The main issue is that the repl is actually rendering nix values in a way that they are not valid nix, i. e. a properly escaped nix string will evaluate to a nix string which is then rendered by the repl as invalid  nix syntax:

```
nix-repl> ''''${checkFlagsArray[@]}'' 
"${checkFlagsArray[@]}"
```

The error message was just added to demonstrate that pasting back the printed nix expression in the repl will result in an error.

**Comment by sternenseemann** [comment] 2022-01-04 18:18
Hasn't been fixed.

**Comment by sternenseemann** [comment] 2022-07-10 09:55
Still an issue in Nix 2.9.

**Comment by sternenseemann** [comment] 2022-08-25 10:23
Basically, `$` is never escaped, I guess because Nix reuses escaping rules for C++ which doesn't have string interpolation:

```
nix-repl> "\${foo}"
"${foo}"
```

**Comment by sternenseemann** [comment] 2022-08-25 10:36
Hm, this was fixed in #4012 for `nix-instantiate` at least:

```
$ nix-instantiate --eval -E '"\${foo}"'
"\${foo}"
```

I don't see why `nix repl` should behave differently here?

**Comment by houstdav000** [comment] 2023-01-09 16:19
Cool, I just ran into this today. I like to use REPLs though a lot, and might try to see about writing a PR to fix this. Might take a second though -- I'm a little out-of-practice with C++.

**Comment by roberth** [comment] 2023-04-09 20:59
Hi @cyntheticfox, I've encountered the cause of the issue while resolving some tech debt.
I didn't read your message before, so I just wanted to let you know that a contribution would have been appreciated (but don't feel bad about it!).

**Closed** 2023-04-17 09:19 UTC
Labels: bug
