### ISSUE TITLE
nix build regression 2.4 vs 2.3 - "failing to extract archive"

### ISSUE THREAD

**Issue by mpickering** [NixOS/nix#5741] opened 2021-12-07 10:11 UTC
Reproduce with

```
nix build -f https://gitlab.haskell.org/bgamari/ghcs-nix/-/archive/master/ghcs-nix-master.tar.gz ghc-9_0_1
```

this works with nix-2.3 but fails with nix-2.4 with the following error

```
error: failed to extract archive (Hard-link target 'ghc-9.0.1/driver/ghci/isMinTTY.c' does not exist.)
(use '--show-trace' to show detailed location information)
```

**Comment by regnat** [comment] 2021-12-07 12:46
That looks like it’s due to the switch to `libarchive`. I couldn’t reproduce it outside of Nix though (the offending file is `https://downloads.haskell.org/ghc/8.10.7/ghc-8.10.7-src.tar.xz`, and `bsdtar` − which uses libarchive too − unpacks it just fine), so hopefully it’s just a matter of passing the right flags internally. @yorickvP any idea what could go wrong here?

**Comment by regnat** [comment] 2021-12-07 12:50
That looks like it could be related to https://github.com/libarchive/libarchive/issues/1044 , but it has been fixed in the latest libarchive release (which we’re apparently using)

**Comment by domenkozar** [comment] 2021-12-10 09:23
@mpickering can you run `$(nix-store -qR $(which nix))`

**Comment by yorickvP** [comment] 2021-12-10 14:41
We probably need to do something similar to https://github.com/clearlinux/swupd-client/pull/384

**Comment by mpickering** [comment] 2021-12-10 17:58
I have rolled back to 2.23 so can't run that command sorry @domenkozar .

**Closed** 2021-12-13 12:37 UTC
Labels: bug
