### ISSUE TITLE
Docker nixos/nix image issues with fork/exec

### ISSUE THREAD

**Issue by attilaolah** [NixOS/nix#9618] opened 2023-12-15 22:32 UTC
**Describe the bug**

I'm running the following:

```sh
$ docker run -ti nixos/nix
```

Then inside the container, I run this:

```sh
$ nix-env --install bazelisk
$ bazelisk version
```

And I get this error:

```
2023/12/15 22:27:40 could not run Bazel: could not start Bazel: fork/exec /root/.cache/bazelisk/downloads/bazelbuild/bazel-7.0.0-linux-x86_64/bin/bazel: no such file or directory
```

I get similar fork/exec errors with some other downloaded binaries, e.g. cargo when installed via rules_rust, managed via Bazel. I'm not sure what is going on here or how to debug this further, any help is much appreciated.

**Steps To Reproduce**

See commands above. I'm running Docker on an Arch host.

**Expected behavior**

It should print the Bazel version, in the above case 7.0.0.

**`nix-env --version` output**

nix-env (Nix) 2.19.2

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by tomberek** [comment] 2023-12-16 01:10
In this, and likely the the other cases you mention, what is happening is that the tool is downloading pre-conpiled binaries that expect an FHS environment. The nixos/nix container does not by default place system libraries into their expected locations, or the dynamic linker, thus giving the error that you see. This is expected in the ecosystem. Consider the situation of bazelisk and then rules_rust downloading binaries that each depend on incompatible versions of the same libraries. It is exactly this situation that Nix was invented to solve, by ensuring that any shared dependencies are explicit in what they depend on. That dependency is captured in the store path that has a hash portion.

Running bazelisk in a "FROM scratch" container will do the same thing. Thus there is an unstated assumption of stuff that needs to be present on the machine. You are running into that unstated assumption by bazelisk. 

This situation is why the warning for bazelisk exists: https://github.com/NixOS/nixpkgs/blob/0f10e1681d87c273a5c4a6d1b51d0b419c363793/pkgs/development/tools/bazelisk/default.nix#L23

Bazel 7 was released upstream only a few days ago. Adding it to Nixpkgs is happening here: 
https://github.com/NixOS/nixpkgs/pull/262152

It is possible to build a nix-based container that can support this, one example: https://github.com/tazjin/nixery/issues/58#issuecomment-545490157

Closing as not a bug. But feel free to follow up or ask any questions as needed.

**Closed by tomberek** 2023-12-16 01:10 UTC
Labels: bug

**Comment by attilaolah** [comment] 2023-12-18 17:21
Thank you so much for explaining this. I understand how this is not a bug, and I don't think I slapped the `bug` label on this intentionally.

My reason for using bazelisk was really to be able to pin the version to 6 for now, because my workspace is not yet ready for 7.0, so installing Bazel itself is not an issue, as long as I can be explicit about which version I install.

As for rules_rust, there's ongoing work already to support it via `rules_nixpkgs`, that is, the `rules_nixpkgs_rust` toolchain, but it's not all ready yet.

I think once `rules_nixpkgs_rust` is ready, it will all work quite nicely in a vanilla container. The reason I'm going with the Nix container in the first place is to get reproducible builds, and Bazel is just one tool in achieving that. So aligning the Bazel tools to work better with the Nix ecosystem is a goal on its own anyway.

Again, thanks for your explanation above, and for the useful pointers.
