### ISSUE TITLE
Nix install script uses shasum, which is sometimes missing

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#978] opened 2016-07-18 14:02 UTC
I've had a couple of people in unrelated situations ask me about this, and I think it's a poor user experience for the first nix install to fail because of a lack of a dependency. Can we make the install script rely only on common dependencies? `shasum` is bundled with perl, which is missing at least from CentOS distributions. At worst, can we fall back to `openssl`, which should be available almost everywhere? Or have the installer script download more of its dependencies?

**Comment by edolstra** [comment] 2016-07-18 14:12
Dupe of https://github.com/NixOS/nixos-homepage/issues/86.

**Closed by edolstra** 2016-07-18 14:12 UTC

**Comment by copumpkin** [comment] 2016-07-18 14:13
Thanks, forgot the install script lived over there and didn't see anything about it in this tracker 😄
