### ISSUE TITLE
Nix commands fail without any message

### ISSUE THREAD

**Issue by GGG-KILLER** [NixOS/nix#9725] opened 2024-01-09 02:12 UTC
**Describe the bug**

Currently neither `nix-daemon` nor any other nix-based commands work in my machine if they are inside a systemd service.

They all fail with a SIGSEV which apparently happens in `getMaxCPU`.

**Steps To Reproduce**

I am not sure how to reproduce yet, however this is my current configuration: https://github.com/GGG-KILLER/nixos-configs (the machine that is experiencing this issues is located in `hosts/sora`).

**Expected behavior**

All commands and services work normally without any errors.

**`nix-env --version` output**

```console
$ nix-env --version         
nix-env (Nix) 2.18.1
```

This also happens on 2.19:
```console
$ nix-env --version
nix-env (Nix) 2.19.2
```

**Additional context**

```console
$ coredumpctl info 1523
           PID: 1523 (nix-build)
           UID: 1000 (ggg)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-01-08 22:22:48 -03 (43min ago)
  Command Line: nix-build --expr {} --no-out-link
    Executable: /nix/store/p1l4j192w1abk7mmkg60qmvc18svhky4-nix-2.18.1/bin/nix
 Control Group: /system.slice/home-manager-ggg.service
          Unit: home-manager-ggg.service
         Slice: system.slice
       Boot ID: 8f993118458b45e7a131b370551e7c40
    Machine ID: d234abf9bd5f42c8a488e0bf5005433f
      Hostname: sora
       Storage: /var/lib/systemd/coredump/core.nix-build.1000.8f993118458b45e7a131b370551e7c40.1523.1704763368000000.zst (present)
  Size on Disk: 453.0K
       Message: Process 1523 (nix-build) of user 1000 dumped core.
                
                Module libattr.so.1 without build-id.
                Module libkeyutils.so.1 without build-id.
                Module libkrb5support.so.0 without build-id.
                Module libcom_err.so.3 without build-id.
                Module libk5crypto.so.3 without build-id.
                Module libkrb5.so.3 without build-id.
                Module libunistring.so.5 without build-id.
                Module libxml2.so.2 without build-id.
                Module libbz2.so.1 without build-id.
                Module liblzma.so.5 without build-id.
                Module libacl.so.1 without build-id.
                Module libbrotlicommon.so.1 without build-id.
                Module libaws-c-common.so.1 without build-id.
                Module libaws-checksums.so.1.0.0 without build-id.
                Module libaws-c-sdkutils.so.1.0.0 without build-id.
                Module libaws-c-cal.so.1.0.0 without build-id.
                Module libaws-c-compression.so.1.0.0 without build-id.
                Module libs2n.so.1 without build-id.
                Module libaws-c-io.so.1.0.0 without build-id.
                Module libaws-c-http.so.1.0.0 without build-id.
                Module libaws-c-auth.so.1.0.0 without build-id.
                Module libaws-c-s3.so.0unstable without build-id.
                Module libaws-c-event-stream.so.1.0.0 without build-id.
                Module libaws-c-mqtt.so.1.0.0 without build-id.
                Module libzstd.so.1 without build-id.
                Module libgssapi_krb5.so.2 without build-id.
                Module libssh2.so.1 without build-id.
                Module libidn2.so.0 without build-id.
                Module libnghttp2.so.14 without build-id.
                Module libz.so.1 without build-id.
                Module libcpuid.so.16 without build-id.
                Module libarchive.so.13 without build-id.
                Module libbrotlidec.so.1 without build-id.
                Module libbrotlienc.so.1 without build-id.
                Module libseccomp.so.2 without build-id.
                Module libaws-crt-cpp.so without build-id.
                Module libaws-cpp-sdk-core.so without build-id.
                Module libaws-cpp-sdk-s3.so without build-id.
                Module libaws-cpp-sdk-transfer.so without build-id.
                Module libboost_context.so.1.81.0 without build-id.
                Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module liblowdown.so.1 without build-id.
                Module libeditline.so.1 without build-id.
                Stack trace of thread 1523:
                #0  0x00007f563ccf9734 _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_ (libnixutil.so + 0x48734)
                #1  0x00007f563cd5570e _ZN3nix9getMaxCPUEv (libnixutil.so + 0xa470e)
                #2  0x00007f563cefd47d _ZN3nix8Settings15getDefaultCoresEv (libnixstore.so + 0x15d47d)
                #3  0x00007f563cf007bd _ZN3nix8SettingsC2Ev (libnixstore.so + 0x1607bd)
                #4  0x00007f563ce520b1 _sub_I_65535_0.0 (libnixstore.so + 0xb20b1)
                #5  0x00007f563d4efebe call_init (ld-linux-x86-64.so.2 + 0x4ebe)
                #6  0x00007f563d4effac _dl_init (ld-linux-x86-64.so.2 + 0x4fac)
                #7  0x00007f563d505f50 _dl_start_user (ld-linux-x86-64.so.2 + 0x1af50)
                ELF object binary architecture: AMD x86-64
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by AbbottWu** [comment] 2024-01-11 14:44
Hi, I encountered the same issue after a system update a couple of days ago, and the coredump stack was consistent with the report above. I conducted some checks on this issue over the past few days and found that the main problem might occur in this part of `getMaxCPU()`:

```cc
auto cpuMaxParts = tokenizeString<std::vector<std::string>>(cpuMax, " \n");
auto quota = cpuMaxParts[0];
auto period = cpuMaxParts[1];
if (quota != "max")
        return std::ceil(std::stoi(quota) / std::stof(period));
```

When reading `cpuMaxParts`, no data verification was performed (despite the whole code block being wrapped by a try...catch block), which ultimately led to the program error. This issue can be avoided by adding a simple length check:

```cc
auto cpuMaxParts = tokenizeString<std::vector<std::string>>(cpuMax, " \n");

// add size check
if (cpuMaxParts.size() != 2)
        return 0;

auto quota = cpuMaxParts[0];
auto period = cpuMaxParts[1];
if (quota != "max")
        return std::ceil(std::stoi(quota) / std::stof(period));
```

To fix this issue on the existing package, I created a patch on 2.18.1 tag and made a provisional fix through an overlay:

```
diff --git a/src/libutil/util.cc b/src/libutil/util.cc
index 5a10c69e2..a8f89cf41 100644
--- a/src/libutil/util.cc
+++ b/src/libutil/util.cc
@@ -792,6 +792,8 @@ unsigned int getMaxCPU()
 
         auto cpuMax = readFile(cpuFile);
         auto cpuMaxParts = tokenizeString<std::vector<std::string>>(cpuMax, " \n");
+        if (cpuMaxParts.size() != 2)
+                return 0;
         auto quota = cpuMaxParts[0];
         auto period = cpuMaxParts[1];
         if (quota != "max")
```

Assuming you save the above content as `fix_nix.patch` and store it in the same directory as `configuration.nix`, you can configure `nixpkgs.overlays` in `configuration.nix` to introduce this patch, and it is best to explicitly specify that nix uses this package:

```nix
nixpkgs = {
  overlays = [
    (final: prev: {
      nix = prev.nix.overrideAttrs (previousAttrs: {
        patches = previousAttrs.patches ++ [ fix_nix.patch ];
        version = "2.18.1";
      });
    })
  ];
};
nix.package = pkgs.nix;
```

The above patch should fix the issue (at least it did for me).

Based on the code analysis, I think the bug might have been caused by changes to the cgroups CPU subsystem due to a system update. This inference comes from comparing the existence status of the `cpu.max` file before and after my system update. Before the update, the file did not exist, and the exception was directly caught by `try...catch`. However, after the update, the file exists, which triggers an uncaught exception when using `cpuMaxParts`. There might be more specific reasons. However, it is clear that there should indeed be a piece of code here to ensure that the parameters involved in the calculation "really" exist, rather than expecting `try...catch` to completely solve the problem.

**Comment by GGG-KILLER** [comment] 2024-01-11 23:41
It worked @AbbottWu, thank you very much for this solution!

Finally able to rebuild my system without having to use an install ISO after 2 weeks 😄

**Comment by yshui** [comment] 2024-01-12 20:57
I believe this is because zen kernel added a dummy `cpu.max` file when using alt cpu schedulers...

**Comment by GGG-KILLER** [comment] 2024-01-12 23:12
> I believe this is because zen kernel added a dummy `cpu.max` file when using alt cpu schedulers...

This would make sense, I'm currently using LQX kernel. And my custom install ISO uses stock kernel.

**Comment by thufschmitt** [comment] 2024-01-15 10:59
Discussed during the Nix maintenance team meeting on 2024-01-12. Assigned to @edolstra to see whether the workaround can be upstreamed

(nice digging in btw ;) )

**Closed** 2024-03-07 05:58 UTC
Labels: bug
