### ISSUE TITLE
Per-user profiles not created when $HOME mounted on NFS

### ISSUE THREAD

**Issue by rihardsk** [NixOS/nix#3356] opened 2020-02-13 13:59 UTC
I’m using Nix (multi-user) on Ubuntu and i’m getting errors when trying to install stuff with `nix-env -i ...`
```
$ nix-env -i nix-prefetch-git
installing 'nix-prefetch-git'
error: opening lock file '/nix/var/nix/profiles/per-user/.../profile.lock': No such file or directory
```

There are multiple systems on which this error occurs. On all of them the user home directory is mounted on an NFS drive (and users are managed with SSSD and Active Directory). The issue manifests only when running `nix-env` with a user whose home is on the NFS drive. Everything is fine when doing the above with a local user whose home is on the local drive.

I have tracked down that the issue is present in Nix 2.3.2 and not Nix 2.3. The cause of the error is that for users on NFS `/nix/var/nix/profiles/per-user/$USER` doesn't get created (don't know about `/nix/var/nix/gcroots/per-user/$USER` as, it's, apparently, not used when doing `nix-env -i ...`). If using Nix 2.3 (with local users or users on NFS) or Nix 2.3.2 with local users, the per-user directory gets created and everything works fine. The issue disappears if i manually create the per-user directory and assign it the correct ownership.

Here's some info from Nix:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-76-generic, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixpkgs-20.03pre212770.cc1ae9f21b9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Initially, i posted this issue on nixos discourse, there's some more info on how i attempted to debug it https://discourse.nixos.org/t/per-user-profiles-not-created-when-home-mounted-on-nfs/5864

**Comment by pacien** [comment] 2020-04-12 17:52
I'm having the same issue on NixOS 19.09 with nix 2.3.3 in a NixOS container.
My $HOME dir isn't a mount point though.

**Comment by rihardsk** [comment] 2020-04-28 13:47
Yeah, still having the same issue with Nix `2.3.4`

**Comment by pacien** [comment] 2020-06-28 15:10
Still present on Nix 2.3.6.

❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.48, NixOS, 20.03.2351.f8248ab6d9e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"home-manager-20.03, nixos-20.03.2351.f8248ab6d9e, nixos-19.09-19.09.2520.289466dd6a1, nixos-unstable-20.09pre231796.22a81aa5fc1"`
 - channels(kea): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by duog** [comment] 2020-07-29 09:25
I've also encountered this problem using nixos-containers with nix 2.3.6

It seems the regression was introduced in:
65953789b * Remove world-writability from per-user directories
though note that this seems to be part of a series of commits that should be considered together.

It used to be that /nix/var/nix/profiles/per-user was world writable(mode 1777). nix-env and nix-channel would create ../per-user/$USER which would be owned by the user and protected from deletion by the sticky bit(leading 1) in the per-user mode.  

The commit referenced above moves the responsibility of creating the per-user/$USER dir to LocalStore::createUser. This works normally, but not in the nixos-containers case. Here there is a bind mount /nix/var/nix/profiles/per-container/$container/per-user -> /nix/var/nix/profiles/per-user. nix-env inside the container doesn't use a LocalStore, it uses a UDSRemoteStore, which does not call the createUser codepath. The daemon on the host, which has the LocalStore, doesn't know about the bind mount, so can't hope to create the user directories.

This can be worked around by creating the per-user/$user directories manually.

**Comment by Kloenk** [comment] 2020-07-29 12:09
On my computer I have my home on an nfs mount, but everything works just fine. Maybe this got fixed in nix 2.4-pre (which I'm using)?

If I remember the code in nix right, when connecting to the daemon the daemon creates the state dirs, and chowns it to the user which is connected (identified via the unix socket).

**Comment by rihardsk** [comment] 2020-10-02 12:21
@Kloenk i just tried nix 3.0-pre and got the same profile.lock error as initially. The newest nix-daemon still wouldn't create the per-user direcotries on it's own.

Just to make sure that i didn't miss any steps when setting up the nix 3.0-pre from source, here's what i did - fetched source from github, built with nix-build, stopped my existing nix-daemon service and socket, did `systemctl daemon-reload`, replaced the `/etc/systemd/system/nix-daemon.service` unit file with one that points to the newly built nix-daemon.

I found something interesting though. The `/nix/var/nix/profiles/per-user/` directory contains a `1515612688` subdirectory with ownership assigned to my user. As it turn's out, that's my linux uid. To me it seems that the nix-daemon actually does create the per-user profile directory for my user but it's just naming it weirdly - it's naming it for my uid - while some other part of nix expects it to be named for my user name instead. That is, i have `/nix/var/nix/profiles/per-user/1515612688` assigned to my user and also a dead symlink under $HOME `.nix-profile -> /nix/var/nix/profiles/per-user/<my-user>@<my-work-org-domain>/profile`.

Maybe my SSSD and Active Directory setup is somehow tripping up Nix's ability to correctly determine the per-user profile directory's name (and maybe $HOME being on NFS is beside the point)?

**Comment by Kloenk** [comment] 2020-10-02 13:40
What's your output of ‘id‘?

**Comment by rihardsk** [comment] 2020-10-05 07:52
```sh
$ id
uid=1515612688 gid=1515600513 groups=1515600513,1515601112,1515601176,1515606567,1515608809,1515608919,1515608920,1515609837,1515610130,1515610150,1515611624,1515612675,1515612732,1515612742,1515612853,1515612855,1515612897,1515613135,1515613155,1515613251,1515613255
```

**Comment by Kloenk** [comment] 2020-10-05 08:36
seems like `getpwuid` failes because of your SSSD/Active Directory setup? So it can't get a username for you and then can't create a profile folder for you?

**Comment by rihardsk** [comment] 2020-10-05 11:44
Yeah, did some more testing and it seems you're right. It turned out that `getpwuid` doesn't work when built with `gcc` provided by nixpkgs **and** when SSSD/Active Directory is used.

I built this simple bit of C++ code with my distro's gcc and with nixpkgs gcc and ran it on a system with SSSD/Active Directory and on one without it.
```c++
#include <pwd.h>
#include <stdio.h>
#include <string>

int
main(int argc, char *argv[])
{
    struct passwd pwd;

   if (argc != 2) {
        fprintf(stderr, "Usage: %s uid\n", argv[0]);
        exit(EXIT_FAILURE);
    }

   pwd = *getpwuid(std::stoi(argv[1]));

   printf("Use: %s; UID: %ld\n", pwd.pw_name, (long) pwd.pw_uid);
    exit(EXIT_SUCCESS);
}
```
The only combination that returned a segfault was with nixpkgs' gcc on a system with SSSD/Active Directory.

A note on the `id` outputs i posted previously: outputs were stripped of user readable names because it was executed from within a nix shell. The actual output looks like this
```sh
$ id
uid=1515612688(<name>.<surname>@<workplace-domain>) gid=1515600513(domain users@<workplace-domain>) groups=1515600513(domain users@<workplace-domain>) .....
```
I checked that, when inside a nix shell, `id` is provided by nix so it's acting consistently with the above observations.

I guess this isn't a problem in itself but rather the fact that some other part of nix *is* able to get my username and it disagrees with `nix-daemon` on what the per-user profile directories should be named like.

**Comment by wucke13** [comment] 2021-06-10 08:42
This issue is still present.

**Comment by iFreilicht** [comment] 2021-07-01 10:25
Can confirm, just encountered this on a fresh install. Nix version: `nix-env (Nix) 2.3.13`.

I actually found the profile does get created at some point, but not with my user-name, but my user-id:

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-77-generic, Ubuntu, 18.04.5 LTS (Bionic Beaver)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.13`
 - channels(root): `"nixpkgs-21.11pre299378.db6e089456c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
$ nix-env -i vscode
installing 'vscode-1.57.1'
error: opening lock file '/nix/var/nix/profiles/per-user/felix/profile.lock': No such file or directory
$ ll /nix/var/nix/profiles/per-user
total 16
drwxr-xr-x 4 root    root 4096 Jul  1 11:50 ./
drwxr-xr-x 3 root    root 4096 Jul  1 11:46 ../
drwxr-xr-x 2 felix   root 4096 Jul  1 11:50 2098324/
drwxr-xr-x 2 root    root 4096 Jul  1 11:46 root/
$ ll /nix/var/nix/profiles/per-user/2098324/
total 8
drwxr-xr-x 2 felix   root 4096 Jul  1 11:50 ./
drwxr-xr-x 4 root    root 4096 Jul  1 11:50 ../
$ id
uid=2098324(felix) # group IDs stripped
```

The simple workaround was:

```
$ sudo mkdir /nix/var/nix/profiles/per-user/$USER
$ sudo chown $USER /nix/var/nix/profiles/per-user/$USER
```

**Comment by rihardsk** [comment] 2021-08-18 12:00
I just ran into https://github.com/NixOS/nix/issues/3873 which might have a similar cause as this issue.

**Comment by bjornfor** [comment] 2021-09-11 14:24
If you're hit by this (i.e. you're on non-Nixos, having non-local users from LDAP or SSSD), it can be worked around like this.

Run `sudo systemctl edit nix-daemon` and paste:

```
[Service]
Environment=LD_LIBRARY_PATH=<nss_ldap>/lib:<sssd>/lib
```

(Where \<nss_ldap\> and \<sssd\> are the store paths from `nix-build -A nss_ldap -A sssd`, preferably built from the same nixpkgs as nix.)

Then restart the nix-daemon service.

**Comment by nickgarber** [comment] 2022-02-28 19:00
With a Multi-User Install on Debian, this is occuring on GCE using `os-login`, getting error 
```
error: opening directory '/nix/var/nix/profiles/per-user/<x-redacted-x>': No such file or directory
```

Interestingly it looks like a profile is being created by using the UID, rather than the username.
```
$> sudo ls -ld /nix/var/nix/profiles/per-user/

815947506/ root/      

$> sudo ls -ld /nix/var/nix/profiles/per-user/*

drwxr-xr-x 2 <x-username-x> root 4096 Feb 28 06:32 /nix/var/nix/profiles/per-user/815947506

$> id

uid=815947506(<x-username-x>) gid=815947506(<x-username-x>) groups=815947506(<x-username-x>)
```

**Comment by Ericson2314** [comment] 2023-03-12 14:21
Nix 2.14 (released but currently quasi-revoked until somethings are fixed), moves the profiles inside home directories, side-stepping this issue.

Assigned to @thufschmitt to either close right away or close once the 2.14 (or newer) is once again the default installer.

**Comment by thufschmitt** [comment] 2023-06-06 09:24
Closing since (as far as I understood), Nix 2.14+ don't have this problem any more. Feel free to complain if that's not the case

**Closed** 2023-06-06 09:40 UTC
Labels: bug

**Comment by samuela** [comment] 2023-07-19 19:04
I'm seeing this issue not with NFS mounts, but with /home being mounted from a separate (virtual) disk on GCP. Is there a workaround?

**Comment by NobbZ** [comment] 2023-07-19 19:04
Which version of nix?

**Comment by samuela** [comment] 2023-07-19 19:09
Ah apologies, I forgot to mention: 2.16.1

**Comment by samuela** [comment] 2023-07-19 19:09
```
sudo mkdir /nix/var/nix/profiles/per-user/$USER
sudo chown $USER /nix/var/nix/profiles/per-user/$USER
```
seems to work for me
