### ISSUE TITLE
Stream error in the HTTP/2 framing layer

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#1254] opened 2017-02-27 13:27 UTC
Observed a few times from BinaryCacheStore:
```
unable to download ‘https://cache.nixos.org/nar/1vwg4rs3rqzy2pia1ll8cnz066m8pjhz3q8qnqj5mrz6ayxd5m9n.nar.xz’: Stream error in the HTTP/2 framing layer (92)
unable to download ‘https://cache.nixos.org/nar/023m6mfkb4akkb7zpmcg8z2r4ly5yvz9gfp7g8an5rwn4y96284q.nar.xz’: Stream error in the HTTP/2 framing layer (92)
```
This seems to be pretty random. It may be a bug in curl or in nghttp2, or a CloudFront issue.

**Comment by iblech** [comment] 2017-10-30 15:03
Have others experienced this problem? Can we consider it fixed in view of the referenced commit?

**Comment by schoettkr** [comment] 2018-10-20 08:14
> Have others experienced this problem? Can we consider it fixed in view of the referenced commit?

I also experienced this/similar issue eg:
`unable to download 'https://cache.nixos.org/nar/1n9cyv2q974r14yr6823zwkvfs4k80vlfpp3xh2jlgcqw2z2g5dn.nar.xz': HTTP error 200 (curl error: Stream error in the HTTP/2 framing layer);`

To me it seems to be `curl` related

**Comment by brodavi** [comment] 2018-11-01 08:15
I am seeing this same error in conjunction with "error 9 while decompressing xz file" ... using a very slow internet connection. NixOS 18.09

**Comment by alexherbo2** [comment] 2019-02-07 19:18
Same.

**Comment by iblech** [comment] 2019-02-10 10:51
Meanwhile the error also surfaced here, but on a very fast connection (100 Mbit/s).

**Comment by u23a** [comment] 2019-02-16 11:32
`warning: unable to download 'https://cache.nixos.org/nar/12mabyfb0m7jl32kxadkcjamlhmnbwp46fnlxxhh7m6sam1s724d.nar.xz': HTTP error 200 (curl error: Stream error in the HTTP/2 framing layer); retrying in 312 ms
error 9 while decompressing xz file`

When executing nixos-rebuild switch,always with the error.

**Comment by vcunat** [comment] 2019-02-16 12:56
The "HTTP 200" errors were more lengthily discussed [on the forum](https://discourse.nixos.org/t/the-nixos-cache-is-now-hosted-by-fastly/1061); maybe they are unrelated to these errors from CloudFront cache.

**Comment by alex-giusi-tiri** [comment] 2019-05-12 04:25
I noticed that this happens if I run the CPU of my RaspberryPi 3B very slowly (<100MHz).

**Comment by ebzzry** [comment] 2019-05-12 04:37
Does this have anything to do with CloudFront?

**Comment by vcunat** [comment] 2019-05-12 07:20
cache.nixos.org isn't using CloudFront anymore &ndash; it's Fastly now: https://discourse.nixos.org/t/the-nixos-cache-is-now-hosted-by-fastly/1061

**Comment by ebzzry** [comment] 2019-05-12 10:35
@vcunat OK. Does that mean that the diagnostic script linked at [http://cache.nixos.org/](http://cache.nixos.org/) is no longer applicable?

**Comment by edolstra** [comment] 2019-08-27 19:02
Closing, probably not a Nix bug.

**Comment by domenkozar** [comment] 2022-12-13 11:35
We could retry on these errors, otherwise it's quite annoying that Nix just fails.

**Comment by domenkozar** [comment] 2022-12-13 11:37
Relevant: https://github.com/edolstra/nix/commit/1ab8d6ac1861e9405ae34af3deb681020c03e82d

What happens here is that we get code 200, but the stream stops at some point.

**Comment by KaiserKarel** [comment] 2022-12-13 15:23
> Relevant: [edolstra@1ab8d6a](https://github.com/edolstra/nix/commit/1ab8d6ac1861e9405ae34af3deb681020c03e82d)
> 
> What happens here is that we get code 200, but the stream stops at some point.

Here is a link to logs where this error occurs: https://github.com/ComposableFi/composable/actions/runs/3686602278/jobs/6239292877

**Comment by KaiserKarel** [comment] 2022-12-13 15:24
A simple retry/exponential backoff would probably resolve our issues.

**Comment by dzmitry-lahoda** [comment] 2022-12-13 15:52
List of errors codes which `nix flake build/run` can produce could be awesome too. So if retry would not be done inside `nix`, can at least do some basics outside in shell.

**Comment by SuperSandro2000** [comment] 2022-12-13 15:58
Is this related to the client or server?

**Comment by domenkozar** [comment] 2022-12-13 17:00
These errors are part of the networking stack unhappy path so they should be handled gracefully on the Nix client.

**Comment by KaiserKarel** [comment] 2022-12-13 17:51
> Is this related to the client or server?

client side

**Comment by SuperSandro2000** [comment] 2022-12-16 23:16
Turning of http2 makes downloads more stable and no longer constantly fail after about 100MB from a hydra that uses nginx with http2 enabled.

https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-http2

**Comment by RossComputerGuy** [comment] 2023-02-05 20:39
![image](https://user-images.githubusercontent.com/19699320/216844605-67997a56-5f80-4f84-ae6a-cf341b4d1ff5.png)
Had this same problem but even with `http2` being disabled, it still fails.

**Comment by binarydigitz01** [comment] 2023-03-26 08:20
Another log:
```
error: unable to download 'https://nix-community.cachix.org/nar/859f1bbb5fe98775ee6a6b0f120409b7fa516504ae830c04e083a116f7bdb895.nar.zst': HTTP error 200 (curl error: Stream error in the HTTP/2 framing layer)
error: some substitutes for the outputs of derivation '/nix/store/wcw77rdy23z9jx0zsadxblrw1gxbha0n-emacs-pgtk-20230324.0.drv' failed (usually happens due to networking issues); try '--fallback' to build derivation from source
error: 1 dependencies of derivation '/nix/store/1xk9rgjv2fd806q14k8594355qh3x1kz-emacs-pgtk-with-packages-20230324.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/idqxv0bafs4rdkfqd3ncl4wqprv0gixl-emacs.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wgxn3fqabrpysw41zx4scjc43m6c71ky-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ysm1q3l6n7672vlsg604ivbd9k69klkp-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lnn3k3i3vanpj76vnvsak1lnw8i3dcfc-unit-home-manager-binarydigitz01.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cwwwhnhb3wic9b85r0hakfy8pn2i6f7h-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/72zs7mviv3nifkz5d1g0vnj8l0qa04rv-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mdncpm5mgl75pwjixcifcjg8r9d7b144-nixos-system-nixos-23.05.20230325.8f40f2f.drv' failed to build
```

**Comment by domenkozar** [comment] 2023-04-02 10:49
Reading [upstream issues on curl](https://github.com/curl/curl/issues/8809#issuecomment-1429261645) this *might* have been fixed in the latest curl versions, so if it happens to you please upgrade to nix on nixpkgs-unstable and report back with the curl version in the closure of Nix you're using.

**Comment by rodrigol-chan** [comment] 2023-05-08 10:06
Just had this happen to me when downloading from Cachix.

```console
$ nix build --file everything.nix --out-link .gcroots/result
error: unable to download 'https://REDACTED.cachix.org/nar/REDACTED.nar.zst': HTTP error 200 (curl error: Stream error in the HTTP/2 framing layer)
error: some substitutes for the outputs of derivation '/nix/store/REDACTED' failed (usually happens due to networking issues); try '--fallback' to build derivation from source
error: 1 dependencies of derivation '/nix/store/REDACTED' failed to build
error: 1 dependencies of derivation '/nix/store/REDACTED' failed to build
error: 1 dependencies of derivation '/nix/store/REDACTED' failed to build

$ nix --version
nix (Nix) 2.13.3

$ nix path-info --recursive $(which nix) | grep curl
/nix/store/yklzq364x0m0jw9bqaqvbdm11z8x6ndz-curl-8.0.1
```

**Comment by domenkozar** [comment] 2023-05-08 10:14
To workaround this issue, you can disable http2 (although that is likely to impact performance) by putting `http2 = false` in your `nix.conf`.

**Comment by dzmitry-lahoda** [comment] 2023-05-08 10:14
@rodrigol-chan  cachix is not nix cache server. ping them for issue.

**Comment by vcunat** [comment] 2023-05-08 10:16
Domen is from cachix.

**Comment by domenkozar** [comment] 2023-05-08 11:00
To be able to debug and fix this issue, we need a way to reproduce it. Ideally using `-vvv` passed to Nix so that curl debugging information is printed.

**Comment by domenkozar** [comment] 2023-05-16 10:05
curl `8.1.0` is coming out tomorrow with more fixes around HTTP2, if someone can compile Nix with it and give it a try, that would be lovely. Also don't forget to add `-vvv` so that we get the full log in case we hit the error again.

**Comment by jakubgs** [comment] 2023-06-22 08:25
Any plans to upgrade Curl anytime soon? Our devs encounter this error on bigger NARs often enough to be a noticeable problem.

**Comment by vcunat** [comment] 2023-06-22 08:33
`nixos-unstable` and `nixos-23.05` have curl 8.1.1 for quite some time already.

**Comment by vcunat** [comment] 2023-06-22 09:02
I guess it should better migrate away from 22.11, as that only gets about one week of support now.  (IMHO flakes tend to result into too much pinning, but that's tangential here.)

**Comment by jakubgs** [comment] 2023-06-22 09:06
I checked out `2.16.1` tag and tried updating the channel to `23.05` but Nix build fails with:
```
 > nix build .\#packages.x86_64-linux.nix
warning: Git tree '/home/jakubgs/soft/nix' is dirty
warning: Git tree '/home/jakubgs/soft/nix' is dirty
error: builder for '/nix/store/79d7g2j9i3k5gjcbd862q449mczj6chv-nix-2.16.1.drv' failed with exit code 1;
       last 10 log lines:
       > configure: error: Package requirements (lowdown >= 0.9.0) were not met:
       >
       > No package 'lowdown' found
       >
       > Consider adjusting the PKG_CONFIG_PATH environment variable if you
       > installed software in a non-standard prefix.
       >
       > Alternatively, you may set the environment variables LOWDOWN_CFLAGS
       > and LOWDOWN_LIBS to avoid the need to call pkg-config.
       > See the pkg-config man page for more details.
       For full logs, run 'nix log /nix/store/79d7g2j9i3k5gjcbd862q449mczj6chv-nix-2.16.1.drv'.
```
In my opinion the benefit of flakes is the easy and clear locking of channels. As far as I'm concerned I'd rather have everything locked down and many years old, and working, than upgrading regularly and having to fix upgrade issues regularly.

To each their own. But yeah, not the place for this.

**Comment by domenkozar** [comment] 2023-07-18 17:27
For anyone hitting this, you can give the latest Nix a try with curl 8.1.1:

```
  - uses: cachix/install-nix-action@v22
    with:
      install_url: https://nixos-nix-install-tests.cachix.org/serve/r1x1gcvnw0hc9cv5[3](https://github.com/NixOS/nix/actions/runs/5586878694/jobs/10220019680#step:4:3)1z86pa5lfn8s9jn/install
      install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
```

**Comment by domenkozar** [comment] 2023-07-22 09:52
Starting to see these here https://github.com/cachix/nixpkgs-python/actions/runs/5628950619/job/15253397406#step:7:268

Going to apply the above fix and report back in some time if it still happens.

**Comment by domenkozar** [comment] 2023-09-14 12:39
We haven't observed any further errors with the above installer.

**Comment by domenkozar** [comment] 2024-05-15 10:48
Closing as it's fixed in recent versions of curl.

**Closed by domenkozar** 2024-05-15 10:48 UTC
Labels: bug

**Comment by elikoga** [comment] 2025-01-24 03:34
Am I encountering the same error? https://github.com/Thymis-io/thymis/actions/runs/12942633454/job/36100689433#step:4:1884

**Comment by MagicRB** [comment] 2026-08-01 12:25
I'm running into this again, on `nix (Nix) 2.34.8`. Setting `http2 = false` does indeed make it go away.

EDIT: no it showed up again....

Caddy logs:
```
Aug 01 12:25:59 ingress caddy[452]: 2026/08/01 12:25:59.030        WARN        http.handlers.reverse_proxy        aborting with incomplete response        {"upstream": "172.20.69.25:80", "duration": 0.005352881, "request": {"remote_ip": "10.64.0.29", "remote_port": "34026", "client_ip": "10.64.0.29", "proto": "HTTP/1.1", "method": "GET", "host": "buildbot.in.redalder.org", "uri": "/nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar", "headers": {"Via": ["1.1 Caddy"], "Accept-Encoding": ["deflate, gzip, br, zstd"], "User-Agent": ["curl/8.21.0 Nix/2.34.8"], "Accept": ["*/*"], "X-Forwarded-For": ["10.64.0.29"], "X-Forwarded-Proto": ["https"], "X-Forwarded-Host": ["buildbot.in.redalder.org"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "http/1.1", "server_name": "buildbot.in.redalder.org", "ech": false}}, "error": "reading: unexpected EOF"}
```

Nginx after caddy:
```
/nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar HTTP/1.1" 200 - "" "curl/8.21.0 Nix/2.34.8"
Aug 01 12:25:50 blowhole container buildbot-in-redalder-org[2255301]: 2026/08/01 14:25:50 [warn] 243#243: *50453 an upstream response is buffered to a temporary file /tmp/nginx_proxy/9/05/0000001059 while reading upstream, client: 172.20.69.7, server: https://buildbot.in.redalder.org/, request: "GET /nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar HTTP/1.1", upstream: "http://127.0.0.1:8077/nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar", host: "buildbot.in.redalder.org"
Aug 01 12:25:56 blowhole container buildbot-in-redalder-org[2255301]: 2026/08/01 14:25:56 [crit] 243#243: *50453 pwritev() "/tmp/nginx_proxy/9/05/0000001059" has written only 2229 of 8192 while reading upstream, client: 172.20.69.7, server: https://buildbot.in.redalder.org/, request: "GET /nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar HTTP/1.1", upstream: "http://127.0.0.1:8077/nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar", host: "buildbot.in.redalder.org"
Aug 01 12:25:56 blowhole container buildbot-in-redalder-org[2255301]: 172.20.69.7 - - [01/Aug/2026:14:25:56 +0200] "GET /nar/f7705d50pzy7ys5c2jvfmiwdpvxfjc5s-1ax9mjqrvz4aqx3bk0340cp8j2kibmlkjsqq2mpyrdr45zr9gdvr.nar HTTP/1.1" 200 17037909 "-" "curl/8.21.0 Nix/2.34.8"
```
