### ISSUE TITLE
Better error message for error: unable to fork: Cannot allocate memory

### ISSUE THREAD

**Issue by kevinburke** [NixOS/nix#309] opened 2014-07-26 18:50 UTC
I ran `nix-env` on a machine with 512MB of RAM (and little memory usage) and got the error message above. It's not clear reading that that `nix-env` is using lots of memory. An appropriate error message (consider creating a swapfile or allocating more memory) would be nice.

**Comment by mmahut** [comment] 2018-01-16 10:40
Duplicate of #421 and should probably be closed.

**Closed** 2018-02-01 09:43 UTC
