### ISSUE TITLE
unable to use github pr refs when using git+http

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nix#10481] opened 2024-04-12 01:56 UTC
**Describe the bug**

the special pull/N/{head,merge} refrences that github creates for each pull request can only be used with `github:` flakes, not `git+http://github.com` flakes.

**Steps To Reproduce**

1. `nix build 'git+https://github.com/NixOS/nixpkgs?ref=pull/303399/merge#cargo-shear'`
```
fatal: couldn't find remote ref refs/heads/pull/303399/merge
error:
       … while fetching the input 'git+https://github.com/NixOS/nixpkgs?ref=pull/303399/merge'

       error: program 'git' failed with exit code 128
```

**Expected behavior**
the command should succeed.

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Additional context**

this could cause problems for programs that want to act generically on git repositories, having to special case github to not use `git+http` adds unnecessary complexity.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment] 2024-04-23 13:26
You need to use `refs/pull/:ID/merge`. `git` does some magic to abstract over branches, tags and arbitrary other references that Nix doesn't replicate.

Closing as a dupe of https://github.com/NixOS/nix/issues/3701

**Closed by thufschmitt** 2024-04-23 13:26 UTC
Labels: bug
