### ISSUE TITLE
linenoise error when piping expressions into nix repl

### ISSUE THREAD

**Issue by gilligan** [NixOS/nix#2492] opened 2018-10-27 14:06 UTC
linenoise complains when you pipe expressions into the repl:
```
$ echo '1 + 1' | nix repl                                           
Welcome to Nix version 2.1.1. Type :? for help.
2
error: Unexpected linenoise keytype: 0
```
The `0` is probably going to be the EOF. This *hopefully* just disappear whenever https://github.com/NixOS/nix/pull/2228 gets merged.

**Comment by dtzWill** [comment] 2018-10-29 11:39
This is fixed by commit referenced here:

https://github.com/NixOS/nix/issues/1925

Which I've been using for some time now, so is pretty safe :).  Haven't checked how the editline version handle this.

**Comment by edolstra** [comment] 2018-10-29 11:45
Closing as dupe of #1925.

**Closed by edolstra** 2018-10-29 11:45 UTC
