### ISSUE TITLE
i have problem install NixOS

### ISSUE THREAD

**Issue by yuda-pradana** [NixOS/nix#8989] opened 2023-09-17 18:33 UTC
## Platform

- [ ] Linux: 
- [ ] macOS
- [x] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by yuda-pradana** [comment] 2023-09-17 18:50
installing 'nix-2.17.0'
error:
       … while setting up the build environment

       error: unable to load seccomp BPF program: Invalid argument

**Comment by dimaqq** [comment] 2023-09-19 06:54
This seems relevant: https://github.com/jetpack-io/devbox/issues/1444

**Comment by fricklerhandwerk** [comment] 2023-09-28 22:27
Hey @yuda-pradana, sorry that apparently something doesn't work out for you, and thanks for reaching out. I'll close this issue for now since it's not actionable  without any details on what exactly happened.

Feel free to reopen the issue when you provide more information for reproducing the problem. Please check the Nix [contribution guide](https://github.com/NixOS/nix/blob/master/CONTRIBUTING.md) and a the [somewhat more extensive one one nix.dev](https://nix.dev/contributing/how-to-contribute) for tips on making issues maintainers (or anyone) will be more likely to address.

**Closed by fricklerhandwerk** 2023-09-28 22:27 UTC
Labels: installer
