### ISSUE TITLE
fetcher cache sqlite error: table Cache has no column named domain

### ISSUE THREAD

**Issue by DavHau** [NixOS/nix#10985] opened 2024-06-28 11:02 UTC
I ran into this issue since upgrading from 2.20 to 2.23.1.

Error:
```
> sudo nixos-rebuild --flake . switch
[sudo] password for grmpf: 
warning: Git tree '/home/grmpf/synced/projects/hyperconfig' is dirty
error:
       … while fetching the input 'git+file:///home/grmpf/synced/projects/hyperconfig'

       error: creating statement 'insert or replace into Cache(domain, key, value, timestamp) values (?, ?, ?, ?)': SQL logic error, table Cache has no column named domain (in '/root/.cache/nix/fetcher-cache-v2.sqlite')
```

deleting `{root,$HOME}/.cache/nix` fixes the issue

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment] 2024-07-03 19:08
Try deleting `/root/.cache/nix/fetcher-cache-v2.sqlite`.

**Comment by roberth** [comment] 2024-09-13 11:04
Unfortunately something went wrong with the notes (previous comment), but iirc, we were unable to reproduce this, and we suspect that it may be related to running a development version; either an intermediate unreleased revision, or perhaps a branch like #6530.

As the issue is not actionable, I'll close it for now.

**Comment by Montmorency** [comment] 2024-11-03 16:37
I just ran in to this when bumping nix-darwin nixpkgs version in a flake:

```
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-24.05-darwin";
    #nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-23.11-darwin";
```

```
error: creating statement 'insert or replace into Cache(domain, key, value, timestamp) values (?, ?, ?, ?)': SQL logic error, table Cache has no column named domain (in '/Users/lambert/.cache/nix/fetcher-cache-v2.sqlite')
```

removing: `/Users/myusername/.cache/nix/fetcher-cache-v2.sqlite` then meant the rebuild ` nix run nix-darwin -- switch --flake .#Enrico
[0.0 MiB DL]` just hanged. 

Most nix functionality was broken at this stage (i.e. launching dev shells rebuilding nix-darwin etc.) Ended up doing a full reinstall of nix.

**Comment by Zaczero** [comment] 2024-11-19 04:46
I have just upgraded from 24.05 to Beta 24.11 and starting facing this issue.

```txt
nix-shell 
error:
       … while calling the 'import' builtin
         at /home/user/Source/openstreetmap-ng/shell.nix:5:10:
            4|   # Update packages with `nixpkgs-update` command
            5|   pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/85f7e662eda4fa3a995556527c87b2524b691933.tar.gz") { };
             |          ^
            6|

       … while realising the context of a path

       … while calling the 'fetchTarball' builtin
         at /home/user/Source/openstreetmap-ng/shell.nix:5:18:
            4|   # Update packages with `nixpkgs-update` command
            5|   pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/85f7e662eda4fa3a995556527c87b2524b691933.tar.gz") { };
             |                  ^
            6|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: creating statement 'insert or replace into Cache(domain, key, value, timestamp) values (?, ?, ?, ?)': SQL logic error, table Cache has no column named domain (in '/home/user/.cache/nix/fetcher-cache-v2.sqlite')
```

> deleting {root,$HOME}/.cache/nix fixes the issue

This helped and nix-shell started working again.

**Comment by edolstra** [comment] 2024-11-20 13:26
@Montmorency @Zaczero Did you ever run the Nix lazy-trees branch (specifically a version from between August - October 2023)? That might explain having a `fetcher-cache-v2.sqlite` without a `domain` attribute.

**Comment by Zaczero** [comment] 2024-11-21 13:33
@edolstra I have only been running official and beta releases of NixOS. I am not a nix hackerman (yet) :smiley:.

**Closed** 2024-11-21 15:34 UTC
Labels: bug, regression, fetching

**Comment by Zaczero** [comment] 2024-11-21 15:51
I do confirm that I did use devenv at some point (for about a day :open_mouth:).
