### ISSUE TITLE
error: committing transaction: disk I/O error

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nix#804] opened 2016-02-17 15:49 UTC
```
 error: committing transaction: disk I/O error
269 store paths deleted, 136.03 MiB freed
```

I get this error running `nix-store --gc`. Run it again a few times and it eventually works.

**Comment by edolstra** [comment] 2019-11-28 15:07
Closing, can't reproduce.

**Closed by edolstra** 2019-11-28 15:07 UTC
Labels: backlog
