### ISSUE TITLE
A way to get project root inside of `nix develop` shell

### ISSUE THREAD

**Issue by srid** [NixOS/nix#8145] opened 2023-04-01 17:25 UTC
**Is your feature request related to a problem? Please describe.**
I'd like a way to know the root of the project from inside the `nix develop` shell.

**Describe the solution you'd like**
Running `nix develop` should automatically set a `FLAKE_ROOT` env var that points to the absolute path to the directory containing the `flake.nix`. If `nix develop` is run on a remote flake URL (eg: `nix develop github:user/repo`) this environment can be unset.

**Describe alternatives you've considered**
Set this env var manually in the `shellHook`, à la: https://github.com/srid/flake-root

**Additional context**
https://github.com/cachix/pre-commit-hooks.nix/pull/268#pullrequestreview-1367874391

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment] 2023-04-09 22:06
Duplicate of #8034

**Closed** 2023-04-10 00:19 UTC
Labels: feature
