### ISSUE TITLE
`nix build` throws error `Assertion 'get() != pointer()' failed` on git dependency

### ISSUE THREAD

**Issue by MrFoxPro** [NixOS/nix#10123] opened 2024-03-01 14:41 UTC
**Describe the bug**
After updating from 2.19.1 to 2.20.3, when building derivation for Rust project with `crane`, Nix fails with error:
```
nix build .#sv -vv
<...>
evaluating file '/nix/store/c3afw4qy9a1wcd4pkw9zvpk5lvx4mxll-source/lib/urlForCargoPackage.nix'
evaluating file '/nix/store/c3afw4qy9a1wcd4pkw9zvpk5lvx4mxll-source/lib/registryFromDownloadUrl.nix'
evaluating file '/nix/store/c3afw4qy9a1wcd4pkw9zvpk5lvx4mxll-source/lib/downloadCargoPackageFromGit.nix'
using revision d8b1552edb88f6e835b0f78ff7bd16de8a903211 of repo 'https://github.com/MrFoxPro/tokio-beanstalkd.git'
evaluating derivation 'git+file:///home/foxpro/craft/sferadel/dev#sv'/usr/include/c++/13.2.1/bits/unique_ptr.h:453: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = git_tree_entry; _Dp = nix::Deleter<git_tree_entry_free>; typename std::add_lvalue_reference<_Tp>::type = git_tree_entry&]: Assertion 'get() != pointer()' failed.
Aborted (core dumped)
```

Seems like it's related to fetching git dependecy from Cargo.toml

**Steps To Reproduce**
Sorry, I do not have example to reproduce.

**`nix-env --version` output**
nix-env (Nix) 2.20.3

**Additional context**
I'm using nix on Arch Linux 6.7.6-arch1-2

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by alerque** [comment] 2024-03-04 08:56
Arch Linux packager here.

This seems to be turning up on Arch Linux builds but not the upstream binary release. That spawned [this packaging issue](https://github.com/NixOS/nix/issues/1012https://gitlab.archlinux.org/archlinux/packaging/packages/nix/-/issues/1) where @loqs pointed out that this can be made to work if you remove `-Wp,-D_GLIBCXX_ASSERTIONS` from CXXFLAGS.

I have rebuilt and deployed an Arch Linux package with this change which seems to work better, but I am not qualified to say if that is the actual fix to the underlying problem. Since this is part of the default build flags for Arch packages it seems like something else is amiss here. Hopefully somebody with more expertise in C++ issues can speak to what should actually happen longer term.

**Comment by thufschmitt** [comment] 2024-03-04 09:33
@alerque : does https://github.com/NixOS/nix/issues/10095 fix it for you? Or is it a separate issue?

**Comment by MrFoxPro** [comment] 2024-03-04 12:08
> Arch Linux packager here.
> 
> This seems to be turning up on Arch Linux builds but not the upstream binary release. That spawned [this packaging issue](https://github.com/NixOS/nix/issues/1012https://gitlab.archlinux.org/archlinux/packaging/packages/nix/-/issues/1) where @loqs pointed out that this can be made to work if you remove `-Wp,-D_GLIBCXX_ASSERTIONS` from CXXFLAGS.
> 
> I have rebuilt and deployed an Arch Linux package with this change which seems to work better, but I am not qualified to say if that is the actual fix to the underlying problem. Since this is part of the default build flags for Arch packages it seems like something else is amiss here. Hopefully somebody with more expertise in C++ issues can speak to what should actually happen longer term.

I see you fixed that. Thanks!

**Comment by alerque** [comment] 2024-03-04 12:32
Please re-open this issue. I don't believe it is fixed, only worked around and avoided. I would like the issue to get a look from somebody with C++ expertise because I think there is still a bug lurking here that is not fixed.

**Comment by intelfx** [comment] 2024-03-05 00:09
Would really like a reproducer here...

**Comment by intelfx** [comment] 2024-03-05 08:22
@alerque Yep I've found the reproducer on the Arch GitLab already. Can you try applying the linked PR?

**Comment by alerque** [comment] 2024-03-05 21:21
#10154 seems to have actually fixed this.

@MrFoxPro You can close this now, I think it's solved for real now.

**Closed** 2024-03-06 06:22 UTC
Labels: bug
