### ISSUE TITLE
Allow evaluating local flakes directly

### ISSUE THREAD

**Issue by Atemu** [NixOS/nix#4772] opened 2021-05-05 11:40 UTC
**Is your feature request related to a problem? Please describe.**

Currently, when you do something like `nix build .#hello` inside a local Nixpkgs checkout, the entire needs to be dumped into the Nix store.

That takes quite a while even on an SSD and wastes erase cycles too.

This behaviour is especially problematic in combination with bash completion as it calls nix for everything separately. Bash completion is unusable with local flakes.     

**Describe the solution you'd like**

Local flakes should be evaluable directly just like regular local Nix expressions are.

**Describe alternatives you've considered**

The state of the directory could at least be cached but that's not a great solution. 

**Additional context**

https://discourse.nixos.org/t/troubles-adopting-the-new-nix/12870

**Comment by edolstra** [comment] 2021-05-05 12:31
Duplicate of #3121.

**Closed by edolstra** 2021-05-05 12:31 UTC
Labels: improvement
