### ISSUE TITLE
Example nix-shell command from installer does not work on macOS

### ISSUE THREAD

**Issue by svniemeijer** [NixOS/nix#1488] opened 2017-07-25 07:35 UTC
The installation script `scripts/install-darwin-multi-user.sh` provides the following example command after installation:

`nix-shell -p figlet -p lolcat --run "echo 'nix rules' | figlet | lolcat"`

However, trying this on macOS (10.12) gives me:

`/nix/store/fpqvm0gishkdjcyq607gi3h9jvabadvv-stdenv-darwin/setup: line 34: local: -n: invalid option
local: usage: local name[=value] ...`
`/nix/store/fpqvm0gishkdjcyq607gi3h9jvabadvv-stdenv-darwin/setup: line 34: local: -n: invalid option
local: usage: local name[=value] ...`
`/nix/store/fpqvm0gishkdjcyq607gi3h9jvabadvv-stdenv-darwin/setup: line 86: failureHooks: command not found`

My nix channel is set to `https://nixos.org/channels/nixos-17.03`

**Comment by edolstra** [comment] 2017-07-25 10:28
Duplicate of https://github.com/NixOS/nixpkgs/issues/27493.

**Closed by edolstra** 2017-07-25 10:28 UTC
