### ISSUE TITLE
nix flake schema - change "nixosModules" attribute to "modules" for more generality

### ISSUE THREAD

**Issue by marksisson** [NixOS/nix#6723] opened 2022-06-25 14:19 UTC
Since modules are a general mechanism, applicable in other scenarios such as home-manager and nix-darwin, the flake schema attribute "nixosModules" seems too narrow and specific.  I currently use the "nixosModules" attribute for specifying home-manager and nix-darwin modules in flakes.  Would it be better to have the flake schema attribute be just "modules"?  This might also be considered for "nixosConfigurations" -- just make it "configurations", since this can be used for darwin configurations, and maybe other configurations in the future.

Is this a tight coupling between Nix and NixOS that should be avoided?

**Comment by bew** [comment] 2022-06-25 16:16
Isn't this a duplicate of #6257 ?

**Comment by marksisson** [comment] 2022-06-25 19:06
yes, looks like duplicate.

Just for some additional input, here is what I am doing to use nixosConfigurations to specify home-manager and darwin configurations.  This does work, but shows that a generalized "configurations" might be better.

This flake allows me to run

`darwin-rebuild switch --flake ".#marks-macbook-pro"`
`home-manager switch --flake ".#marksisson" --impure`

and

`nix flake check`

without any errors

```nix
{
  description = "Mark Sisson's configurations";
 
  inputs = {
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.inputs.utils.follows = "flake-utils";
  };
 
  outputs = { self, nixpkgs, nix-darwin, home-manager, flake-utils }@args:
 
    let
      darwinSystem = "x86_64-darwin";
      darwinSystemPkgs = import nixpkgs { localSystem = darwinSystem; };
      # configuration types
      homeConfigurations = "homeConfigurations";
      darwinConfigurations = "darwinConfigurations";
    in {
      nixosConfigurations = let
        user = "marksisson";
        host = "marks-macbook-pro";
      in {
        #
        # home-manager configurations
        #
        "${homeConfigurations}-${user}" = (nixpkgs.lib.recursiveUpdate
          (home-manager.lib.homeManagerConfiguration {
            system = darwinSystem;
            pkgs = darwinSystemPkgs;
            username = "${user}";
            homeDirectory = "/Users/${user}";
            stateVersion = "21.03";
            configuration = { ... }: {
              imports = [ ./home.nix ];
            };
          }) {
            # set this attribute to satisfy nix flake check
            config.system.build.toplevel =
              self.nixosConfigurations."${homeConfigurations}-${user}".activationPackage;
          });
      } // {
        #
        # darwin configurations
        #
        "${darwinConfigurations}-${host}" = (nixpkgs.lib.recursiveUpdate
          (nix-darwin.lib.darwinSystem {
            system = darwinSystem;
            modules = [ ./system.nix ];
          }) {
            # set this attribute to satisfy nix flake checklake check
            config.system.build.toplevel =
              self.nixosConfigurations."${darwinConfigurations}-${host}".system;
          });
      };
 
    } // flake-utils.lib.eachSystem [ "x86_64-darwin" ] (localSystem:
      let pkgs = import nixpkgs { inherit localSystem; };
      in {
        # make homeConfigurations visible to home-manager
        legacyPackages.homeConfigurations = nixpkgs.lib.mapAttrs'
          (attr: value: {
            name = nixpkgs.lib.removePrefix "${homeConfigurations}-" "${attr}";
            inherit value;
          }) (nixpkgs.lib.filterAttrs
            (attr: _: nixpkgs.lib.hasPrefix "${homeConfigurations}" attr)
            self.nixosConfigurations);
 
        # make darwinConfigurations visible to darwin-rebuild
        legacyPackages.darwinConfigurations = nixpkgs.lib.mapAttrs'
          (attr: value: {
            name =
              nixpkgs.lib.removePrefix "${darwinConfigurations}-" "${attr}";
            inherit value;
          }) (nixpkgs.lib.filterAttrs
            (attr: _: nixpkgs.lib.hasPrefix "${darwinConfigurations}" attr)
            self.nixosConfigurations);
 
        formatter = pkgs.nixfmt;
      });
}
```

**Comment by thufschmitt** [comment] 2022-12-06 14:15
> Isn't this a duplicate of https://github.com/NixOS/nix/issues/6257 ?

It is indeed. I'll close this in favour of #6257 to keep the discussion scoped.

**Closed by thufschmitt** 2022-12-06 14:15 UTC
