### ISSUE TITLE
perl: warning: Setting locale failed.

### ISSUE THREAD

**Issue by joepie91** [NixOS/nix#615] opened 2015-08-23 18:55 UTC
[This issue](https://unix.stackexchange.com/questions/187402/nix-package-manager-perl-warning-setting-locale-failed) also occurred to me after installing Nix (latest) on openSUSE 13.1 x86_64.

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "",
        LC_ALL = "en_US.UTF-8",
        LC_CTYPE = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

The issue occurs for *any* Nix command, often many times (eg. when installing dependencies, it happens at least once for each dependency).

The workaround there (setting `LC_ALL` in `.bashrc`) works, but as that thread states:

> This is more of a workaround (as LC_ALL is also strongly discouraged), but my guess is the reason for this behaviour lies in assumptions nix makes about locales on the system which don't apply on openSUSE.

**Comment by yoshuawuyts** [comment] 2016-03-22 05:30
I can confirm this also happens on `Ubuntu 14.04.3 LTS`, and am having issues with this on the latest NixOS - messing with locales is quite frustrating :(

**Comment by domenkozar** [comment] 2016-08-11 15:16
Since https://github.com/NixOS/nix/issues/341 is basically done, I'll close this as Nix won't have any perl code.

**Closed by domenkozar** 2016-08-11 15:16 UTC

**Comment by joepie91** [comment] 2016-08-11 15:23
Hmm. Are you certain that this was actually a Perl issue, rather than just being a *symptom* of wider locale-related issues?

**Comment by domenkozar** [comment] 2016-08-11 15:31
@joepie91 it was due to glibc locale archive incompatibility ABI, but only Perl used that. C++ code doesn't depend on locales.
