### ISSUE TITLE
assert failure !S_ISDIR when checking owner in canonicalisePathMetaData_

### ISSUE THREAD

**Issue by martinetd** [NixOS/nix#4053] opened 2020-09-23 13:13 UTC
**Describe the bug**

I tried rebuilding nix with `nix-build -A defaultPackage.x86_64-linux` a second time after modifying something and the builder failed with assert failure:
```
nix-daemon: src/libstore/local-store.cc:481: void nix::canonicalisePathMetaData_(const Path&, uid_t, nix::InodesSeen&): Assertion `!S_ISDIR(st.st_mode)' failed.
```

**Steps To Reproduce**

Here's what I ran but I suspect I would get the same error with the base nix-daemon (currently rebuilding, takes ~1h on this machine so writing this while waiting... I'll edit when confirmed and remove step 2 at that point)

1. run `nix-build -A defaultPackage.x86_64-linux` in nix repo
2. replace whatever nix-daemon is running with new one
3. modify something in nix repo
4. run same nix-build command again

**Expected behavior**

Get a better error than `error: unexpected end-of-file` on the client / `nix-daemon: src/libstore/local-store.cc:481: void nix::canonicalisePathMetaData_(const Path&, uid_t, nix::InodesSeen&): Assertion `!S_ISDIR(st.st_mode)' failed.` on daemon

**Additional context**

It looks quite a bit like #122 so I assume I did something wrong (e.g. should clean whatever previous build output I had before rebuilding?) but I think in general it would be better to throw an error than to assert this should not be a directory?
I mean, assert should be reserved for internal state errors that really ought to be impossible to hit in the wild, stuff that can happen are allowed to fail but some error would help.

Cheers.

**Comment by edolstra** [comment] 2020-09-23 13:25
Dupe of #4021. I'm looking into it right now.

**Closed by edolstra** 2020-09-23 13:25 UTC
Labels: bug
