### ISSUE TITLE
`tomlFormat.generate` doesn't chomp tab indentation

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nix#8874] opened 2023-08-27 18:02 UTC
*Transferred from https://github.com/NixOS/nixpkgs/issues/251823 as instructed [on matrix](https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$APsgULbRRlGorQs5oIFaWKBc8MYjiyoHikz8iFOv8yM?via=nixos.org&via=matrix.org&via=tchncs.de) due to GitHub's issue transfering not working correctly*

---

### Describe the bug

Issues observed in home-manager's `program.starship.settings.format` as described in https://github.com/nix-community/home-manager/issues/4382

### Steps To Reproduce

Declare `tomlFormat.generate` with 2nd argument that is using tabs for indentation parsed through `''` string as shown in linked issue.

### Expected behavior

Work without issues on tab indentation

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/11302521/f878b461-17a9-44d9-a98f-ed8c0f82d911)

### Additional context

Affected line:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/pkgs-lib/formats.nix#L198

Discussed on matrix: https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$n1AQxqYcMCHglb15MfUxujcN9tISVsPvzGStK2L0Ciw?via=nixos.org&via=matrix.org&via=tchncs.de

### Notify maintainers

Unsure who to notify, triage

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8-xanmod1, NixOS, 23.05 (Stoat), 23.05.2775.720e61ed8de1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(raptor): `"home-manager-23.05.tar.gz, nixpkgs-23.05, nixpkgs-unstable"`
 - nixpkgs: `/home/raptor/.nix-defexpr/channels/nixpkgs`
```

**Comment by infinisil** [comment] 2023-08-27 21:35
Duplicate of https://github.com/NixOS/nix/issues/3759 or https://github.com/NixOS/nix/pull/2911

**Comment by roberth** [comment] 2023-09-03 17:28
Unfortunately we're stuck with this behavior, it is actionable as [discussed](https://github.com/NixOS/nix/pull/2911#issuecomment-1635778908) by the team, to introduce warnings for this, or move RFC 137 forward.

Closing as duplicate.

**Closed by roberth** 2023-09-03 17:28 UTC
Labels: bug
