### ISSUE TITLE
nix-shell 1.11.5 executes stdin with bash if stdin is non-interactive

### ISSUE THREAD

**Issue by Baughn** [NixOS/nix#1186] opened 2017-01-12 22:39 UTC
Sounds crazy, doesn't it? But, nevertheless:

`test.sh:`
```
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash

cat
```

This should simply echo stdin. However...
```
$ echo 'echo "Hi!"' | ./test.sh
Hi!

$ ./test.sh  # Behaves normally
```

This may be related to issue #1171. I found the culprit by bisecting NixOS; I'm not sure how to test with a built-from-source Nix package.

**Comment by grahamc** [comment] 2017-01-12 23:05
I can replicate:

Using master's nix:
```
$ echo 'echo hi' | PATH=$(pwd)/result/bin:$PATH ./test.sh
hi
```

Using 16.09's nix:
```
$ echo 'echo hi' |  ./test.sh
echo hi
```

**Comment by edolstra** [comment] 2017-01-13 09:31
Dupe of #1171?

**Comment by edolstra** [comment] 2017-01-13 10:04
Indeed a4ad1ffa252d2e5d74eea8c56479f6bf27e316e7 fixes this. I'll do a 1.11.6 release.

**Closed by edolstra** 2017-01-13 10:04 UTC
