### ISSUE TITLE
Nix-shell reevaluating shellHook from shell configured by ```nix-shell some_file.nix``` for next new ```nix-shell -p```

### ISSUE THREAD

**Issue by SeaOfCrystalGreens** [NixOS/nix#10679] opened 2024-05-11 11:22 UTC
nix-shell seems to rerun shellHook from
```
pkgs.mkShell {
  buildInputs = with pkgs; [ nodejs_21 ];
  shellHook = ''
    echo n2.nix
  '';
}
```
for most recently used file.nix after

```
> nix-shell file.nix
```
when invoking ```nix-shell``` with  ```--package``` parameter in any directory.
When invoking only ```nix-shell``` and ommiting ```--package```
```
error: getting status of '/.../default.nix': No such file or directory
```
is emited.

**Steps To Reproduce**
1. Create directory structure ```test/shells```
2. Crate file ```new_shell.nix``` inside ```shells```
3. Content of file ```new_shell.nix```
```
{ pkgs ? import <nixpkgs> {} }:
let
  
in
pkgs.mkShell {
  buildInputs = with pkgs; [ ];
  shellHook = ''
    echo new_shell.nix
  '';
}
```
4. Run ```nix-shell new_shell.nix``` when in ```shells``` folder
5. Change directory to ```test```
6. Running ```nix-shell``` results
```error: getting status of '/tmp/test/default.nix': No such file or directory```
Running ```nix-shell --packages``` results in evaluation of shellHook from ```new_shell.nix``` file and spawning new shell.
Then repeating ```nix-shell ---packages``` runs shellHook again

**Expected behavior**

When running `nix-shell --packages` inside `nix-shell` configured by some file, shellHooks from previous  shell are omitted for new shell.

**`nix-env --version` output**
```nix-env (Nix) 2.18.1```

**Additional context**

**Comment by abathur** [comment] 2024-05-11 11:58
This is a duplicate of #8257 (though i guess the title of that issue doesn't make it obvious).

**Closed** 2024-05-15 19:32 UTC
Labels: bug
