### ISSUE TITLE
How to add a git repo as dependency?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [NixOS/nix#10428] opened 2024-04-08 05:54 UTC
![image](https://github.com/NixOS/nix/assets/74532770/34ab3743-f2b1-43f1-9596-477e364ba28a)
I do not understand how make it work
I am trying to add a haskell repo

**Comment by Aleksanaa** [comment] 2024-04-09 00:54
This should be marked as question imo

**Comment by tomberek** [comment] 2024-04-10 19:17
Closing as not a bug. Please see the manual. You seem to be adding a Haskell package's repo directly has a Nix package. This likely needs more familiarity with how Nix packaging work.

**Closed by tomberek** 2024-04-10 19:17 UTC
Labels: bug
