### ISSUE TITLE
Get rid of the Perl dependency

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#341] opened 2014-09-16 13:30 UTC
I.e. rewrite nix-build, download-from-binary-cache etc. in C++.
- [x] [scripts/nix-collect-garbage.in](https://github.com/NixOS/nix/pull/522)
- [x] [scripts/find-runtime-roots.pl.in](https://github.com/NixOS/nix/commit/ee3032e4de439b481ce1a4bc7fd8d71ea6ed2c94)
- [x] [scripts/nix-copy-closure.in](https://github.com/NixOS/nix/pull/1023)
- [x] [scripts/nix-prefetch-url.in](https://github.com/NixOS/nix/commit/bec3c3160881fcedf226080f13739aee81adae1a)
- [x] [scripts/nix-install-package.in](https://github.com/NixOS/nix/pull/1021)
- [x] [corepkgs/buildenv.pl](https://github.com/NixOS/nix/pull/1020)
- [x] [scripts/nix-channel.in](https://github.com/NixOS/nix/pull/1026)
- [x] [scripts/build-remote.pl.in](https://github.com/NixOS/nix/pull/981)
- [x] [scripts/nix-build.in](https://github.com/NixOS/nix/pull/1018)
- [x] [scripts/nix-push.in](https://github.com/NixOS/nix/pull/1024)
- [x] [scripts/download-from-binary-cache.pl.in](https://github.com/NixOS/nix/commit/a6eed133c5a3602037bc48675ca783185cca5454)

Darwin:
- [x] [scripts/resolve-system-dependencies.pl.in](https://github.com/NixOS/nix/pull/1030)

**Comment by hilyjiang** [comment] 2015-01-24 06:03
+1

**Comment by domenkozar** [comment] 2015-04-08 19:52
Would also get rid of https://github.com/NixOS/nix/issues/19

**Comment by copumpkin** [comment] 2015-04-19 18:05
:+1: obviously. Seems like it wouldn't have to be a monolithic work item. I'm guessing many of the *.pm files are just wrapping functionality that's already in the C++ library, so some of that wouldn't even be necessary anymore. The individual utilities could be replaced one at a time if someone didn't want to take on the entire task at once.

**Comment by lethalman** [comment] 2015-04-21 17:03
I'm on `nix-collect-garbage` :) starting low

**Comment by copumpkin** [comment] 2015-04-21 17:05
Yay!

**Comment by edolstra** [comment] 2015-04-21 17:55
:beer:

**Comment by lethalman** [comment] 2015-04-23 10:46
I'm now on find-runtime-roots.pl

**Comment by edolstra** [comment] 2015-04-23 10:55
Rather than replacing it with an external C++ program, please add it directly to `gc.cc`.

**Comment by domenkozar** [comment] 2015-08-09 14:43
I've added a 50$ bounty for this issue at https://www.bountysource.com/issues/4399291-get-rid-of-the-perl-dependency

**Comment by bjornfor** [comment] 2015-11-07 09:17
Is there a bounty service that doesn't require sign-up? I'd like to support, but I don't want yet another account on some web service...

**Comment by domenkozar** [comment] 2015-11-07 09:21
You can login with github account. But no :)

**Comment by vcunat** [comment] 2015-11-07 09:24
And you can always make promises without any service at all...

**Comment by bjornfor** [comment] 2015-11-07 09:29
Ah, I didn't know bountysource was "a promise", I thought it was direct payment.

**Comment by vcunat** [comment] 2015-11-07 09:36
Well, perhaps, but I think there's an unavoidable tricky point: who decides that the issue is solved well-enough?

**Comment by AndersonTorres** [comment] 2015-11-07 18:39
Also, what if multiple people solve it?

**Comment by domenkozar** [comment] 2015-11-07 18:44
The one offering the bounty decides how the money should be split.

**Comment by vcunat** [comment] 2015-11-07 18:52
Well, nice theoretical discussion, but for all nixos.org stuff I've only seen this single bounty offer of $50 &ndash; that probably wouldn't pay more than a single day of work for most people, so overall there seem to be basically no incentive for bounty hunting.

**Comment by AndersonTorres** [comment] 2015-11-07 22:57
Maybe some money if necessary, but it would be smaller than a day of work anyway. We can add some value by putting the name of hunter on a Nix congratulations list :)

**Comment by AndersonTorres** [comment] 2015-11-11 09:15
Well, I will study the sources at Saturday. Maybe I can do something :)

**Comment by offlinehacker** [comment] 2015-11-12 11:34
I've added additional 50$ to the bounty, i know the pain involved with cross compiling nix, so i would love to see this solved :)

**Comment by garbas** [comment] 2015-12-07 00:16
i've also added additional $50 for this effort ...  ![badge](https://api.bountysource.com/badge/issue?issue_id=4399291)

**Comment by domenkozar** [comment] 2016-01-03 10:59
So here's an idea: let's fund the whole development of this effort. I think it's an important milestone for Nix and I'm willing to invest some of personal finances just to really get it done. It's a tedious job and I really think whoever gets it done deserves a payment.

Proposal: is anyone willing to port Perl code to C++ and being paid for it? Send me an email to domen@dev.si and let's talk how to make it happen.

**Comment by davidak** [comment] 2016-01-03 22:09
@domenkozar great. i also added some money to the bounty. you can pay with bitcoin :)

i also shared it on Diaspora*

**Comment by domenkozar** [comment] 2016-01-11 10:43
I'm really excited to announce a (proper!) funding campaign for this issue. Shea Levy stepped up as the implementer, he's familiar with the codebase and currently top 2 contributor.

I'd like to invite everyone that is excited about this work (if not, see the link for why you should be) to donate funds at https://www.gofundme.com/htuafwrg/

**Comment by MarcWeber** [comment] 2016-01-11 15:37
I just saw this effort. Let me remind that there are alternatives to C++ such as rust which could be evaluated as well. We all know that Sha is very capable of many things. Thus an interesting idea would be to do ask another question: If there were $3000, would there be other tasks as well? If I had $3000 I'd spend them on a proper open source versioning database from which many .nix derivations could be derived. Something like hackage but for C/C++ and all the other small items. Because if you do that, more devs might join in the long run.

**Comment by domenkozar** [comment] 2016-01-11 16:08
@MarcWeber I agree - but funding this was initiated because doing such tedious rewriting work is not exciting, but it's important for Nix to prosper. Scope of porting Perl parts to C++ is smaller compared to introducing Rust, so that's why we're going after the former. Baby steps.

**Comment by copumpkin** [comment] 2016-01-11 16:18
Yeah, rewriting the whole thing in rust seems far more expensive (time and money). It might be more appealing for people working on it in their free time, but in the meantime we have a problem that can be solved fairly easily and quickly.

Rust also adds additional compilation requirements on environments we want to bootstrap and compile Nix on, whereas a c++ compiler is pretty much ubiquitous.

I personally dislike c++ but still think this is a pretty valuable thing to do (which is why I overcame my dislike for the language threw money behind it anyway) independent of any other concerns.

**Comment by AndersonTorres** [comment] 2016-01-12 00:56
Also, we can just do a parallel working for Rust - even opening a new github page for it.

**Comment by domenkozar** [comment] 2016-01-12 10:19
@offlinehacker @davidak did you donate to the campaign? We'll cancel the bounty :)

**Comment by davidak** [comment] 2016-01-12 10:42
@domenkozar like i said on twitter, i can't because only credit cards are accepted.

https://twitter.com/davidak/status/686518703085727745

i would like to pay with Bitcoin or SEPA to have no fees.

**Comment by domenkozar** [comment] 2016-01-12 10:45
@davidak that's fine, I'll make sure we also catch your contribution on bountysource :)

**Comment by vcunat** [comment] 2016-01-12 10:58
SEPA is only possible in Euros and within EU, AFAIK. I believe that's not useful for Shea in particular. (Maybe a promise of sending bitcoins is enough, but I can't speak for him.)

**Comment by davidak** [comment] 2016-01-12 11:07
@vcunat Yes, SEPA is wire transfer within the EU. He could just claim the bounty at Bountysource and withdraw it with "Paypal, Bitcoin, or physical check". If that count official to the needed amount i may donate some more. If @shlevy would accept i can also send Bitcoins directly to lower the fees.

**Comment by garbas** [comment] 2016-01-12 11:26
I've also added $50 to bountysource. you can also count on that (apart from the
money i've donated).

**Comment by shlevy** [comment] 2016-01-12 14:53
@davidak What's the fee from bountysource to get a check? If it's in the same range as gofundme's, I'm happy to count bountysource toward the total.

**Comment by vcunat** [comment] 2016-01-12 15:54
@shlevy: [10% on withdrawal](https://www.bountysource.com/fees).

**Comment by copumpkin** [comment] 2016-01-12 15:55
Wow, that seems pretty brutal. Makes me not want to use them anymore.

**Comment by copumpkin** [comment] 2016-01-12 15:57
I guess gofundme ends up being pretty expensive too, after WePay fees. I hate the payments industry.

**Comment by shlevy** [comment] 2016-01-12 17:03
Ugh, I thought gofundme was 5% but I didn't see the wepay cut. I'll start the work when the total after all fees is around $3220 (i.e. as if gofundme hit the campaign goal)

**Comment by davidak** [comment] 2016-01-12 17:14
@copumpkin i thought the same! SEPA is free and Bitcoin has technical a very low fee. (you can pay nothing but the transfer takes more time) And bitcoin.de as a marketplace has 1% fee divided between the 2 trading partners (->0,5%). Paypal has 3% fee what is also very expensive i think. So i try to use Bitcoin for most payments.

**Comment by domenkozar** [comment] 2016-01-17 17:32
We're at $2200 out of $3500 at https://www.gofundme.com/htuafwrg/

**Comment by bjornfor** [comment] 2016-01-17 17:41
Thanks for the reminder. (Now it's at $2320.)

**Comment by domenkozar** [comment] 2016-01-28 18:12
We're at $3220. Only $280 left! https://www.gofundme.com/htuafwrg/

**Comment by shlevy** [comment] 2016-01-28 21:06
We're funded! I'll get started soon, hopefully this weekend!

**Comment by copumpkin** [comment] 2016-01-29 00:15
[Amazing!](https://www.youtube.com/watch?v=fTQvnhNVgxQ)

**Comment by aristidb** [comment] 2016-04-03 18:45
What's the current status of this?

**Comment by shlevy** [comment] 2016-04-20 14:51
Mea culpa, I've seriously let this slip! Working on build-remote now, will keep updated as I go.

**Comment by domenkozar** [comment] 2016-05-11 10:23
@shlevy I think it's best to open a PR per script to get the process going asap and to have it split into minimalistic PRs

**Comment by shlevy** [comment] 2016-05-19 18:08
Update: Mostly through build-remote, I had a sudden job opportunity starting the end of April and am planning and presenting at a conference at the end of May, so I won't be able to do more on this until June. I will update again June 5, hopefully with a PR or two

**Comment by domenkozar** [comment] 2016-05-19 18:18
Awesome :)

**Comment by domenkozar** [comment] 2016-06-03 10:17
I'm really excited about this work, I just went through our issues tagging those that are related to install and this should really reduce the number of errors folks are getting! :)

**Comment by shlevy** [comment] 2016-06-06 00:43
OK, back on a normal schedule! Should have 1-3 hours a day for the next week, will update again on Wednesday evening with status. Currently have tests and the scaffolding of build-remote done, as well as about 70% of the logic.

**Comment by domenkozar** [comment] 2016-06-10 13:37
@shlevy that's a 10% removal, baby steps :) Keep it going!

**Comment by domenkozar** [comment] 2016-06-10 13:41
@shlevy also don't forget about https://github.com/NixOS/nix/issues/533

**Comment by domenkozar** [comment] 2016-06-27 07:13
@shlevy ping :)

**Comment by shlevy** [comment] 2016-07-04 14:53
WIP at https://github.com/shlevy/nix/tree/build-remote-c%2B%2B

**Comment by shlevy** [comment] 2016-07-08 18:53
WIP updated and rebased on master

**Comment by shlevy** [comment] 2016-07-13 10:35
Updated with implementation of ssh connection.

**Comment by shlevy** [comment] 2016-07-18 22:55
PR #981 open

**Comment by shlevy** [comment] 2016-07-20 18:01
PR #985 open

**Comment by domenkozar** [comment] 2016-07-21 13:09
@shlevy to spare you some time:

`scripts/nix-install-package.in` is deprecated https://github.com/NixOS/nix/issues/831

**Comment by shlevy** [comment] 2016-07-22 10:31
SSH store (to replace nix-copy-closure with nix copy as well as improve build-remote and bring back ssh substitutes) WIP at https://github.com/shlevy/nix/tree/ssh-store

**Comment by shlevy** [comment] 2016-08-08 11:56
Update: still working through nix-shell/nix-build conversion.

**Comment by shlevy** [comment] 2016-08-09 11:43
`nix-build`/`nix-shell` at #1018

**Comment by shlevy** [comment] 2016-08-10 12:11
#1020 for buildenv

**Comment by shlevy** [comment] 2016-08-10 12:22
Nuked nix-install-package in #1021

**Comment by domenkozar** [comment] 2016-08-10 12:34
@shlevy I've changed the description of this issue to reflect current status. Feel free to modify, for example I don't think `scripts/show-duplication.pl` is needed at runtime, `scripts/nix-generate-patches.in` is part of manifests also to be removed, etc.

**Comment by shlevy** [comment] 2016-08-10 12:36
@domenkozar How old is your nix checkout? :tongue: `nix-generate-patches` was removed in April

**Comment by domenkozar** [comment] 2016-08-10 12:37
Ah, I was copying @wmertens output. Removed :)

**Comment by domenkozar** [comment] 2016-08-10 12:48
@shlevy wait, only `nix-channel` and `nix-push` left?!

**Comment by shlevy** [comment] 2016-08-10 12:52
@domenkozar Too fast for me #1022

**Comment by edolstra** [comment] 2016-08-10 13:47
We can drop `nix-push` (since probably very few people use it and `nix copy` provides largely the same functionality), but we definitely need to keep `nix-copy-closure` for backwards compatibility.

**Comment by shlevy** [comment] 2016-08-10 13:52
@edolstra OK

**Comment by shlevy** [comment] 2016-08-10 14:46
OK nix-copy-closure migrated in #1023

**Comment by shlevy** [comment] 2016-08-10 15:13
nix-push removed in #1024

**Comment by knedlsepp** [comment] 2016-08-10 19:44
@pikajude: Am I correct in assuming that `scripts/resolve-system-dependencies.pl.in` is only relevant in the case of a chrooted build? It seems those don't work properly anyway: https://github.com/NixOS/nix/issues/759

**Comment by domenkozar** [comment] 2016-08-11 10:52
`nix-channel` port away from perl free Nix? :dancers:

**Comment by shlevy** [comment] 2016-08-11 15:00
nix-channel in #1026

**Comment by davidak** [comment] 2016-08-11 17:05
@shlevy Thank you! I just added another $50 to the bounty.

https://www.bountysource.com/issues/4399291-get-rid-of-the-perl-dependency

Don't forget to claim it when it is complete.

**Comment by shlevy** [comment] 2016-08-11 18:17
I consider the core work finished (if all PRs are merged and a simple final Makefile tweak added on top, nix on Linux has no dependency on perl) and the bounty is linked to this github issue. Any objections to me closing the issue to claim the bounty, and using the `perl-to-c++` milestone to track the remaining bits?

**Comment by domenkozar** [comment] 2016-08-11 20:38
@shlevy sure, if PRs are merged and Nix can compile without perl, feel free to claim this :)

**Comment by vcunat** [comment] 2016-08-12 06:53
I understood it as a suggestion to close/claim *before* merging the PRs.

**Comment by davidak** [comment] 2016-08-12 10:36
@vcunat No, the issue is solved for me when every change is merged in master. (and properly works together)

**Comment by shlevy** [comment] 2016-08-12 10:37
OK, thought I'd check :smile:

**Comment by shlevy** [comment] 2016-08-12 12:14
#1027

**Comment by domenkozar** [comment] 2016-11-01 20:09
@shlevy I'd say you have done your part of the work so it's fine if you collect the bounty.

**Comment by shlevy** [comment] 2016-11-01 22:35
@domenkozar Do I have to do anything besides just close the issue?

**Comment by domenkozar** [comment] 2016-11-02 08:21
I think you have to claim bounty on bountysource manually.

**Comment by shlevy** [comment] 2016-11-02 11:05
From https://github.com/bountysource/core/wiki/Frequently-Asked-Questions it looks like the only way is to close the issue, maybe even the only way is to merge a commit that closes the issue. I will try closing this, let me know if you get the confirmation email.

**Closed by shlevy** 2016-11-02 11:05 UTC
Labels: improvement

**Comment by domenkozar** [comment] 2016-11-02 11:34
I needed to refresh about 6 times before you showed up as a claimer on https://www.bountysource.com/issues/4399291-get-rid-of-the-perl-dependency, but it's accepted from me.

**Comment by shlevy** [comment] 2016-11-02 11:36
Did my summary not show up?

**Comment by domenkozar** [comment] 2016-11-02 11:38
Nope
