### ISSUE TITLE
boost::bad_format_string when IFD output contains %

### ISSUE THREAD

**Issue by YorikSar** [NixOS/nix#8761] opened 2023-07-31 13:34 UTC
**Describe the bug**

We ran into this issue when tools that run in IFD report errors that refer to source code containing `%` in some places. When the derivation fails to build, instead of reporting the error properly, Nix outputs:

```
error: boost::bad_format_string: format-string is ill-formed
```

I assume that when Nix outputs last log lines in the error, it erroneously passes it as a format string instead of data to some boost library.

**Steps To Reproduce**

I managed to shrink the example to this:

```
{
  nixpkgs ? builtins.getFlake "nixpkgs",
  system ? builtins.currentSystem,
  pkgs ? nixpkgs.legacyPackages.${system},
}: let
  d = pkgs.runCommand "fail" {} ''
    echo 'Fail %h%e%r%e'
    exit 1
  '';
in
  import d
```

Now when I build it, I get:

```
 % nix-build
building '/nix/store/95d4nqk01w9dy75pm5s50j3scxx9prbb-fail.drv'...
Fail %h%e%r%e
error: boost::bad_format_string: format-string is ill-formed
```

**Expected behavior**

If I replace the string in `echo` line with just `'Fail'`, I get a proper error reporting:

```
 % nix-build
building '/nix/store/8smyf82h6c1xyr4wylsx515grnj320h8-fail.drv'...
Fail
error:
       … while calling the 'import' builtin

         at /Users/tweag/tmp/nix-boost-format-error/default.nix:11:3:

           10| in
           11|   import d
             |   ^
           12|

       … while realising the context of path '/nix/store/r584a38rcs9hnvi01i5kwf2f542x7a3s-fail'

         at «none»:0: (source not available)

       error: builder for '/nix/store/8smyf82h6c1xyr4wylsx515grnj320h8-fail.drv' failed with exit code 1;
       last 1 log lines:
       > Fail
       For full logs, run 'nix-store -l /nix/store/8smyf82h6c1xyr4wylsx515grnj320h8-fail.drv'.
```

**`nix-env --version` output**

```
nix-env (Nix) 2.16.1
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by ettom** [comment] 2023-08-28 21:45
I bisected this:
```
29abc8e7647cd9ec6ef5a1df3fcb1dcf4a4495a2 is the first bad commit
commit 29abc8e7647cd9ec6ef5a1df3fcb1dcf4a4495a2
Author: Eelco Dolstra <edolstra@gmail.com>
Date:   Thu Mar 2 15:44:19 2023 +0100

    Remove FormatOrString and remaining uses of format()
```

Not sure where the exact problem is or how to fix it.

**Comment by bacchanalia** [comment] 2023-11-03 03:22
I root caused what is either this bug or a highly related bug. PR should be coming tomorrow, and I'll try to verify whether it fixes this issue.

**Comment by YorikSar** [comment] 2023-11-03 11:03
FIY I've committed a test that reproduces this issue: https://github.com/YorikSar/nix/commit/89aca4675e0f039ed12a730ba3c74f9285544777

**Comment by jsoo1** [comment] 2023-11-29 16:08
I believe this was closed by https://github.com/NixOS/nix/pull/9291

Tested the reproduction on master and the test passes.

@bacchanalia can you confirm?

**Comment by bacchanalia** [comment] 2023-11-29 16:11
I thought I tried this with my fix and still saw the error, but I might have made a mistake somewhere. I'll take another look.

**Comment by quantenzitrone** [comment] 2024-01-18 00:58
running
```bash
nix repl nixpkgs <<< ':b legacyPackages.x86_64-linux.fetchzip {
url = "mirror://sourceforge/projects/gprename/files/gprename/20230429/gprename-20230429.zip";
hash = "sha256-Du9OO2qeB1jUEJFcVYmLbJAGi2p/IVe3sqladq09AyY=";
}'
```
gives me
```c
error: boost::bad_format_string: format-string is ill-formed
```

not sure if it is this or #9204 or something else

**Comment by thufschmitt** [comment] 2024-01-18 07:16
@quantenzitrone what's the Nix version you're running on? I can't reproduce neither this nor #9204 on 2.19.

@YorikSar can you confirm that this specific issue is fixed?

**Comment by quantenzitrone** [comment] 2024-01-18 07:20
2.18.1

**Comment by thufschmitt** [comment] 2024-01-18 07:30
Strange, it works just fine for me:

```console
$ nix repl --extra-experimental-features repl-flake nixpkgs <<< ':b legacyPackages.x86_64-linux.fetchzip { 
url = "mirror://sourceforge/projects/gprename/files/gprename/20230429/gprename-20230429.zip";
hash = "sha256-Du9OO2qeB1jUEJFcVYmLbJAGi2p/IVe3sqladq09AyY=";
}'
Welcome to Nix 2.18.1. Type :? for help.

Loading installable 'flake:nixpkgs#'...
Added 5 variables.
Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
error: builder for '/nix/store/gp4c01piydkyq4frlpyn4pr852l31v21-source.drv' failed with exit code 1;
       last 25 log lines:
       > 100   138  100   138    0     0   1352      0 --:--:-- --:--:-- --:--:--  1366
       >   0   154    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
       > curl: (22) The requested URL returned error: 404
       >
       > trying https://versaweb.dl.sourceforge.net/sourceforge/projects/gprename/files/gprename/20230429/gprename-20230429.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       > 100   154  100   154    0     0    218      0 --:--:-- --:--:-- --:--:--   218
       >   0   154    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
       > curl: (22) The requested URL returned error: 404
       >
       > trying https://freefr.dl.sourceforge.net/sourceforge/projects/gprename/files/gprename/20230429/gprename-20230429.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0   345    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       >   0   154    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
       > curl: (22) The requested URL returned error: 404
       >
       > trying https://osdn.dl.sourceforge.net/sourceforge/projects/gprename/files/gprename/20230429/gprename-20230429.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       > 100   162  100   162    0     0    267      0 --:--:-- --:--:-- --:--:--   267
       >   0   154    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/gp4c01piydkyq4frlpyn4pr852l31v21-source.drv'.
error: build of 'xs878bq5f860yd9k3w0wzq121ag8hmlf-source.drv' failed

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
```

**Closed** 2024-10-23 13:58 UTC
Labels: bug

**Comment by AlexSherbinin** [comment] 2025-04-29 15:30
```
~/Projects/C/neovim on master ❯ nix-shell '<nixpkgs>' -A neovim-unwrapped
error: boost::bad_format_string: format-string is ill-formed

~/Projects/C/neovim on master ❯
```

Same issue when [following neovim BUILD.md](https://github.com/neovim/neovim/blob/master/BUILD.md#nixos--nix)

**Comment by sidkshatriya** [comment] 2025-05-06 05:31
I get the same error when trying to `nix-shell '<nixpkgs>' -A neovim-unwrapped` as mentioned by @AlexSherbinin above.

```bash
$ nix --version
nix (Nix) 2.28.3
```
