### ISSUE TITLE
Getting error: attribute 'unsafeDiscardStringContext' missing while full update on Linux

### ISSUE THREAD

**Issue by x80486** [NixOS/nix#4704] opened 2021-04-10 13:33 UTC
## Describe the bug

I usually do `nix-channel --update` and `nix-env --prebuilt-only --upgrade` to upgrade Nix and the installed dependencies. I started getting this error around 4/5 days ago:

```shell
unpacking channels...
warning: don't know how to open Nix store 'https://cache.nixos.org/'
created 1 symlinks in user environment
error: attribute 'unsafeDiscardStringContext' missing, at /nix/store/ff8fzv31yydp2qkbvqykjm15zkfs8f3n-nixpkgs-21.05pre281594.6fc2b7ecc2a/nixpkgs/lib/strings.nix:429:13
(use '--show-trace' to show detailed location information)
```

## Steps To Reproduce

1. Install Nix under Arch Linux
2. Update

## Expected behavior

To be able to update without error(s).

## `nix-env --version` output

```shell
[x80486@uplink:~]$ nix-env --version 
nix-env (Nix) 2.3.10
[x80486@uplink:~]$ uname -a 
Linux uplink 5.10.27-1-lts #1 SMP Tue, 30 Mar 2021 13:22:29 +0000 x86_64 GNU/Linux
```

**Comment by shyim** [comment] 2021-04-10 21:04
Ran into now also 😅

Also nix-env (Nix) 2.3.10
But running Nix inside an Debian docker container

**Comment by b0o** [comment] 2021-04-11 20:40
`nix-env --upgrade` has been failing with this error for me as well these past few days.

```
$ nix-env --upgrade --show-trace
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixpkgs' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: while evaluating anonymous function at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/top-level/impure.nix:15:1, called from /nix/store/0rl36g1wxzf89866h2ic1rwjlc0m8vc9-home-manager/home-manager/default.nix:1:10:
while evaluating anonymous function at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/top-level/default.nix:19:1, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/top-level/impure.nix:83:1:
while evaluating anonymous function at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:42:1, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/top-level/default.nix:122:10:
while evaluating 'dfold' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:60:27, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:136:4:
while evaluating 'go' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:63:18, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:72:13:
while evaluating 'imap1' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/lists.nix:116:14, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:78:30:
while evaluating 'reverseList' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/lists.nix:393:17, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/booter.nix:85:6:
while evaluating anonymous function at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/stdenv/default.nix:7:1, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/top-level/default.nix:118:12:
while evaluating 'elaborate' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/default.nix:18:15, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/pkgs/top-level/default.nix:52:17:
while evaluating 'foldl' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/lists.nix:80:20, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/default.nix:149:13:
while evaluating 'foldl'' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/lists.nix:82:16, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/lists.nix:86:8:
while evaluating the attribute 'parsed.abi.assertions' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/default.nix:23:7:
while evaluating 'mkSystemFromString' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/parse.nix:462:24, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/default.nix:23:16:
while evaluating 'mkSkeletonFromList' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/parse.nix:382:24, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/parse.nix:462:49:
while evaluating 'splitString' at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/strings.nix:427:23, called from /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/systems/parse.nix:462:69:
attribute 'unsafeDiscardStringContext' missing, at /nix/store/jpb8f98zm13bcwwycpbr8vclxrdd0l2b-nixpkgs-21.05pre281670.842f900e73c/nixpkgs/lib/strings.nix:429:13

$ nix-env --version
nix-env (Nix) 2.3.10

$ uname -srmov
Linux 5.11.12-1-ck-zen #1 SMP PREEMPT Thu, 08 Apr 2021 11:25:39 +0000 x86_64 GNU/Linux

$ lsb_release -idr
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
```

**Comment by leon-barrett** [comment] 2021-04-14 18:41
I believe this is caused by https://github.com/NixOS/nixpkgs/issues/118481 , where nix is being replaced by an "upgrade" to a broken statically-linked nix. While the bug is already closed, the PR hasn't yet rolled out to nixpkgs-unstable. https://nixpk.gs/pr-tracker.html?pr=119317

**Comment by adworacz** [comment] 2021-04-14 21:29
So, once this bug is fixed, how to we update to the latest version if the update mechanism is broken? Or perhaps I'm misunderstanding the ramifications of this issue.

**Comment by arsfeld** [comment] 2021-04-14 21:36
@adworacz you can rollback with `nix-env --rollback`, you might have to go a few versions back (at least I had to).

**Comment by adworacz** [comment] 2021-04-14 22:30
Excellent, @arsfeld, that's exactly what I needed.

**Comment by domenkozar** [comment] 2021-04-16 10:20
If you update nixpkgs-unstable this should be fixed now.

**Closed by domenkozar** 2021-04-16 10:20 UTC
Labels: bug

**Comment by adworacz** [comment] 2021-04-16 17:07
Confirmed - this is working just fine for me after upgrading.
