### ISSUE TITLE
Cannot build derivation on a fresh install, reasonable package

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nix#735] opened 2015-12-09 08:19 UTC
This is a fresh nix install on OS X and I'm writing some packages. I'm not done with one but I'm working with this one:

```nix
{ stdenv, fetchFromGitHub, automake, autoconf, libtool } :

stdenv.mkDerivation rec {

  name = "libbrotli";
  src = fetchFromGitHub {
    repo = "libbrotli";
    owner = "bagder";
    rev = "851122b665cde2374387c595ae3dc3369bf8ea05";
    sha256 =
    "76e0756130b273832b6792b7cfa88a8cf6c92b37c0ec4ff10b9637c335caeb7f";
  };
  buildInputs = [ automake autoconf libtool ];
  preConfigure = "./autogen.sh";
  meta = {
    description = "libbrotli";
  };
}
```

and then seeing if it installs/testing it with 

`nix-build -A libbrotli`

and getting:

```shell
output path ‘/nix/store/pdwz581jbf27cm2lvmngrhnrbyd5bv7a-bash43-042’ should have sha256 hash ‘1bwhssay66n75fy0pxcrwbm032s6fvfg7dblzbrzzn5k38a56nmp’, instead has ‘06a90k0p6bqc4wk2dsmapna69124an76xvlnlj3xm497vci968dc’
cannot build derivation ‘/nix/store/mcz594fvkwrf2ighnz2xh9w1qgznj5cy-bash-4.3-p42.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/n69kz335c800n2b6izsjbw60rlnvp87c-binutils-2.23.1.tar.bz2’
killing process 15456
cannot build derivation ‘/nix/store/bpz19s2byr1vh11gvvrvhk35fpw83qxi-libbrotli.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/bpz19s2byr1vh11gvvrvhk35fpw83qxi-libbrotli.drv’ failed
```

So I'm confused, as a new user. I don't think that my package is so wrong that it caused this problem, and what am I supposed to do in this situation, nothing really to rollback back to.

**Comment by fkz** [comment] 2015-12-09 11:47
this belongs to nixpkgs instead of nix.
duplicate of NixOS/nixpkgs#11512

**Closed** 2015-12-09 16:38 UTC
