### ISSUE TITLE
nix fails to rebuild itself when bootstrapping

### ISSUE THREAD

**Issue by xplat** [NixOS/nix#461] opened 2015-01-28 22:39 UTC
I'm following the instructions to install nix in $HOME [here](https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29).  I figured out and bypassed the problem where it indicates to use an older version of nix when 1.8 is needed to parse nixpkgs-unstable, and also figured out that i needed to run

> bin/nix-env -iA nixpkgs.nix

(rather than just with 'nix') to build the final version of nix using the bootstrap one in $HOME/nix-boot.  However, it's still failing:

> building path(s) ‘/home/james/nix/store/18sacv568bvrmnaz9lrl7wxn2nlvpbpc-mpc-1.0.1.tar.gz’
> 
> trying http://www.multiprecision.org/mpc/download/mpc-1.0.1.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 2960k  100 2960k    0     0   443k      0  0:00:06  0:00:06 --:--:--  509k
> output path ‘/home/james/nix/store/18sacv568bvrmnaz9lrl7wxn2nlvpbpc-mpc-1.0.1.tar.gz’ should have sha1 hash ‘vxg0rkyn4cs40wr2cp6bbcyr1nnijzlc’, instead has ‘m3i6nj5yybm97ka4yclmqs2iz73ssbh9’
> cannot build derivation ‘/home/james/nix/store/6lj26zj23pyscfv14px2ys88kj2705l0-mpc-1.0.1.drv’: 1 dependencies couldn't be built

I've tried it a number of times so it doesn't appear to be a transient error.

**Comment by iElectric** [comment] 2015-01-29 09:46
what version of nixpkgs?

**Comment by xplat** [comment] 2015-01-29 19:02
https://nixos.org/releases/nixpkgs/nixpkgs-15.05pre56948.53710c7/nixexprs.tar.xz

May not have been what I originally used but I can reproduce it with this.

Notably the 18sacv568bvrmnaz9lrl7wxn2nlvpbpc-mpc-1.0.1.tar.gz that fails the hash check is a tarfile, not a gzipped tarfile.

**Comment by edolstra** [comment] 2015-01-29 23:40
I can't reproduce this. `nix-build -A mpc.src` works for me.

Do you have a (transparent) proxy server? Maybe the `x-gzip` Content-Encoding on the tarball is causing the tarball to be decompressed down the line.

**Comment by xplat** [comment] 2015-01-30 16:47
Hm, there *is* a transparent proxy of some sort here.  I don't have control over it.  Is there a way I can scp the tarball in from another host, and/or use a socks5 proxy with nix to download things?

**Comment by xplat** [comment] 2015-01-30 19:08
It seems to work if i use 'http_proxy=socks5h://localhost:PORT nix-env'.  I was confused at first since HTTP_PROXY didn't do anything.

**Comment by edolstra** [comment] 2019-11-28 14:30
Closing on account of age.

**Closed by edolstra** 2019-11-28 14:30 UTC
Labels: backlog
