### ISSUE TITLE
null pointer cast to ref when building with ssh-ng

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#2086] opened 2018-04-18 09:07 UTC
First, to work around #2085, `nix build -f https://github.com/lheckemann/nixpkgs/archive/ebbbe24a3ea35e3a166b2d19ecdd5a4c3b79ba9a.tar.gz`

Then:
```
% nix build -f https://github.com/lheckemann/nixpkgs/archive/ebbbe24a3ea35e3a166b2d19ecdd5a4c3b79ba9a.tar.gz hello --store ssh-ng://root@192.168.99.14 # substitute some other machine you can access
error: null pointer cast to ref
[0.0 MiB DL]
error: unexpected EOF reading a line
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.15, NixOS, 18.03.132013.41b1c57d8dd (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.132013.41b1c57d8dd, nixos-unstable-18.09pre137207.92f0d31b949"`
 - channels(linus): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dtzWill** [comment] 2018-04-18 23:15
So I tried this just now, and indeed I had to do something like the command you suggest to workaround the linked issue (https://github.com/NixOS/nix/issues/2085#issuecomment-382355614).

Without this, error was:

```
tar: /nix/store/wpinwgcm4yd3q6vd72dglnx85akhd0sf-ebbbe24a3ea35e3a166b2d19ecdd5a4c3b79ba9a.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
error: program 'tar' failed with exit code 2
```

Anyway, that's not the interesting part.  The reason I'm commenting is because after running the command you suggested (which produces "error" message warning about attempting to build all packages, hehe) it... seems to have worked? At least the build started going...

Is your remote builder also running 18.03+ / Nix 2.x? Not sure what else would cause the discrepancy.

And is your Nix more or less what one'd get from the 18.03 branch? Currently that would be something like `/nix/store/r1kcvwv8jgwwcg2w5hrsqavaq8ir5pfi-nix-2.0`, FWIW.

---------

UPDATE: Poking at the path mentioned above, it looks like I can reproduce the problem when using that Nix but not my system Nix (~2.1).  Haven't attempted to chase down the fixed commit, but it appears this has been fixed in master.

Can you check with master? And for bonus points test if using 2.0-maintenance works (or bisect/chase down the fixing commit) so we can include the fix in next release?

Thanks, hope a newer Nix fixes the issue for ya!

**Comment by LnL7** [comment] 2018-04-18 23:34
@dtzWill I remember when I've seen this before now.

With nix 2.0 ssh-ng forwards all settings to the remote host causing problems for options that point to paths (eg. sandbox-paths) if the versions don't match exactly. That was fixed in https://github.com/NixOS/nix/pull/1948.

**Comment by dtzWill** [comment] 2018-04-19 00:04
I can confirm that reverting 088ef81759f22bf0115a52f183ba66b0be3b9ef2 produces a `nix` that generates the error, while with the commit (current master, for example) produces a `nix` where this works properly.  Woohoo!

**Closed** 2018-04-19 01:03 UTC
Labels: bug
