### ISSUE TITLE
Large files within source tree causes build to run out of memory

### ISSUE THREAD

**Issue by gulrotkake** [NixOS/nix#358] opened 2014-09-29 12:03 UTC
If the size of a file or a sufficient number of files in a nix-build exceeds the amount of memory available, Nix runs out of memory and gives up. For example, given this simple build:

```
{ stdenv, pkgs, ... } :

stdenv.mkDerivation rec {
  name = "huge";
  src = ./.;
  buildInputs = [ ];
  buildPhase =
    ''
        md5sum huge.bin > md5.result
    '';

  installPhase =
   ''
     mkdir $out
     mv md5.result $out
  '';
}
```

where huge.bin is a very huge file, nix will first warn:

```
warning: dumping very large path (> 256 MiB); this may run out of memory
```

before eventually running out of memory.

The above was tested with

```
nix-build (Nix) 1.8pre3834_9b146a5
```

**Comment by domenkozar** [comment] 2016-02-29 12:47
It would be nice if it printed out the file name

**Comment by sjmackenzie** [comment] 2016-02-29 12:53
Agreed, the file name would be most handy.

**Comment by sjmackenzie** [comment] 2016-02-29 13:22
We have 50 instances of `src = ./.` each time the `./.` points to the root of a rust project which consists of 4 files, one of which is in a folder called `src`. We have no instances of a large file/binary called with `./.`, just many (and growing quickly) instances of (`./.`).

**Comment by Ericson2314** [comment] 2016-03-01 04:45
Why does it even read the files all into memory? I assume the hash can be computed with constant space.

**Comment by sjmackenzie** [comment] 2016-03-01 05:09
For the record, we found the cause: it was a `.target` folder generated by the `rustc` compiler. Deleting that folder straightened `nix` again.

**Comment by domenkozar** [comment] 2016-11-16 11:42
@Ericson2314 https://github.com/NixOS/nix/pull/619

**Comment by domenkozar** [comment] 2016-11-29 14:49
Until this is fixed in Nix see https://nixos.org/wiki/How_to_add_files_to_the_nix-store#Large_files

**Comment by ip1981** [comment] 2017-02-03 09:30
> As a workaround, you could use fetchurl to get the file, e.g. fetchurl { src = file:///bla/huge; sha256 = ...; }.

There might be permission problem.

**Comment by fisx** [comment] 2017-09-28 16:30
> Until this is fixed in Nix see https://nixos.org/wiki/How_to_add_files_to_the_nix-store#Large_files

dead link, and it looks like this page does not exist on https://nixos.wiki/?

**Comment by dpc** [comment] 2017-11-02 06:24
Is there any way to make `src = ./. except for ./target`?

**Comment by sjmackenzie** [comment] 2017-11-02 06:28
take a look at `cleanSource` and `filterSource`

**Comment by siddharthist** [comment] 2017-11-15 22:52
I am also experiencing this problem while trying to install Mathematica.

Here's the old Wiki page on archive.org in case anyone else is searching for it: https://web.archive.org/web/20160829175307/https://nixos.org/wiki/How_to_add_files_to_the_nix-store

**Comment by bgamari** [comment] 2017-12-21 21:18
This is addressed by #619.

**Comment by Pitometsu** [comment] 2019-02-15 00:25
Looks as a solution for me: https://stackoverflow.com/a/39493330/3195266

**Closed** 2020-09-22 09:40 UTC
Labels: improvement
