### ISSUE TITLE
nix-build consumes a fair amount of memory while waiting for build scripts

### ISSUE THREAD

**Issue by nagisa** [NixOS/nix#3244] opened 2019-11-26 02:01 UTC
I was waiting for my custom kernel to rebuild as part of my `nixos-rebuild boot --upgrade` when I noticed that the process using most memory was `nix-build` itself, at 1.45G of RSS.

This seems excessive for a process that’s just `tee`ing output from a bash script and waiting for it to terminate.

Same thing happens with `nix build --no-link -f '<nixpkgs/nixos>' system` as well.

**Comment by grahamc** [comment] 2019-11-26 02:14
Duplicate of #54

**Closed by grahamc** 2019-11-26 02:14 UTC
