### ISSUE TITLE
Issue with nix installation - syntax error *env-manifest.next1:1

### ISSUE THREAD

**Issue by cochipdesign** [NixOS/nix#10792] opened 2024-05-28 04:19 UTC
## Platform

- [ ] Linux: 
- [ ] macOS
- [ Yes] WSL

## Additional information

Here is the command I used to install nix

sh <(curl -L https://nixos.org/nix/install) --yes --daemon --nix-extra-conf-file /dev/stdin <<EXTRA_NIX_CONF
extra-experimental-features = nix-command flakes
extra-substituters = https://openlane.cachix.org
extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
EXTRA_NIX_CONF

## Output

Here is the error I got

error: syntax error, unexpected end of file
       at /nix/store/rxsk1m9wnyqf19hal96hpfhqjarmh1gp-env-manifest.nix:1:1:

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Mic92** [comment] 2024-05-28 06:35
I just tried the exact command in a docker container but cannot reproduce the error.
Did you potentially had a data corruption during the download?

**Comment by cochipdesign** [comment] 2024-05-29 21:39
Hi Joerg,

I think you are right, i had a data corruption. I started installing things
on mac and all went well.

on windows I tried uninstalling ubunto and then reinstall but its causing
all kind of issues so I gave up on windows for now :-)


Thanks

Rashid Iqbal
CEO, Founder
***@***.***

**Comment by Mic92** [comment] 2024-05-31 07:42
Could close the issue than? Thanks!

**Comment by cochipdesign** [comment] 2024-06-03 06:22
Yes, i will.
Thanks

Rashid Iqbal
CEO, Founder
***@***.***

**Comment by cochipdesign** [comment] 2024-06-03 06:25
I have this working on mac. I think window issue was some kind of corruption of the installed tool.

**Closed** 2024-06-03 06:24 UTC
Labels: installer
