### ISSUE TITLE
`nix flake update <inputs>` doesn't allow multiple inputs

### ISSUE THREAD

**Issue by olmokramer** [NixOS/nix#10032] opened 2024-02-18 11:17 UTC
**Describe the bug**

The "Synopsis" section of `nix flake update --help` implies that the command can be used to update multiple inputs at once, specifically "inputs" being plural:

```
Synopsis

    nix flake update [option...] inputs
```

And later on in the "Description" section:

```
Description

    <snip>

    Unlike other nix flake commands, nix flake update takes a list of names of inputs to update as its positional arguments and operates on the flake in
    the current directory. You can pass a different flake-url with --flake to override that default.
```

However, when I run `nix flake update` with multiple inputs, I get the following error:

```
$ nix flake update nixpkgs home-manager
error: unexpected argument 'home-manager'
```

This could be either a documentation issue or an implementation issue, depending on what is actually the desired behaviour here.

**Steps To Reproduce**

1. In a terminal, `cd` to a flake that has multiple inputs.
2. Run `nix flake update <input1> <input2>`.
3. Get the error I described above:

       error: unexpected argument '<input2>'

**Expected behavior**

I expect the documentation to agree with reality. Moreover, since the documented behaviour is described multiple times, and it would be more useful than being able to update only a single input, I would expect the implementation to handle multiple inputs.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.19.3
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by olmokramer** [comment] 2024-02-18 11:28
PS I'd be willing to make a PR to fix this, but I've never worked on a C++ project before, so depending on how difficult this is to fix that might not be feasible.

**Comment by infinisil** [comment] 2024-02-19 19:45
Duplicate of https://github.com/NixOS/nix/issues/9764

**Comment by thufschmitt** [comment] 2024-02-20 10:21
Thanks @infinisil ! I knew there was already an issue for that, but I couldn't find it.
Closing that one then to keep the discussion in a single place

**Closed by thufschmitt** 2024-02-20 10:21 UTC
Labels: bug
