### ISSUE TITLE
Make `-L`/`--print-build-logs` configurable in a config file.

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nix#7237] opened 2022-10-29 19:28 UTC
**Is your feature request related to a problem? Please describe.**

I have to type `-L` after every command.

**Describe the solution you'd like**

Have the nix config file accept `print-build-logs`

**Describe alternatives you've considered**

`alias nix='nix -L'`

**Comment by Artturin** [comment] 2022-11-08 18:43
Dupe of https://github.com/NixOS/nix/issues/5858

**Closed by Artturin** 2022-11-08 18:43 UTC
Labels: feature
