### ISSUE TITLE
1.12 regression: if any of your configured binary caches is inaccessible, Nix fails

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1340] opened 2017-04-18 15:01 UTC
Previously (as far as I could tell), nix would try to grab `nix-cache-info` until `connect-timeout` expired, and then not use that cache if it failed. Now Nix fails altogether if any configured cache is inaccessible.

**Comment by domenkozar** [comment] 2017-05-10 08:36
Fixed by https://github.com/NixOS/nix/commit/9cc8047f44b3d333c2c55c140165bfd507f4d41e ?

**Comment by domenkozar** [comment] 2017-05-10 08:38
I've noticed that even in 1.11, if cache returns 500 for narfiles and `--fallback` is passed to Nix, it wouldn't fallback.

**Comment by edolstra** [comment] 2017-05-10 08:39
@domenkozar No, that just makes it fail faster :-)

**Comment by edolstra** [comment] 2017-05-10 08:40
Repro:
```
$ nix-build -A hello --option binary-caches 'https://cache.nixos.org/ https://example.org' 
error: ‘https://example.org’ does not appear to be a binary cache
```

**Comment by domenkozar** [comment] 2017-05-10 08:42
Interestingly, `sudo nix-build -A hello --check --option binary-caches 'https://httpbin.org/status/500' '<nixpkgs>'` does fallback.

**Comment by domenkozar** [comment] 2017-05-10 08:43
Oh because `https://httpbin.org/status/500/nix-cache-info` is 404.

**Comment by orivej** [comment] 2017-11-12 05:16
`https://hydra.nixos.org` fails with this message (`does not appear to be a binary cache`). Is this correct?

**Comment by 7c6f434c** [comment] 2018-02-08 21:25
I guess it is 2.0 regression now that 1.12 is renamed… (found this issue after also hitting it)

**Closed** 2018-02-09 14:11 UTC
