### ISSUE TITLE
nix-shell inherits single CPU affinity when derivation has import from derivation

### ISSUE THREAD

**Issue by nmattia** [NixOS/nix#3345] opened 2020-02-05 16:30 UTC
As title says. A `nix-shell` for the following derivation will have its affinity set to a single core:

``` nix
with import <nixpkgs> {};
stdenv.mkDerivation
  {
    src = lib.cleanSourceWith
      {
        src = ./.;
        filter = _: _: builtins.hasAttr "bar" (builtins.readDir hello);
      };
    name = "foo";
  }
```

``` console
$ nix-shell --run nproc
1
```

There's probably a `restoreAffinity()` missing somewhere.

**Comment by layus** [comment] 2020-02-06 10:07
From a rough inspection, I would say that the affinity setup is entered twice, and the second time the backup value gets overwritten by the current (restricted) affinity. Sort story long: this affinity setup is not re-entrant and is re-entered in this case.

It seem to happen in this example because two connections are opened at the same time, and the affinity setting occurs during remote store connection initialization.

**Comment by michaelpj** [comment] 2020-10-19 22:43
I'd love a fix for this, I had the same problem and lost almost a day before I tracked it down to this.

**Comment by layus** [comment] 2020-10-19 23:24
I guess we need @NixOS/nix-core to have a look at the proposed fix in #3346. While the code stalled, I would be happy to refresh it if we agree on the idea of the patch.

**Comment by michaelpj** [comment] 2021-06-03 08:30
Still important.

**Comment by gilligan** [comment] 2021-12-18 16:46
Just lost a decent amount of time because of this until I finally realised that this was the underlying issue.

**Comment by edolstra** [comment] 2021-12-22 13:51
I can't reproduce this BTW:
```
$ nix-shell ./foo.nix --run nproc 
16
```

**Comment by edolstra** [comment] 2021-12-22 14:19
Looks like CPU locking got disabled by accident (ba87b08f85).

**Closed** 2021-12-22 19:31 UTC
Labels: bug
