### ISSUE TITLE
nix-daemon hangs indefinitely in nix-1.12pre4911_b30d1e7

### ISSUE THREAD

**Issue by elitak** [NixOS/nix#1179] opened 2017-01-09 17:46 UTC
I've had this issue on 2 different machines using `nixpkgs.config.packageOverrides = pkgs: { nix = pkgs.nixUnstable; }`. Nothing can build because every nix-daemon process is hanging forever. It's a real pain to work around, since I need to manually `killall -9 nix-daemon; /nix/store/older-nix-1.12/bin/nix-daemon  --daemon`, in order to run `nixos-rebuild switch` out of the broken configuration. I don't have any details on why this is happening. I would start by stracing nix-daemon.

~~Oddly, The broken revision used in nixpkgs, b30d1e7ada0a8fbaacc25e24e5e788d18bfe8d3c, is already fixed somewhere before or at d0a2db17d91931cfd8d60e93d30cee20d39762c8. Was this bug understood and fixed intentionally? If so,~~ the revision in `<nixpkgs/pkgs/tools/package-management/nix/default.nix>` needs to be updated immediately so users don't get locked into their system profiles using `nixUnstable`. The threat is compounded by the fact that the schema upgrade to the db can't easily be reverted.

Edit: On second examination, I don't think this is fixed on any change later than b30d1e7ada0a8fbaacc25e24e5e788d18bfe8d3c.

Edit 2: I'm having problems finding a working revision of 1.12 to start `git bisect`ing from. I could be confounding this with my attempts to build a large derivation set, and that contributing to the nix-daemon lockup. I definitely never had problems with 1.11, so I will leave this open in case anybody else has experienced similar issues.

Edit 3: b99c6e0e2959e90ddda14d8b318e4c7b1a508674 works okay. I will wait for some input before I try to `git bisect` to find the regressive commit.

**Comment by expipiplus1** [comment] 2017-01-23 11:37
`edd5babb31efec337b756abd5d5de0b7ade89dc2` seems to work fine too.

**Comment by rht** [comment] 2017-01-28 05:52
Bump. Currently, I'm locked-in at https://github.com/NixOS/nix/commit/b30d1e7ada0a8fbaacc25e24e5e788d18bfe8d3c with no /nix/store/older-nix-1.12 available due to low disk space. I suspect that #1175 has the same bug.

https://github.com/NixOS/nixpkgs/pull/17631/files#diff-5712e736e0de6ba170577f8472c398e9R13 wouldn't do to fetch an older nix version (or nixStable) since it is the daemon that is frozen.

This is likely affecting everyone on https://github.com/NixOS/nix/commit/b30d1e7ada0a8fbaacc25e24e5e788d18bfe8d3c.

**Comment by rht** [comment] 2017-01-28 21:02
I was able to finally download a nixStable by bypassing the https protection

``nix --option binary-caches http://cache.nixos.org build /nix/store/k7mmbp7nk0289k57mj80ic54sby6wbkc-nix-1.11.6`` (only works for schema version 7 -- I should be able to proceed next after finding one that could do with schema version 10)

and could even proceed with `nixos-rebuild switch` by having add to NixOS config a line `nix.binaryCaches = "http://cache.nixos.org";`, however, this is unsafe.

What should be the safe way to downgrade to nixStable? (I am aware it is my foolishness to not the have previous generations in hand, but my disk space is limited)

**Comment by edolstra** [comment] 2017-01-30 09:51
Dupe of #1181?

**Closed** 2017-02-07 11:01 UTC
