### ISSUE TITLE
Nix self update not possible on mac

### ISSUE THREAD

**Issue by Sironheart** [NixOS/nix#10157] opened 2024-03-05 11:16 UTC
**Describe the bug**

Nix doesn't recognize being installed in a macOS environment and thus doesn't upgrade itself to the latest version.

**Steps To Reproduce**

1. Install nix on macOS.
2. Run `nix upgrade-nix`
3. Receive error "Nix on NixOS must be upgraded via 'nixos-rebuild'"

**Expected behavior**

Install latest version of universal nix cli.

**Additional context**

Just in case it's needed, here is my nix configuration: https://github.com/sironheart/nix-config

**Comment by abathur** [comment] 2024-03-05 14:11
Duplicate of:
- #5499

**Closed by abathur** 2024-03-05 14:11 UTC
Labels: bug
