### ISSUE TITLE
Assertion failed/Core dumped when installing neovim

### ISSUE THREAD

**Issue by faulesocke** [NixOS/nix#4788] opened 2021-05-10 13:35 UTC
**Describe the bug**
When I try to install neovim, I get an assertion failure from nix, indicating memory corruption:
```bash
% nix-env -f '<nixpkgs>' -iA neovim
installing 'neovim-0.4.4'
nix-env: src/libexpr/attr-set.hh:54: void nix::Bindings::push_back(const nix::Attr&): Assertion `size_ < capacity_' failed.
[1]    16366 abort      nix-env -f '<nixpkgs>' -iA neovim
```

This happens both under a fresh nixos installation as well as with nix on other distributions. I tried this on several different machines.

If this turns out to be an issue with nixpkgs, please feel free to move/close this issue.

**Steps To Reproduce**
See above.

**Expected behavior**
Should not crash.

**`nix-env --version` output**
```
nix-env (Nix) 2.3.10
```

**Comment by regnat** [comment] 2021-05-10 13:40
> If this turns out to be an issue with nixpkgs, please feel free to move/close this issue.

There might also be a nixpkgs issue, but Nix segfaulting is definitely a Nix bug :wink: But it might be a duplicate of https://github.com/NixOS/nix/issues/4709

Can you also give the exact nixpkgs revision you’re using?

**Comment by faulesocke** [comment] 2021-05-10 13:55
Here is `nix-info`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.32, NixOS, 21.05pre287333.63586475587 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre287333.63586475587"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I have this issue with multiple revisions of nixpkgs.

**Comment by faulesocke** [comment] 2021-05-10 14:00
Also affected:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.18_1, void, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(socke): `"nixpkgs-21.05pre287202.123db833485"`
 - nixpkgs: `/home/socke/.nix-defexpr/channels/nixpkgs`
```

**Comment by dotlambda** [comment] 2021-05-10 14:45
Same thing happening to me:
```
$ nix-env -u --always
unpacking channels...
upgrading 'ripgrep-all-0.9.6' to 'ripgrep-all-0.9.6'
upgrading 'nixos-shell-0.2.1' to 'nixos-shell-0.2.1'
upgrading 'sc-im-0.8.1' to 'sc-im-0.8.1'
upgrading 'hexchat-2.14.3' to 'hexchat-2.14.3'
upgrading 'nix-update-0.4.0' to 'nix-update-0.4.0'
upgrading 'chromium-90.0.4430.93' to 'chromium-90.0.4430.93'
upgrading 'gpicview-0.2.4' to 'gpicview-0.2.4'
upgrading 'gotop-4.1.1' to 'gotop-4.1.1'
upgrading 'openconnect-8.10' to 'openconnect-8.10'
upgrading 'firefox-88.0' to 'firefox-88.0.1'
upgrading 'imv-4.2.0' to 'imv-4.2.0'
upgrading 'xournalpp-1.0.20' to 'xournalpp-1.0.20'
nix-env: src/libexpr/attr-set.hh:54: void nix::Bindings::push_back(const nix::Attr&): Assertion `size_ < capacity_' failed.
[1]    1699861 abort (core dumped)  nix-env -u --always
```

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.14, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre287596.ae1c8ede09b"`
 - channels(rschuetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment] 2021-05-14 12:37
https://github.com/NixOS/nixpkgs/pull/122980 fixed this for me.

**Closed** 2021-07-14 08:15 UTC
Labels: bug
