### ISSUE TITLE
ref regex can contain forward slashes (bug)

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nix#4428] opened 2021-01-06 06:05 UTC
https://github.com/NixOS/nix/blob/eb458ad1b2d5ef316fe8948d4e1abd484dde41eb/src/libutil/url-parts.hh#L26

The following error is an illigitimate error:

> 
```console
URL 'github:input-output-hk/haskell.nix?ref=hkm/more-flake-support' contains an invalid branch/tag name
```

**Comment by cole-h** [comment] 2021-01-06 09:23
Related / duplicate of https://github.com/NixOS/nix/issues/4061.

**Comment by edolstra** [comment] 2021-01-06 10:41
Yes, looks like the same issue.

**Closed by edolstra** 2021-01-06 10:41 UTC
