### ISSUE TITLE
File descriptor leak in Nix master

### ISSUE THREAD

**Issue by regnat** [NixOS/nix#4046] opened 2020-09-21 18:16 UTC
**Describe the bug**

Building a derivation with Nix master leaves a number of file descriptors that aren't closed until Nix exits

**Steps To Reproduce**

1. In the background, monitor the number of FDs used by a `nix-build` process (replace by `nix-store` if you're using the daemon)
     ```console
     $ while true; do lsof -c nix-build | wc -l; done
     ```
2. Build a big-enough number of independant derivations:

   ```console
   $ nix-build many-drvs.nix
   ```

    where `many-drvs.nix` is as follows:

    ```nix
    let pkgs = import <nixpkgs> {}; in

    builtins.map
      (i: pkgs.writeText "foo" (toString builtins.currentTime + toString i))
      (pkgs.lib.genList (i: i) 1000)
    ```

    watch the output of `lsof` grow (up to ~5000 in my tests).

**Expected behavior**

The number of opened file descriptors should be bounded (it stays under 100 for nix 2.3.7)

**`nix-env --version` output**

```console
$ nix-env --version
nix-env (Nix) 3.0pre20200829_f156513
```

**Additional context**

Looking at the `lsof` output, I see a lot of `.lock` (~half of the output) and `.drv.bz2` (~1/4th of the output) files. I guess we forget to release these at some point

**Comment by cole-h** [comment] 2021-03-22 00:11
I just tried this on `nix-env (Nix) 2.4pre20210308_1c0e3e4` and it stayed at about 58 the entire time. It seems like this was resolved in some intermediate commit?

**Comment by edolstra** [comment] 2021-04-07 10:29
Yeah, I can't reproduce this. Top-level substitution goals had a similar FD leak (8a29052cb2f52ef2c82c36fb3818fd0f66349729).

**Closed by edolstra** 2021-04-07 10:29 UTC
Labels: bug

**Comment by veprbl** [comment] 2022-04-04 22:36
Still reproducible on 2.7.0

**Comment by thufschmitt** [comment] 2022-04-05 12:15
@veprbl how did you manage to reproduce it? Just tried on `2.8.0pre20220317_a0b517d`, but the FD count stayed nicely bounded

**Comment by veprbl** [comment] 2022-04-06 14:04
Just evaluated texlive from master on macOS and observed "Too many open files" on Nix 2.7.0. Trying on 2.3.16 fixed the issue.

**Comment by thufschmitt** [comment] 2022-04-06 14:21
Oh it’s happening at eval-time? Interesting…

Still can’t reproduce though. Maybe it’s a darwin-specific thing ? :thinking:

**Comment by veprbl** [comment] 2022-04-06 14:46
I meant build. I remember originally I also saw a similar behaviour on Linux, it was opening some extra files (not the .lock's) in the store.

**Comment by tobiasBora** [comment] 2022-05-02 09:24
I can experience this again, on NixOs when installing texlive with the documentation https://github.com/NixOS/nixpkgs/issues/171218

**Comment by aameen-tulip** [comment] 2022-05-04 00:01
This was causing issues for me building ( an admittingly large ) Yarn project on Debian 11 ( barebones cloud-init image with nothing other than `nix` installed ), Nix 2.7.0, multi-user.

Nix was trying to build ~6,000 derivations at once, so in fairness, it was a heavy load.

I tried several of the most common ways to raise the max file limit with little success; but what finally worked was overriding the limit in the service:
```
sudo systemctl edit nix-daemon.service;
# In your editor set these fields
[Service]
LimitNOFILE=65535
LimitNOFILESoft=65535
```
