### ISSUE TITLE
nix-env -i with no arguments will install every package

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nix#1334] opened 2017-04-15 10:54 UTC
When running `nix-env -i` without an argument, nix will try to install every package available.
It might be wiser to instead output an error message as it is unlikely that it is what the user wants to do.

This is even more problematic when `nix-env -i` is used in combination with `nix-build`, as if the `nix-build` command fail, `nix-env` will try to install every package, eg:

```
nix-env -i $(nix-build /dev/null)
```

**Comment by copumpkin** [comment] 2017-04-15 13:55
Yeah, I've seen several confused questions on IRC about this behavior.

**Comment by nh2** [comment] 2017-05-04 13:27
I've put moreinfo about this into https://github.com/NixOS/nix/issues/1373#issue-226151364

Specifically, it happens when passed a newline, but not when passed the empty string `""`.

**Comment by vcunat** [comment] 2018-08-11 12:26
This is also a duplicate of https://github.com/NixOS/nix/issues/308

**Closed by vcunat** 2018-08-11 12:26 UTC
Labels: backlog

**Comment by Diti** [comment] 2021-05-18 15:35
This is still an issue, I don’t think it should be closed. ☹️

**Comment by vcunat** [comment] 2021-05-18 15:48
#308 is open.  Seems enough to me.
