### ISSUE TITLE
Updating Docker Hub nixos/nix image

### ISSUE THREAD

**Issue by stephengroat** [NixOS/nix#2083] opened 2018-04-17 13:34 UTC
wondering what the status of https://hub.docker.com/r/nixos/nix/ is.

relatively easy to automate build & deployment of this image, is that something the project is interested in?

**Comment by edolstra** [comment] 2018-04-17 13:40
Yeah that would be good. I could add updating of the Docker image to the release script. Don't know who owns the nixos Docker repo though.

**Comment by stephengroat** [comment] 2018-04-17 14:00
@edolstra sorry, didn't know. thought that was under your control

since you do all the work on a dockerfile anyway, another path would be creating an official nix docker repository https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by domenkozar** [comment] 2018-04-17 16:38
I have access there. I'll make sure 2.0 is uploaded, but yeah it should be added to release steps.

**Comment by stephengroat** [comment] 2018-04-17 16:41
@domenkozar thanks so much! greatly appreciated!

**Comment by domenkozar** [comment] 2018-04-18 11:33
@LnL7 yeah we still need to get those merged with upstream. I think what's missing is a plan how to :)

**Comment by domenkozar** [comment] 2018-05-08 10:30
Pushed readme and nix bump at https://github.com/NixOS/nix/pull/2142

**Comment by stephengroat** [comment] 2018-05-17 20:47
@domenkozar work for me. let me know if this is good to close

**Comment by coretemp** [comment] 2018-05-26 19:59
Is this now automated or would people have to open a new issue for every release? 

Additionally, can the docker images be tagged with the hash to remove the impurity that has now been introduced? If the Nix release changes (or is tampered with), a different hash should be generated.

**Comment by domenkozar** [comment] 2018-05-26 20:01
@coretemp hash of what? what impurity?

**Comment by coretemp** [comment] 2018-05-26 20:09
A hash of the generated docker image. 

It is my understanding that you pushed two different pieces of software under the same name via:
`docker push nixos/nix:2.0`.

I would like to see a list of previous releases of the form  `nixos/nix:<hash>:2.0.2` (other formats according to your own insight).

You are doing exactly the kind of thing which Nix tools don't like (changing what is at a particular URL). The people that don't need stability can still use `latest`.

**Comment by domenkozar** [comment] 2018-05-27 12:37
Hash of generated docker image doesn't sound too useful to me, as docker should already include image id and hash of each layer. Maybe Nix git revision used when generated?

**Comment by coretemp** [comment] 2018-05-27 21:53
Abstractly what I want is clear, isn't it? Just something such that the same *name* where a name currently is nixos/nix:2.0 will either return the exact same data *or* no result (because of a lack of storage space) forever,

Additionally, it should be the case that one can reproduce the image and obtain the same result. I don't think that's the case with the current scheme, because it depends on a tarball on some server. The build should work with a git revision as input, since that is more guaranteed not to change.

**Comment by asymmetric** [comment] 2018-06-06 20:30
I think it would be enough if e.g. the `2.0.4` image would be pinned to the `2.0.4` git tag on this repo.

I don't think there needs to be a change in scheme for this to happen (additionally, `nixos/nix:<hash>:2.0.2` is not valid in Docker), it can simply be a convention and an implementation detail in the [`maintainers/upload-release.pl`](https://github.com/NixOS/nix/blob/master/maintainers/upload-release.pl).

**Comment by peti** [comment] 2018-06-07 06:26
I don't understand why it's necessary *at all* to update that docker image manually. Dockerhub can easily re-generate it automatically every time the underlying git repository changes; there's no need for us to do anything to trigger that.

@domenkozar, would it be possible to get the login data for that account? I'f love to take a look at the setup, if I may?

**Comment by coretemp** [comment] 2018-06-07 08:17
@asymmetric I am not sure why you would say that this would be enough, since I have said 10 days ago that it isn't.

**Comment by domenkozar** [comment] 2018-06-18 12:29
@peti excuse my radio silence, happy to give you access, what's your docker hub account?

**Comment by domenkozar** [comment] 2020-04-30 09:50
https://github.com/NixOS/docker

**Closed by domenkozar** 2020-04-30 09:50 UTC
Labels: feature
