### ISSUE TITLE
nix fails to install under macosx 10.13 (High Sierra) beta

### ISSUE THREAD

**Issue by LATBauerdick** [NixOS/nix#1414] opened 2017-06-17 05:37 UTC
Hi

here's the result of installing nix on maxosx 10.13 -- there seem to be changes to the dynlibs and `/usr/lib/system/coretls.dylib` went missing...  

My existing nix installation failed with the same error, after I upgraded to 10.13. 

```
$  curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2358  100  2358    0     0   1853      0  0:00:01  0:00:01 --:--:--  1853
downloading Nix 1.11.10 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-1.11.10/nix-1.11.10-x86_64-darwin.tar.bz2' to '/var/folders/f_/g24vrff54kd04lm0m742z6yh00060t/T/nix-binary-tarball-unpack.XXXXXXXXXX.h9vIT1uC'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.7M  100 24.7M    0     0  5578k      0  0:00:04  0:00:04 --:--:-- 5579k
performing a single-user installation of Nix...
copying Nix to /nix/store....................................
initialising Nix database...
dyld: Library not loaded: /usr/lib/system/libsystem_coretls.dylib
  Referenced from: /nix/store/v7i520r9c2p8z6vk26n53hfrxgqn8cl9-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
/var/folders/f_/g24vrff54kd04lm0m742z6yh00060t/T/nix-binary-tarball-unpack.XXXXXXXXXX.h9vIT1uC/unpack/nix-1.11.10-x86_64-darwin/install: line 67: 77488 Abort trap: 6           $nix/bin/nix-store --init
/var/folders/f_/g24vrff54kd04lm0m742z6yh00060t/T/nix-binary-tarball-unpack.XXXXXXXXXX.h9vIT1uC/unpack/nix-1.11.10-x86_64-darwin/install: failed to initialize the Nix database
```

Unfortunately I didn't manage to build from sources, so can't tell if there is an easy fix by providing new binaries. 

Thanks, LatB

**Comment by domenkozar** [comment] 2017-06-17 16:03
@LATBauerdick where is `coretls.dylib` now located?

**Comment by LATBauerdick** [comment] 2017-06-17 19:17
@domenkozar there is a `libcoretls.dylib` (without the `libsystem_` in front of it) in `/usr/lib':
```
$  ls -l /usr/lib/*coretls.dylib
-rwxr-xr-x  1 root  wheel  289344 May 31 23:00 /usr/lib/libcoretls.dylib
```

**Comment by LATBauerdick** [comment] 2017-06-17 19:25
and, indeed, putting a link into `/usr/lib` fixes the problem for the moment -- thanks @domenkozar !!
```
$ sudo ln -s /usr/lib/libcoretls.dylib /usr/lib/libsystem_coretls.dylib
$ curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2358  100  2358    0     0   4472      0 --:--:-- --:--:-- --:--:--  4465
downloading Nix 1.11.10 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-1.11.10/n
ix-1.11.10-x86_64-darwin.tar.bz2' to '/var/folders/f_/g24vrff54kd04lm0m742z6yh00060t/T/nix-binary-tarball-u
npack.XXXXXXXXXX.ekS1ov0T'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.7M  100 24.7M    0     0  5579k      0  0:00:04  0:00:04 --:--:-- 5580k
performing a single-user installation of Nix...
copying Nix to /nix/store....................................
initialising Nix database...
installing ‘nix-1.11.10’
building path(s) ‘/nix/store/wmx041jh85q5ymi3m58pw7hzimy319rp-user-environment’
created 7 symlinks in user environment
installing ‘nss-cacert-3.30’
building path(s) ‘/nix/store/hy1ij47h859730fszi2bdzwbrwcc07ij-user-environment’
created 9 symlinks in user environment
downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-17.09pre108299.ec9a
23332f/nixexprs.tar.xz’...
downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-17.09pre108299.ec9a23332f/nixexprs.tar.x
z’... [7311/8656 KiB, 7293.4 KiB/s]
unpacking channels...
created 2 symlinks in user environment

Installation finished!  To ensure that the necessary environment
variables are set, either log in again, or type

  . /Users/bauerdic/.nix-profile/etc/profile.d/nix.sh

in your shell.
```

**Comment by domenkozar** [comment] 2017-06-19 13:48
```
dyld: Library not loaded: /usr/lib/system/libsystem_coretls.dylib
  Referenced from: /nix/store/v7i520r9c2p8z6vk26n53hfrxgqn8cl9-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
```

means this needs to be addressed in nixpkgs actually cc @NixOS/darwin-maintainers

**Comment by copumpkin** [comment] 2017-06-21 13:54
Yup! Shouldn't be too hard to fix. I'd try to kill https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/Libsystem/reexported_libraries#L22 and see what happens. I'm still catching up from a long period of vacation so can't experiment for another few days, but if someone wants to try it I'd be happy to help consult on any problems you run into.

**Comment by copumpkin** [comment] 2017-07-13 03:41
@LATBauerdick if you want to test it: https://github.com/NixOS/nixpkgs/pull/27318#issuecomment-314952699

**Comment by bradleyjensen** [comment] 2017-08-18 01:25
Any ETA on when this will land?

**Comment by copumpkin** [comment] 2017-08-18 14:04
After 17.09 at this rate. Nix's own builds are pinned to 17.03 right now and we tried backporting the changes that would be needed to make it work on High Sierra but there was just too much that had changed, so we decided to just wait. In the meantime, I think [this script](https://gist.github.com/copumpkin/8373ae6c89236989ae4296771ba5aa14) should get you up and running for now.

**Comment by ssbarnea** [comment] 2017-08-30 12:40
I am looking forward to see this fixed in nix, without additional workarounds.

**Comment by domenkozar** [comment] 2017-09-12 20:37
Could you guys try Nix 1.11.15 built with 17.09 branch that should include the high sierra support? If it's confirmed to work we can release new Nix version:

```
$ curl https://static.domenkozar.com/nix-install-high-sierra | sh
```

PS: I realize you might not trust my source, sadly I can't provide any more official installer than this.

**Comment by copumpkin** [comment] 2017-09-13 02:13
@domenkozar that works fine, thanks 😄 just tested it on build 17A306f

**Comment by domenkozar** [comment] 2017-09-15 13:36
Nix 1.11.15 should be shortly released with the fix for High Sierra.

**Comment by copumpkin** [comment] 2017-09-15 18:20
It's released now and we should be able to close this ticket!

**Closed** 2017-09-15 18:28 UTC
Labels: darwin

**Comment by yihuang** [comment] 2018-02-28 02:35
I got this issue, my nix version is ``nix-env (Nix) 1.11.6``, how do I upgrade to 1.11.15, when I run ``nix-env -i nix``, it only installs ``1.11.8``, which is also problematic on high sierra.

**Comment by schell** [comment] 2018-02-28 19:33
I'm seeing this error and `nix-env --version` tells me `nix-env (Nix) 1.11.16` is there more to it that the env version?

**Comment by LnL7** [comment] 2018-02-28 19:35
With a multi-user install you'll also have to upgrade the daemon.

**Comment by schell** [comment] 2018-03-06 18:04
@yihuang that's funny, I'm running nix 2.0 as well. Maybe I have some dangling artifacts lying around in my PATH...

**Comment by narrowtux** [comment] 2020-12-29 12:42
Hello from 2020, I can't use `ln -s` to fix this issue, even with disabled SIP, because macOS lives on a readonly FS now. What should I do about it?
