### ISSUE TITLE
kernel oom-kill on nixos-rebuild switch

### ISSUE THREAD

**Issue by voobscout** [NixOS/nix#4363] opened 2020-12-15 13:48 UTC
nixos-rebuild switch --flake .#someSystem always fails with kernel oom-kill on a system with 4gb ram.

* How to find the places in nix code, that use lots of ram?
* How to profile nix closure memory usage?
* In general - what to do about systems with 512MB ram or less (i.e. VMs or arm boards)? How are we supposed to rebuild them?
* How to restrict nix to use only a certain amount of memory?
* Why does this problem exist in a first place?

**Comment by zimbatm** [comment] 2020-12-15 16:43
duplicate of https://github.com/NixOS/nix/issues/2664

**Closed by zimbatm** 2020-12-15 16:43 UTC
