### ISSUE TITLE
Support hard links within tar files being used as flake inputs type=tarball

### ISSUE THREAD

**Issue by gborgers** [NixOS/nix#10819] opened 2024-05-31 14:18 UTC
**Is your feature request related to a problem? Please describe.**
Support hard links within tar files being used as flake inputs type=tarball (see details [here](https://discourse.nixos.org/t/tarball-has-unsupported-file-type-lib/46258))

**Describe the solution you'd like**
Hard links are supported

**Describe alternatives you've considered**
Use input type=file, and manually extract the file during the unpackphase

**Additional context**

**Priorities**
Not too important

**Comment by edolstra** [comment] 2024-06-10 12:17
Duplicate of #10395.

**Closed by edolstra** 2024-06-10 12:17 UTC
Labels: feature, fetching
