### ISSUE TITLE
Can't eta-reduce with flakes: expected a function but got a thunk

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nix#4384] opened 2020-12-20 13:42 UTC
**Describe the bug**

I have a [`flake.nix`](https://github.com/lovesegfault/nix-config/blob/a3aefba126f08fcd81f97c4c232db122808c74cd/flake.nix) file, in which I moved the outputs into their own [`output.nix`](https://github.com/lovesegfault/nix-config/blob/a3aefba126f08fcd81f97c4c232db122808c74cd/output.nix)  file. 

If I try to eta-reduce the `outputs = args: import ./output.nix args;` call to simply be `outputs = import output.nix;` I get the following error:

```
❯ nix flake check
warning: Git tree '/home/bemeurer/src/nix-config' is dirty
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------- nix
expected a function but got a thunk at /nix/store/h21gfgrkjkhwl0f1ri2jhaqsdssrzm86-source/flake.nix:29:3
```

**Steps To Reproduce**

1. `mkdir flake-bug && cd flake-bug`
2. `echo "{ inputs = { }; outputs = import ./outputs.nix; }" > flake.nix`
3. `echo "{ ... }: { }"> outputs.nix`
4. `nix flake check`
5. See error

**Expected behavior**

I expected the thunk to be forced and understood by nix to be a function.

**`nix-env --version` output**
`nix-env (Nix) 2.4pre20201201_5a6ddb3`

**Comment by andir** [comment] 2020-12-20 15:31
Probably a duplicate of https://github.com/NixOS/nix/issues/3966 ?

**Comment by edolstra** [comment] 2020-12-21 13:26
Right, it's not allowed to have any evaluation to get the `outputs` function. This is because the arguments to `outputs` can specify flake inputs (e.g. `{ nixpkgs }: ...`).

**Closed by edolstra** 2020-12-21 13:26 UTC
Labels: bug
