### ISSUE TITLE
@-pattern and default values give unexpected results

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nix#1185] opened 2017-01-12 08:53 UTC
Combining @-pattern and default values give unexpected results as the whole argument set doesn't contains the default values attributes.

For example, this is working:

```
nix-repl> let f = args@{ x, y ? "foo", z ? "bar" }: z + y + x; in f { x = "baz"; }
"barfoobaz"
```

But this does not:

```
nix-repl> let f = args@{ x, y ? "foo", z ? "bar" }: args.z + y + x; in f { x = "baz"; }
error: attribute ‘z’ missing, at (string):1:43
```

By inspecting `args`, it appears that it contains only explicitly set values:

```
nix-repl> let f = args@{ x, y ? "foo", z ? "bar" }: args; in f { x = "baz"; }
{ x = "baz"; }
```

Expected result:

```
nix-repl> let f = args@{ x, y ? "foo", z ? "bar" }: args; in f { x = "baz"; }
{ x = "baz"; y = "foo"; z = "bar"; }
```

**Comment by edolstra** [comment] 2017-01-12 11:38
This is by design. `args@` defines an alias for the argument, which is not modified in any way.

Dupe of #745.

**Closed by edolstra** 2017-01-12 11:38 UTC

**Comment by ericsagnes** [comment] 2017-01-12 12:38
I see, thanks for the clarification!
