### ISSUE TITLE
Remove the contribution docs in the manual

### ISSUE THREAD

**Issue by infinisil** [NixOS/nix#9381] opened 2023-11-19 03:07 UTC
### Problem
This is the second time now that I tried to follow the contribution docs in [the stable docs](https://nixos.org/manual/nix/stable/), only to realise that it doesn't work because they're outdated.

### Proposed Solution

Don't render the contribution docs in the manual. Instead just use the GitHub markdown rendering.

### More context

See https://github.com/NixOS/nixpkgs/issues/244056 for the same change in Nixpkgs, also includes more arguments for why this should be done.

**Comment by fricklerhandwerk** [comment] 2023-12-10 15:57
Duplicate of #9583 :)

**Closed by fricklerhandwerk** 2023-12-10 15:57 UTC
Labels: documentation, contributor-experience
