### ISSUE TITLE
isFunction returns `false` for `primop-app`

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#2073] opened 2018-04-12 23:03 UTC
```
nix-repl> builtins.builtins.isFunction map
false
nix-repl> builtins.typeOf map
"lambda"
nix-repl> map
«primop»

nix-repl> builtins.builtins.isFunction (map (v: v))
false
nix-repl> builtins.typeOf (map (v: v))
"lambda"
nix-repl> map (v: v))
«primop-app»
```

https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L247-L251
https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L270-L275

I’d posit the primop/lambda distinction should be transparent on the nix expression level, `isFunction` should return `true` for `map` as well as `map id`.

cc @cleverca22

**Comment by ledettwy** [comment] 2018-04-16 18:29
Duplicate of https://github.com/NixOS/nix/issues/1424

**Comment by shlevy** [comment] 2018-04-16 23:45
@Profpatsch Any interest in giving a patch a shot?

**Comment by Profpatsch** [comment] 2018-04-17 16:50
@shlevy Ah, I’m sorry, I really don’t have enough C++ experience to fix this in any acceptable timeframe.

**Closed** 2018-04-17 20:42 UTC
Labels: improvement, triaged

**Comment by Profpatsch** [comment] 2018-04-18 22:37
Thanks!
