### ISSUE TITLE
Flakes: allow modules to be paths

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nix#7355] opened 2022-11-27 17:14 UTC
**Is your feature request related to a problem? Please describe.**

Setting `nixosModules.default = ./module.nix;` in a flake causes `nix flake check` to fail with `error: module must be a function or an attribute set`.

**Describe the solution you'd like**

Auto-import paths before checking modules.

**Context & alternatives**

The main use case for this is option declarations: with `imports = [ (import ./module.nix) ];`, the options from `module.nix` will have an unknown declaration file.

An alternative could be to extract location information from `import`ed modules with `unsafeGetAttrPos`. After all, that's how packages work, maybe modules shouldn't be different. See https://github.com/NixOS/nixpkgs/issues/15417

cc @roberth @infinisil

**Comment by roberth** [comment] 2022-11-27 17:51
A path is a valid module reference. The module system does not have this restriction in any user facing interfaces.

> `nix flake check`

Duplicate of https://github.com/NixOS/nix/issues/6866

**Closed by roberth** 2022-11-27 17:51 UTC
Labels: feature
