### ISSUE TITLE
`curl https://nixos.org/nix/install | sh` failed in mac OS catalina

### ISSUE THREAD

**Issue by zaoqi** [NixOS/nix#3143] opened 2019-10-12 16:19 UTC
[macOS Catalina Protects the OS in its Own Read-only Volume](https://www.macobserver.com/analysis/macos-catalina-protects-os-read-only-volume/)
```
downloading Nix 2.3.1 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-2.3.1/nix-2.3.1-x86_64-darwin.tar.xz' to '/var/folders/s0/m5vjyg1n3tz8vj6_hy_h7pq40000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.cIZTQYxr'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.1M  100 17.1M    0     0  1310k      0  0:00:13  0:00:13 --:--:-- 1794k
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown <USERNAME> /nix' using sudo
Password:
mkdir: /nix: Read-only file system
/var/folders/s0/m5vjyg1n3tz8vj6_hy_h7pq40000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.cIZTQYxr/unpack/nix-2.3.1-x86_64-darwin/install: please manually run 'mkdir -m 0755 /nix && chown <USERNAME> /nix' as root to create /nix
```
```
% sudo su
sh-3.2# mkdir -m 0755 /nix && chown <USERNAME> /nix
mkdir: /nix: Read-only file system
```

**Comment by Pandentia** [comment] 2019-10-12 23:01
This appears to be a duplicate of #2925.

**Closed** 2019-10-13 05:52 UTC
