### ISSUE TITLE
`placeholder "out"` does not work with `passAsFile`

### ISSUE THREAD

**Issue by adelbertc** [NixOS/nix#2199] opened 2018-05-31 23:48 UTC
`default.nix`:

```
let
  pkgs = import <nixpkgs> { };
in
  pkgs.writeShellScriptBin "hello" ''
    echo ${placeholder "out"}
  ''
```

Test:
```
~/dev/nix-experiments/placeholder-out ⊢ nix-build
/nix/store/0aamnh6hdr9qh34nzcl5r6anaj1zb5f8-hello
~/dev/nix-experiments/placeholder-out ⊢ ./result/bin/hello 
/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9
```

The expectation is `${placeholder "out"}` gives the Nix store path of the script, but:

1. Only what appears to be a suffix is given
2. Even if you prefix with `/nix/store` the path is bogus

Initial guess is this is due to the use of `passAsFile` by `writeShellScriptBin`

**Comment by shlevy** [comment] 2018-06-01 11:04
Since placeholder is Nix 2.0 only, I wonder if we can just use `__structuredAttrs` instead... Does `placeholder` work there?

**Comment by adelbertc** [comment] 2018-06-02 04:55
@shlevy Was that directed at me? Reading up on `__structuredAttrs` not sure what you mean

**Comment by jtojnar** [comment] 2019-01-27 21:09
Duplicate of https://github.com/NixOS/nix/issues/1846

**Comment by FlorianFranzen** [comment] 2021-06-28 20:03
Should have been fixed by #3463, so probably can be closed.

**Closed** 2021-06-29 07:14 UTC
