### ISSUE TITLE
allowSubstitutes is an anti-feature

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#4442] opened 2021-01-11 14:32 UTC
I can't describe how many hours I and people I have helped have lost to save a few miliseconds of machine time.

For example `preferLocalBuild` ignores builders and `--max-jobs` per https://github.com/NixOS/nix/issues/3810 giving the user the impression that flags are being ignored.

Having such exceptions completely change the way Nix works makes it also really hard to debug binary cache issues - I've gotten lots of reports of why is binary cache not substituting.

Refs #3686

**Comment by domenkozar** [comment] 2021-01-11 14:43
Oh and another point: the reason the user might be using remote builder / binary cache is to avoid HDD space pollution and there's no way to disable that.

**Comment by grahamc** [comment] 2021-01-11 14:55
I think I would rather keep `preferLocalBuild` and have it respect `--max-jobs` instead. I don't relish the idea of uploading 10's of GB of data to a remote server over DSL to write a short text file, just to download it again.

**Comment by Ninlives** [comment] 2021-01-11 15:01
the `preferLocalBuild` overwrites the `--max-jobs` may be an anti-feature, but allowSubstitutes/preferLocalBuild themselves are useful. I do not want to waste time on querying binary cache when I just want to write a text file.

**Comment by Ma27** [comment] 2021-01-11 15:05
The problem I have with removing `preferLocalBuild` is that I regularly use it to configure on a per-derivation level whether or not I want remote builds. As @grahamc stated, this is helpful to avoid uploading tons of data to a remote server just to build e.g. a proprietary package where only an unpack and a `patchelf` happens. This is particularly helpful for me since I'm regularly (not during the pandemic though) at places where I have rather bad internet.

**Comment by domenkozar** [comment] 2021-01-11 15:14
It's a great power feature that hits Nix beginners really had and given that it's used in nixpkgs there no opt-out.

Of course all expirienced Nix users will say they have no problem with it, but it makes behavior with substituters and remove builders hard to debug and reason about.

**Comment by bgamari** [comment] 2021-01-11 15:18
I use `preferLocalBuild` quite heavily as it can mean the difference between waiting a few seconds and a few minutes in the case of derivations with large inputs and outputs.

**Comment by domenkozar** [comment] 2021-01-11 15:29
I often (need to start tracking how often) get Cachix support request why is something not being substituted and I have templated an answer, but the response from Nix beginners is usually: wow

This probably can be fixed with better logging/messaging and fixing all the bugs, but I feel like that's one of those things that will never materialize.

**Comment by Ma27** [comment] 2021-01-11 15:31
Maybe it would help to make this clear in at least the new progress bar that's currently under development: https://github.com/NixOS/nix/pull/4296

**Comment by domenkozar** [comment] 2021-01-11 15:42
I understand that `preferLocalBuild` can save minutes, but `allowSubstitutes` saving is really marginal: as those paths still need to be uploaded, so really you only save the substitution.

For preferLocalBuild there should at least be good `-v` story to explain why something was built where it was.

**Comment by roberth** [comment] 2021-01-11 19:14
`allowSubstitutes` can cause the download of build tools for small store paths that have already been built and uploaded. It's really not that clever, last time I checked. Mostly relevant for C/D agents and other cases where only runtime closures are necessary.

**Comment by rickynils** [comment] 2021-01-12 00:49
From the discussion here, it seems there is a majority in favor of keeping `preferLocalBuild` as it works today, but do something about the `max-jobs=0` situation. I'm also of the opinion that text files and similar should be built locally by default, but that it should be possible to not build them locally. The "prefer" word seems to me imply that this was intended from the start, and that the `max-jobs=0` behavior is just a bug. I've opened a [PR](https://github.com/NixOS/nix/pull/4443) resolving that bug.

**Comment by bhipple** [comment] 2021-06-23 17:49
`preferLocalBuild = true` I can sorta understand, but is there any real use case for `allowSubstitutes = false`?  I'm running into issues with CI and https://github.com/NixOS/nix/issues/4364, and while I see there are workarounds like https://github.com/Mic92/nix-build-uncached/#packages-with-allowsubstitutes--false I'm wondering if I should just patch `nix` itself to always return `allowSubstitutes = true`?

**Comment by ajs124** [comment] 2021-06-23 18:30
> is there any real use case for `allowSubstitutes = false`

https://github.com/NixOS/nixpkgs/pull/123943

**Comment by domenkozar** [comment] 2021-06-24 11:35
That seems like a bug to me rather than a use case for allowSubstitutes.

**Comment by colemickens** [comment] 2021-10-09 20:13
As described in #5358 this lends itself to some very frustrating user experiences. It is very disappointing to me that `nix-store -r --dry-run` and `nix-build --dry-run` can basically give a completely different answer, all owing to this "feature".

**Comment by bgamari** [comment] 2021-10-11 11:31
I think it is important that we split the question here: I personally see very good reasons for having `preferLocalBuild`; I would be strongly opposed to removing it without providing some other way to avoid extraneous network I/O for "trivial" derivations. On the other hand, I couldn't care less about `allowSubstitutes`.

**Comment by rickynils** [comment] 2021-11-10 10:03
NixOS' top-level `system` derivation has `allowSubstitutes = false`, which means building NixOS configs can take quite a bit longer than really necessary, if you for example run the build from a CI machine with an empty nix store (like GitHub Actions). Then Nix will try to build all dependencies of the system individually instead of just fetching the top level derivation with its dependency closure from a binary cache.

Some interesting history:
`allowSubstitutes = false` was implied if `preferLocalBuild = true`, but this was changed by @edolstra in https://github.com/NixOS/nix/commit/b64988bb3585478676585a0f0aecbcf4e11d4432. In that commit, Eelco states that `allowSubstitutes = false` is kind of hurtful for performance.

I think we have some different options for improving this situation:

* Nuke `allowSubstitutes` and simply ignore the fact that under some specific circumstances it could be faster to build a derivation than to fetch it (though you still have the ability to control this with `preferLocalBuild`)
* Make it possible override `allowSubstitutes` with a Nix option (something like `always-substitute`). That way you can force substitution when it makes sense for you (like in CI etc).
* Nuke `allowSubstitutes` and instead race building and fetching against each other. This could either be done for all derivations or just for the ones that has `allowSubstitutes = false` today.

**Comment by roberth** [comment] 2021-11-10 11:24
@rickynils perhaps another option:

* Ignore `allowSubstitutes` and honor `preferLocalBuild` only when all dependencies* are already present. This is 
   - quick on user systems and build agents with a persistent store
   - but also efficient for pre-built server configs, ephemeral build environments
   - and it does not put undue load on binary caches (from races with a predictable winner)


*: all dependencies, perhaps excluding dependencies that have `preferLocalBuild = true` themselves so as to allow not just single derivations but subgraphs of `preferLocalBuild` derivations to behave as suggested.

I'd have to read up on the updated 2.4 realisation logic tbh.

**Comment by Kha** [comment] 2021-11-10 11:33
Has there been any proposal for finer-grained (per-derivation/flake) substituter lists? It seems like `allowSubstitutes = false` is often used to mean "well it's certainly not in cache.nixos.org". Now that substituters can be configured in `flake.nix`, it would be an interesting optimization to apply only them and not cache.nixos.org to derivations of that flake. Though "derivations of that flake" is not a concept that exists right now afaik and could be subtle regarding overrides etc...

**Comment by michaelpj** [comment] 2021-11-10 17:23
> Nuke allowSubstitutes and instead race building and fetching against each other.

Interesting. I suggested this a long time ago in https://github.com/NixOS/nix/issues/3019 as a way to make adding substituters guaranteed to never slow things down, I think you're right that it would also make `allowSubstitutes` pointless.

**Comment by Gerschtli** [comment] 2022-10-29 22:28
Any news here? This issue still is relevant.

**Comment by nrdxp** [comment] 2022-11-02 23:33
some derivations with `preferLocalBuild` may have heavy dependencies that should still be substituted (a NixOS system derivation is one good example). I currently build my own system in CI using a remote store build (`--store`) and then upload the result to my cache using `nix copy`.

What I would prefer is if `nix copy` just had a flag to ignore any derivations in the chain of dependencies that have `preferLocalBuild` set. That way I can still build all the heavy dependencies in CI and ensure they are cached while not wasting time and cache space on those derivations that are gonna be built locally anyway.

**Comment by lovesegfault** [comment] 2023-03-13 19:37
I have a PR in `nixpkgs` which allows users to configure `allowSubstitutes` to be ignored: https://github.com/NixOS/nixpkgs/pull/221048

It's not a perfect solution, since it causes rebuilds, but it does help.

**Comment by domenkozar** [comment] 2023-07-18 09:56
It also breaks horribly if your local system doesn't match the one you're substituting, as Nix will try to build and fails because it can't.

**Comment by elaforge** [comment] 2023-10-09 17:58
Just to pile on here, I spent quite a bit of time debugging due to `allowSubstitutes=false`, because it causes `queryUnbuilts` to basically lie.  I had to go tracing down into the queryUnbuilts source to finally find the hardcoded thing in there, and before that while I knew (and heavily use) `preferLocalBuilds` I had no idea `allowSubstitutes=false` existed.  I'm still not really sure why both are needed.

Now that I know it exists, it means I can't trust `queryUnbuilts` output, but have to do a two step: queryUnbuilts, then for things it claims are unbuilt, parse the drvs to their outs, and then `wopQuerySubstitutablePaths` on those outs... which seems to not use narinfo cache or local cache so is less efficient, though I'm not sure.  I couldn't find any documentation for narinfo cache at all, let alone which ops use it.  Anyway different story.

I think over the years this was also the source of a lot of mysterious rebuilds I never understood, that went away when we stopped using nixpkgs `writeText` and wrote our own.

**Comment by lovesegfault** [comment] 2023-10-13 13:46
Folks, I'm happy to report that https://github.com/NixOS/nix/pull/8047 has been merged!

In the next release, you'll be able to completely disable `allowSubstitutes` by setting `always-allow-substitutes = true` 🥳

**Comment by elaforge** [comment] 2023-10-13 21:29
Nice, just slightly disappointed it wasn't named `disallow-allow-substitutes-is-false = true` for maximum confusion.

**Comment by fricklerhandwerk** [comment] 2023-12-02 01:48
Closed by #8047

**Closed** 2023-12-02 01:48 UTC
