### ISSUE TITLE
nix-shell /path/to/dir no longer works in 1.12

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#1319] opened 2017-04-10 19:31 UTC
On 1.11 invocations like

```console
$ nix-shell /path/to/dir
```
Did the same thing as
```console
$ nix-shell /path/to/dir/default.nix
```
(note that it ignored 'shell.nix' if present)

This no longer works with 1.12:
```
$ nix-shell /path/to/dir
error: reading from file: Is a directory
```

This syntax is useful for switching between nix-build and nix-shell, for example.

Is this intentional or a bug?

**Comment by roberth** [comment] 2024-08-16 12:38
Could not reproduce the example.

> (note that it ignored 'shell.nix' if present)

This has been [fixed in Nix 2.24](https://nix.dev/manual/nix/2.24/release-notes/rl-2.24)

**Closed by roberth** 2024-08-16 12:38 UTC
Labels: bug, cli, nix-shell
