### ISSUE TITLE
Nix fails to download anything. `error: unexpected end-of-file`

### ISSUE THREAD

**Issue by zennad** [NixOS/nix#2701] opened 2019-02-25 00:45 UTC
My nix installation cannot download anything without failing with an error message:
'error: unexpected end-of-file'

Here is the output of running `upgrade-nix`

```
$ nix -v --debug upgrade-nix
found Nix in '/nix/var/nix/profiles/default/bin'
found profile '/nix/var/nix/profiles/default'
upgrading Nix in profile '/nix/var/nix/profiles/default'
querying latest Nix version...
downloading 'https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix'...
starting download of https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix
finished download of 'https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix'; curl status = 0, HTTP status = 200, body = 292 bytes
resolved search path element '/nix/store/1jz25hcma179wbpi56blgajw47n5kgqd-nix-2.2.1/share/nix/corepkgs' to '/nix/store/1jz25hcma179wbpi56blgajw47n5kgqd-nix-2.2.1/share/nix/corepkgs'
checking access to '/nix/store/1jz25hcma179wbpi56blgajw47n5kgqd-nix-2.2.1/share/nix/corepkgs/derivation.nix'
evaluating file '/nix/store/1jz25hcma179wbpi56blgajw47n5kgqd-nix-2.2.1/share/nix/corepkgs/derivation.nix'
downloading '/nix/store/a48whqkmxnsfhwbk6nay74iyc1cf0lr2-nix-2.2'......
querying info about missing paths...
starting pool of 7 threads
checking substituter 'https://cache.nixos.org' for path '/nix/store/a48whqkmxnsfhwbk6nay74iyc1cf0lr2-nix-2.2'
querying info about '/nix/store/a48whqkmxnsfhwbk6nay74iyc1cf0lr2-nix-2.2' on 'https://cache.nixos.org'...
downloading 'https://cache.nixos.org/a48whqkmxnsfhwbk6nay74iyc1cf0lr2.narinfo'...
starting download of https://cache.nixos.org/a48whqkmxnsfhwbk6nay74iyc1cf0lr2.narinfo
closing daemon connection because of an exception
[0.0 MiB DL]
error: unexpected end-of-file
download thread shutting down
```

**Comment by Merlynfry** [comment] 2019-02-25 15:57
I forgot to mention. My system is macOS 10.14 mojave.

**Comment by LnL7** [comment] 2019-02-25 17:08
Duplicate of https://github.com/NixOS/nix/issues/2523.

**Closed** 2019-09-16 19:51 UTC
